export function sampleClock(seconds:number):string{const safe=Number.isFinite(seconds)?Math.max(0,Math.floor(seconds)):0;return `${Math.floor(safe/60)}:${String(safe%60).padStart(2,'0')}`;}
export function waveformPeaks(samples:Float32Array,count=56):number[]{if(!samples.length)return[];return Array.from({length:count},(_,i)=>{const start=Math.floor(i*samples.length/count),end=Math.max(start+1,Math.floor((i+1)*samples.length/count));let peak=0;for(let j=start;j<Math.min(end,samples.length);j++)peak=Math.max(peak,Math.abs(samples[j]));return Math.min(1,peak);});}
export function cloneRequirements({allowed,pending,hasFile,name,consent,authorized,owner,recording}:{allowed:boolean;pending:boolean;hasFile:boolean;name:string;consent:boolean;authorized:boolean;owner:string;recording:boolean}):string[]{return [...(!allowed&&!pending?['Enable instant voice cloning in the connected ElevenLabs account.']:[]),...(!name.trim()?['Give this voice a name.']:[]),...(authorized&&!owner.trim()?['Enter the name of the person who authorized you.']:[]),...(recording?['Stop recording to review your sample.']:!hasFile?['Record or upload your voice sample.']:[]),...(!consent?['Confirm permission to create and use this voice.']:[])];}
export const voiceReadingScript=[
 "Hi, thanks for taking a moment to speak with me. My name is your name here, and I’m glad we could connect. I’d like to understand what you’re working on, what matters most to you, and where I can be helpful.",
 "Could you tell me a little about your business? What does a successful week look like for your team? I’m listening. There’s no need to rush. If something isn’t clear, please stop me and we’ll go through it together.",
 "Let’s imagine we’re planning a short follow-up conversation. Would Tuesday at ten thirty work better, or would you prefer Thursday at two fifteen? We can set aside twenty minutes, review three priorities, and agree on one useful next step.",
 "I understand that timing and budget are important. You don’t have to make a decision today. My job is to explain the options clearly, answer your questions, and help you decide what makes sense for you.",
 "Thank you for sharing that with me. Before we finish, is there anything else you’d like me to know? I’ll send a brief summary so we both have the same information. Have a great rest of your day, and I look forward to speaking again."
] as const;
