import type { EffectiveWorkflowRoute } from './lead-engine-niches.ts';

const sourceNames: Record<string,string> = {wa_lni:'Washington contractor register',or_ccb:'Oregon contractor register',cslb:'California contractor register',fl_dbpr_construction:'Florida construction license records',mn_dli:'Minnesota contractor license records',austin_permits:'Austin permit records',ny_attorneys:'New York attorney register',fl_dfs_individual:'Florida insurance license records',tx_tdi:'Texas insurance license records',nppes:'National provider directory',nppes_medspa:'Provider-directory med-spa candidates',fmcsa:'Motor carrier register',irs_ptin:'Tax preparer directory',tx_tabc:'Texas liquor license records',ny_doh_food:'New York food inspection records',nola_str:'New Orleans rental permits',orlando_str:'Orlando rental permits',ny_salons:'New York establishment licenses',fl_dbpr_barbers:'Florida barbershop licenses',fl_re:'Florida real estate licenses',tx_trec:'Texas real estate licenses',az_adre:'Arizona real estate licenses',fl_cpa:'Florida accounting licenses',il_idfpr:'Illinois IDFPR license records',pa_pals:'Pennsylvania professional licenses',pa_childcare:'Pennsylvania childcare records',ny_childcare:'New York childcare records',tx_childcare:'Texas childcare records',ny_repair_shops:'New York repair-shop records',co_sos_agents:'Colorado company records'};
export function sourceName(source:string|null|undefined):string { return source ? sourceNames[source.split(':')[0]] ?? 'Mapped register (see technical details)' : 'No register selected'; }
export interface ToolNode { id:string; title:string; tool:string; input:string; output:string; why:string; tone?:'normal'|'warning'|'stop'; optional?:boolean }
export interface ToolFlow { reason:string; start:ToolNode[]; question:string; yes:ToolNode[]; no:ToolNode[]; noJoins:boolean; final:ToolNode[]; optional:ToolNode[]; blocked:boolean; sourceScope:string|null; tools:string[]; branchNote:string|null }
const node=(id:string,title:string,tool:string,input:string,output:string,why:string,tone:ToolNode['tone']='normal'):ToolNode=>({id,title,tool,input,output,why,tone});
export function toolFlow(route:EffectiveWorkflowRoute|undefined,niche:string):ToolFlow {
  const recipe=route?.recipe, isB=recipe==='B', isA=recipe==='A', isD=recipe==='D', isC=recipe==='C';
  const source=sourceName(route?.source), isIllinois=route?.source?.startsWith('il_idfpr')??false;
  const verification=node('verify','Check the phone','BatchData · phone verification','One existing phone number','Mobile/landline, reachability, DNC and TCPA flags','This checks a number we already have. It does not find a missing phone or prove who answers. Fresh stored checks may be reused.');
  const read=node('registry','Read the license records',source,'Imported records for the selected niche and state',isIllinois?'Licensee name, license status and location. No phone field.':isC||isD?'Register records and their supplied phone numbers':'Named licensees; contact fields depend on the source','The runner reads records previously imported into Supabase. Choosing this screen does not download or import a register.');
  const filter=node('filter','Select records for this job','NBC rules + Supabase',isA?'Business listings':'Imported register records',isA?'Niche-matching businesses with usable phone numbers':'Records matching this job’s source and filters',isA?'Apply niche relevance and phone checks before paying for verification.':'Apply source/type filters and duplicate/shared-number exclusions. A license holder is not automatically the business owner.');
  const start:ToolNode[]=isA?[node('discover','Find the businesses','Apify · Google Maps scraper','Business type + selected city','Business names, listing URLs and advertised phones','Maps supplies business listings. Apify is the tool that collects them.'),filter]:[read,filter];
  if(isD) start.push(node('compare','Compare two views of the same business','Apify + NBC matching rules','Register contacts + Google Maps listings','Same number / different number / no listing match','The engine matches businesses and compares phone numbers. A different number is a lead to check, not a proven owner line.'));
  const no = isB ? [node('enrichment','Existing missing-phone branch',`${route?.enrichmentSource ?? (route?.registerAddressUsed ? 'Existing register-address branch' : 'Existing record adapter')} + BatchData lookup`,'A record with no phone','A candidate phone, no match, or a stopped row','The older runner contains residential enrichment here. This diagram documents its dependency, not a validated business-contact method. No lookup is run from this page.','warning')]
    : [node('exclude','Do not send an empty number','NBC exclusion rules','No usable phone number','Excluded or unresolved record','A missing phone is not a successful contact. This path does not invent a number.','stop')];
  const final=[node('gates','Apply delivery rules','NBC rules + Supabase','Phone result and its source evidence','Eligible candidates, held rows, or flagged rows','Check exclusions, duplicates and time zone. Calling restrictions follow the job’s DNC mode; flagged rows stay marked do-not-call. Ownership remains unconfirmed.'),node('save','Save the result','Supabase + NBC export','The recorded outcome and provenance','Job results and spreadsheet rows','Keeps the contact, source and status together so an unsuccessful or restricted result is not presented as a confirmed owner contact.')];
  const optional:ToolNode[] = isA||isD ? [node('owner','Try to add a missing owner name','Website reader → Apify reviews → Anthropic Haiku','An eligible delivered phone with no owner name','An extracted name, or the owner field stays empty','The website is checked first. Review scraping and Haiku are conditional, metered fallbacks. This adds name evidence; it does not verify that the person owns the phone.')] : [];
  const reason=isIllinois?'Illinois IDFPR gives us licensed people, but this importer stores no phone number. That is why this route cannot work like a phone-bearing register. The missing-phone branch below is the older dependency that still needs validation.'
    :isB?'This route starts with named license holders. If a record already has a phone, BatchData checks it. If it has no phone, the existing runner takes a separate enrichment branch. Those are different operations, shown below.'
    :isA?route?.fallback?'The register path is unavailable here, so the current fallback uses Apify to collect Google Maps business listings and BatchData to check their phones.':'Apify finds businesses advertising this service on Google Maps. BatchData then checks their published numbers. No connected register has replaced this starting point.'
    :isC?'The mapped register supplies phone numbers, so the runner sends those existing numbers to BatchData. It does not need an Apify Maps search for this method.'
    :isD?'The register supplies contacts. Apify adds the business listing, and NBC compares the two phone numbers before BatchData checks the candidate. This reveals differences that a Maps-only search would miss.'
    :'No route could be resolved. The missing configuration must be inspected before execution.';
  if(!recipe) return {reason,start:[node('missing','No configured source','NBC route selector','Niche + state','No route','There is no resolved method to diagram.','stop')],question:'Is a route available?',yes:[],no:[],noJoins:false,final:[],optional:[],blocked:true,sourceScope:null,tools:['NBC route selector'],branchNote:null};
  return {reason,start,question:'Do we already have a usable phone?',yes:[verification],no,noJoins:isB,final,optional,blocked:route?.blocked??true,
    sourceScope:isIllinois?`Illinois import: ${niche==='realtor'?'managing brokers':'CPAs / managing brokers'} only. The existing enrichment dependency is ${route?.enrichmentSource??'not resolved'}${route?.enrichmentCounty?`; limited to ${route.enrichmentCounty} County`:''}.`:route?.enrichmentCounty?`Existing enrichment dependency: ${route.enrichmentSource}. County coverage: ${route.enrichmentCounty}.`:null,
    tools:[...(isA||isD?['Apify']:[]),...(!isA?[source]:[]),'BatchData','Supabase',...(optional.length?['Website reader','Anthropic Haiku (conditional)']:[])],
    branchNote:isIllinois?'For this Illinois importer, records enter the NO branch because no phone is stored. The YES branch shows how the same runner handles a record that already has a phone.':isB?'The missing-phone branch uses its own BatchData lookup result before delivery rules. It does not run the same phone-verification request twice.':null};
}
