"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Check, CheckCheck, Circle, Flag, Map, Pencil, Play, Plus, Trash2, BookOpen, LockKeyhole } from 'lucide-react';
import type { OverviewPreferences } from '@/lib/overview-layout';
import { lessonMedia } from '@/lib/overview-layout';
import type { AcademyDocument, AcademySummary } from '@/lib/academy-storage-types';
import type { MemberSummary } from '@/lib/member-types';
import { OverviewDialog } from './OverviewDialog';
import { RoadmapPreview } from './RoadmapPreview';
import { listLessonInventories, readLessonInventory } from './useOverviewData';
import styles from './PlatformHome.module.css';
type Update = (change: (old: OverviewPreferences) => OverviewPreferences) => void;
export function RoadmapWidget({ preferences, update, membership }: { preferences: OverviewPreferences; update: Update; membership: MemberSummary | null }) {
  const [editing, setEditing] = useState<string | null>(null), [title, setTitle] = useState('');
  const [showExample, setShowExample] = useState(preferences.milestones.length === 0);
  const done = preferences.milestones.filter(m => m.completed).length;
  if (showExample) return <RoadmapPreview onClose={() => setShowExample(false)} />;
  return <div className={styles.roadmapBody}><div className={styles.roadmapVisual} aria-hidden="true"><svg viewBox="0 0 500 115"><defs><linearGradient id="roadmap-route"><stop stopColor="var(--chart-1)" /><stop offset="1" stopColor="var(--chart-2)" /></linearGradient></defs><path d="M28 79 C86 79 74 24 136 24 S180 84 249 84 S315 24 370 24 S421 74 470 74" fill="none" stroke="var(--line)" strokeWidth="3" strokeDasharray="5 7" /><path d="M28 79 C86 79 74 24 136 24" fill="none" stroke="url(#roadmap-route)" strokeWidth="3" className={styles.routeLine} />{[[28,79],[136,24],[249,84],[370,24],[470,74]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="13" fill={i===0?'var(--chart-1)':'var(--soft)'} stroke={i===0?'var(--chart-1)':'var(--line)'} strokeWidth="2" /><circle cx={x} cy={y} r="3" fill={i===0?'#ffffff':'var(--muted)'} /></g>)}</svg><span>ONE STEP CLOSER.</span></div>
    <div className={styles.roadmapStatus}><span className={styles.stepIcon}>{membership?.completed ? <Check size={16} /> : <Map size={16} />}</span><div><strong>{membership === null ? 'Onboarding status unavailable' : membership.completed ? 'Onboarding complete' : 'Start with your onboarding'}</strong><small>{membership?.completed ? 'Build your personal action plan below.' : 'Give your NBC team a starting point.'}</small></div><Link href="/members" aria-label="Open your member roadmap"><ArrowUpRight size={18} /></Link></div>
    {preferences.milestones.length ? <><div className={styles.progressLabel}><span>Your personal milestones</span><strong>{done} / {preferences.milestones.length}</strong></div><div className={styles.progressTrack}><i style={{ width: `${done / preferences.milestones.length * 100}%` }} /></div><ul className={styles.milestoneList}>{preferences.milestones.map(m => <li key={m.id}><button aria-label={`${m.completed ? 'Reopen' : 'Complete'} milestone: ${m.title}`} aria-pressed={m.completed} className={styles.checkButton} onClick={() => update(p => ({ ...p, milestones: p.milestones.map(item => item.id === m.id ? { ...item, completed: !item.completed } : item) }))}>{m.completed ? <Check size={17} /> : <Circle size={17} />}</button><span className={m.completed ? styles.completedText : undefined}>{m.title}</span><button className={styles.iconButton} aria-label={`Edit milestone: ${m.title}`} onClick={() => { setTitle(m.title); setEditing(m.id); }}><Pencil size={14} /></button></li>)}</ul></> : <p className={styles.bodyNote}>A clear next step changes everything. Add your first milestone.</p>}
    <button className={styles.textButton} disabled={preferences.milestones.length >= 30} onClick={() => { setTitle(''); setEditing('new'); }}><Plus size={16} />Add milestone</button>
    <button className={styles.textButton} onClick={() => setShowExample(true)}>Preview example<ArrowUpRight size={14}/></button>
    {editing && <OverviewDialog title={editing === 'new' ? 'Your next milestone' : 'Edit milestone'} subtitle="Your personal plan, saved on this browser." onClose={() => setEditing(null)}><form className={styles.dialogForm} onSubmit={e => { e.preventDefault(); if (!title.trim()) return; update(p => ({ ...p, milestones: editing === 'new' ? [...p.milestones, { id: crypto.randomUUID(), title: title.trim(), completed: false }] : p.milestones.map(m => m.id === editing ? { ...m, title: title.trim() } : m) })); setEditing(null); }}><label>Milestone<input autoFocus maxLength={120} required value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Practice my opening with my coach" /></label><div className={styles.dialogActions}>{editing !== 'new' && <button type="button" className={styles.dangerButton} onClick={() => { update(p => ({ ...p, milestones: p.milestones.filter(m => m.id !== editing) })); setEditing(null); }}><Trash2 size={16} />Delete milestone</button>}<button type="submit" className={styles.primaryButton} disabled={!title.trim()}>Save milestone<Check size={16} /></button></div></form></OverviewDialog>}
  </div>;
}
function LessonPicker({ token, selected, onPick, onClose }: { token: string; selected: OverviewPreferences['lesson']; onPick(value: NonNullable<OverviewPreferences['lesson']>): void; onClose(): void }) {
  const [inventories, setInventories] = useState<AcademySummary[]>([]), [next, setNext] = useState<number | null>(null), [document, setDocument] = useState<AcademyDocument | null>(null), [inventoryId, setInventoryId] = useState(selected?.inventoryId ?? ''), [error, setError] = useState(''), [busy, setBusy] = useState(true), [retry, setRetry] = useState(0);
  useEffect(() => { const c = new AbortController(); setBusy(true); setError(''); void listLessonInventories(token, 0, c.signal).then(page => { if (c.signal.aborted) return; setInventories(page.inventories); setNext(page.nextOffset); }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setBusy(false); }); return () => c.abort(); }, [token, retry]);
  useEffect(() => { if (!inventoryId) return; const c = new AbortController(); setBusy(true); setError(''); setDocument(null); void readLessonInventory(token, inventoryId, c.signal).then(result => { if (!c.signal.aborted) setDocument(result.inventory); }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setBusy(false); }); return () => c.abort(); }, [token, inventoryId, retry]);
  const lessons = document?.manifest.courses.flatMap(course => course.modules.flatMap(module => module.lessons.map(lesson => ({ ...lesson, course: course.title, module: module.title }))));
  return <OverviewDialog title="Choose your next lesson" subtitle="Choose from the Academy content available to your account." onClose={onClose}><div className={styles.dialogForm}>
    <label>Academy collection<select value={inventoryId} onChange={e => setInventoryId(e.target.value)}><option value="">Select a collection</option>{inventories.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label>
    {next !== null && <button className={styles.textButton} disabled={busy} onClick={() => { setBusy(true); void listLessonInventories(token, next).then(page => { setInventories(old => [...old, ...page.inventories]); setNext(page.nextOffset); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Load more collections</button>}
    {busy ? <p role="status" className={styles.bodyNote}>Loading your Academy…</p> : error ? <div className={styles.inlineError} role="alert">{error}<button className={styles.textButton} onClick={() => setRetry(n => n + 1)}>Try again</button></div> : !inventories.length ? <div className={styles.emptyContent}><BookOpen /><strong>Your Academy is getting ready.</strong><p>Lessons will be available when your team adds the content.</p><Link className={styles.textButton} href="/academy">Open Academy<ArrowUpRight size={15} /></Link></div> : document && <div className={styles.lessonOptions}>{lessons?.length ? lessons.map(lesson => <button key={lesson.id} onClick={() => { onPick({ inventoryId, lessonId: lesson.id }); onClose(); }}><span className={styles.lessonOptionIcon}><Play size={17} /></span><span><small>{lesson.course} · {lesson.module}</small><strong>{lesson.title}</strong><small>{lesson.videoUrl ? 'Video reference available' : 'Video not added yet'}</small></span><ArrowUpRight size={17} /></button>) : <p className={styles.bodyNote}>This collection does not contain any lessons yet.</p>}</div>}
  </div></OverviewDialog>;
}
export function LessonWidget({ token, preferences, update }: { token: string; preferences: OverviewPreferences; update: Update }) {
  const selected = preferences.lesson;
  const [document, setDocument] = useState<AcademyDocument | null>(null), [picker, setPicker] = useState(false), [playing, setPlaying] = useState(false), [error, setError] = useState(''), [loading, setLoading] = useState(false), [retry, setRetry] = useState(0);
  useEffect(() => { setPlaying(false); setDocument(null); setError(''); if (!selected) return; const c = new AbortController(); setLoading(true); void readLessonInventory(token, selected.inventoryId, c.signal).then(result => { if (!c.signal.aborted) setDocument(result.inventory); }).catch(e => { if (!c.signal.aborted) setError(e.message); }).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, [token, selected?.inventoryId, selected?.lessonId, retry]);
  const lessons = document?.manifest.courses.flatMap(course => course.modules.flatMap(module => module.lessons.map(lesson => ({ ...lesson, course: course.title }))));
  const nextLesson = lessons?.[(lessons?.findIndex(l => l.id === selected?.lessonId) ?? -1) + 1];
  const lesson = lessons?.find(l => l.id === selected?.lessonId), media = lessonMedia(lesson?.videoUrl), key = selected ? `${selected.inventoryId}/${selected.lessonId}` : '', completed = preferences.completedLessons.includes(key);
  return <div className={styles.lessonBody}>
    <div className={styles.lessonMedia}>{playing && media?.kind === 'embed' ? <iframe className={styles.video} src={media.url} title={lesson?.title || 'Academy lesson'} allow="fullscreen; encrypted-media; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /> : playing && media?.kind === 'video' ? <video className={styles.video} controls preload="metadata" src={media.url} onError={() => setError('This video could not be played. You can open its source or choose another lesson.')} /> : <button className={styles.videoPoster} aria-label={lesson && media ? `Play lesson: ${lesson.title}` : 'Choose an Academy lesson'} onClick={() => { if (lesson && media) { if (media.kind === 'link') window.open(media.url, '_blank', 'noopener,noreferrer'); else setPlaying(true); } else setPicker(true); }}><span className={styles.posterGrid} /><span className={styles.posterBrand}>NBC<span>ACADEMY</span></span><span className={styles.playButton}>{lesson && !media ? <LockKeyhole size={22} /> : <Play size={23} fill="currentColor" />}</span><span className={styles.posterCaption}>{lesson && media ? 'YOUR NEXT MOVE' : 'A LITTLE BETTER. EVERY DAY.'}</span></button>}</div>
    <div className={styles.lessonDetails}><div className={styles.lessonCopy}><span className={styles.eyebrow}>{lesson?.course || 'BUILD YOUR EDGE'}</span><h3>{loading ? 'Loading your lesson…' : lesson?.title || 'Make learning part of your day.'}</h3>{error ? <div className={styles.inlineError} role="alert">{error}<button className={styles.textButton} onClick={() => setRetry(n => n + 1)}>Retry lesson</button></div> : <p>{!selected ? 'Choose a lesson to keep it here, ready when you are.' : !loading && !lesson ? 'This lesson is no longer in the collection. Choose another.' : !media ? 'Your team has not added a playable video yet.' : completed ? 'Marked complete on this browser. Ready for the next one?' : 'Your selected lesson, right where you need it.'}</p>}</div>
    <div className={styles.lessonActions}>{completed && nextLesson && selected && <button className={styles.textButton} onClick={() => update(p => ({ ...p, lesson: { inventoryId: selected.inventoryId, lessonId: nextLesson.id } }))}>Next lesson<ArrowUpRight size={16} /></button>}<button className={styles.textButton} onClick={() => setPicker(true)}>{selected ? 'Change lesson' : 'Choose lesson'}<ArrowUpRight size={16} /></button>{lesson && <button className={styles.iconButton} title={completed ? 'Mark lesson incomplete' : 'Mark lesson complete'} aria-label={completed ? 'Mark lesson incomplete' : 'Mark lesson complete'} aria-pressed={completed} onClick={() => update(p => ({ ...p, completedLessons: completed ? p.completedLessons.filter(k => k !== key) : [...p.completedLessons, key].slice(-300) }))}><CheckCheck size={20} /></button>}{playing && media && <a className={styles.textButton} href={lesson?.videoUrl} target="_blank" rel="noopener noreferrer">Open source</a>}</div>
    </div>{picker && <LessonPicker token={token} selected={selected} onPick={lesson => update(p => ({ ...p, lesson }))} onClose={() => setPicker(false)} />}
  </div>;
}
