"use client";
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent, ReactNode } from 'react';
import { MoreHorizontal, MoveDiagonal2, X, Check } from 'lucide-react';
import { moveWidget, placeWidgets, widgetCatalog } from '@/lib/overview-layout';
import type { WidgetId, WidgetLayout, WidgetSize } from '@/lib/overview-layout';
import styles from './PlatformHome.module.css';
interface Gesture { id: WidgetId; pointer: number; mode: 'move'|'resize'; x: number; y: number; startX: number; startY: number; width: number; height: number; original: WidgetLayout[]; target: WidgetId | null }
export function OverviewCanvas({ widgets, editing, onChange, onEdit, children }: { widgets: WidgetLayout[]; editing: boolean; onChange(widgets: WidgetLayout[]): void; onEdit(): void; children(id: WidgetId): ReactNode }) {
  const root=useRef<HTMLDivElement>(null), rects=useRef(new Map<string,DOMRect>()), gestureRef=useRef<Gesture|null>(null), changeRef=useRef(onChange), widgetsRef=useRef(widgets), columnsRef=useRef(12), press=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [canvasWidth,setCanvasWidth]=useState(1112), [gridGap,setGridGap]=useState(16), [columns,setColumns]=useState(12), [gesture,setGesture]=useState<Gesture|null>(null), [menu,setMenu]=useState<WidgetId|null>(null), [announcement,setAnnouncement]=useState('');
  changeRef.current=onChange;widgetsRef.current=widgets;columnsRef.current=columns;
  const measure=(node:HTMLElement)=>{const r=node.getBoundingClientRect();return new DOMRect(r.x+scrollX,r.y+scrollY,r.width,r.height);};
  const clearPress=()=>{if(press.current)clearTimeout(press.current);press.current=null;};
  useEffect(()=>{if(!root.current)return;const observer=new ResizeObserver(([entry])=>{setCanvasWidth(entry.contentRect.width);setGridGap(parseFloat(getComputedStyle(root.current!).columnGap)||16);setColumns(entry.contentRect.width<620?6:entry.contentRect.width<880?8:12);});observer.observe(root.current);return()=>{observer.disconnect();clearPress();};},[]);
  useLayoutEffect(()=>{root.current?.querySelectorAll<HTMLElement>('[data-widget]').forEach(node=>{node.getAnimations().filter(a=>a.id==='nbc-layout').forEach(a=>a.cancel());const id=node.dataset.widget!,next=measure(node),old=rects.current.get(id);const active=gestureRef.current;if(old&&!(active?.id===id)&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&(old.x!==next.x||old.y!==next.y||old.width!==next.width||old.height!==next.height)){const animation=node.animate([{transformOrigin:'top left',transform:`translate(${old.x-next.x}px,${old.y-next.y}px) scale(${old.width/next.width},${old.height/next.height})`},{transformOrigin:'top left',transform:'translate(0,0) scale(1)'}],{duration:300,easing:'cubic-bezier(.16,1,.3,1)'});animation.id='nbc-layout';}if(active?.id!==id)rects.current.set(id,next);});},[widgets,columns,canvasWidth,gridGap,gesture?.id]);
  useEffect(()=>{
    let frame=0;
    const autoScroll=()=>{const g=gestureRef.current;if(!g)return;if(g.y>innerHeight-60)scrollBy(0,12);else if(g.y<100)scrollBy(0,-12);frame=requestAnimationFrame(autoScroll);};
    const move=(event:PointerEvent)=>{clearPress();const g=gestureRef.current;if(!g||event.pointerId!==g.pointer)return;event.preventDefault();const target=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-widget]')?.dataset.widget as WidgetId|undefined;
      const next={...g,x:event.clientX,y:event.clientY,target:target&&target!==g.id?target:g.target};gestureRef.current=next;setGesture(next);
      if(g.mode==='resize') {const cols=columnsRef.current,gap=parseFloat(getComputedStyle(root.current!).columnGap)||16,unit=((root.current?.clientWidth||1000)+gap)/cols;const width=Math.max(3,Math.min(cols,g.width+Math.round((event.clientX-g.startX)/unit))),height=Math.max(2,Math.min(12,g.height+Math.round((event.clientY-g.startY)/(56+gap))));if(widgetsRef.current.find(w=>w.id===g.id)?.width!==width||widgetsRef.current.find(w=>w.id===g.id)?.height!==height)changeRef.current(widgetsRef.current.map(w=>w.id===g.id?{...w,width,height}:w));}
      if(!frame)frame=requestAnimationFrame(autoScroll);
    };
    const stop=(cancelled:boolean)=>{const g=gestureRef.current;if(!g)return;const node=root.current?.querySelector<HTMLElement>(`[data-widget="${g.id}"]`);if(node)rects.current.set(g.id,measure(node));gestureRef.current=null;setGesture(null);cancelAnimationFrame(frame);frame=0;if(cancelled)changeRef.current(g.original);else if(g.mode==='move'&&g.target)changeRef.current(moveWidget(widgetsRef.current,g.id,g.target));setAnnouncement(cancelled?'Change cancelled.':`${widgetCatalog[g.id].title} ${g.mode==='resize'?'resized':'moved'}.`);};
    const up=(e:PointerEvent)=>{clearPress();if(e.pointerId===gestureRef.current?.pointer)stop(false);};const cancel=()=>{clearPress();stop(true);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){cancel();setMenu(null);}};
    window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',up);window.addEventListener('pointercancel',cancel);window.addEventListener('keydown',key);return()=>{cancelAnimationFrame(frame);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancel);window.removeEventListener('keydown',key);};
  },[]);
  const start=(e:ReactPointerEvent<HTMLElement>,widget:WidgetLayout,mode:Gesture['mode'])=>{if(e.button!==0||!e.isPrimary)return;if(!editing){if(!e.target||!(e.target as HTMLElement).closest('button,a,input,select,textarea'))press.current=setTimeout(onEdit,550);return;}if(mode==='move'&&(e.target as HTMLElement).closest('button,a,input,select,textarea,details'))return;e.preventDefault();e.stopPropagation();clearPress();setMenu(null);const placement=placeWidgets(widgets,columns,canvasWidth,gridGap).find(p=>p.widget.id===widget.id)!;const g:Gesture={id:widget.id,pointer:e.pointerId,mode,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,width:placement.width,height:placement.height,original:widgets,target:null};gestureRef.current=g;setGesture(g);};
  const resize=(id:WidgetId,size:WidgetSize)=>{onChange(widgets.map(w=>w.id===id?{id,size}:w));setMenu(null);};
  const nudge=(id:WidgetId,delta:number)=>{const index=widgets.findIndex(w=>w.id===id),other=widgets[index+delta];if(other){onChange(moveWidget(widgets,id,other.id));setAnnouncement(`${widgetCatalog[id].title} moved.`);}};
  return <div ref={root} className={`${styles.canvas} ${editing?styles.editing:''}`} style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}} aria-label="Dashboard widgets"><span role="status" className={styles.srOnly}>{announcement}</span>{placeWidgets(widgets,columns,canvasWidth,gridGap).map(({widget,x,y,width,height})=><article key={widget.id} data-widget={widget.id} data-size={widget.size} data-width={width} data-height={height} data-editing={editing} className={`${styles.widget} ${styles[`widget_${widget.id}`]} ${gesture?.id===widget.id?styles.dragging:''} ${gesture?.target===widget.id?styles.dropTarget:''}`} aria-label={widgetCatalog[widget.id].title} tabIndex={editing?0:undefined} onPointerDown={e=>start(e,widget,'move')} onContextMenu={e=>{e.preventDefault();if(!editing)onEdit();setMenu(widget.id);}} onKeyDown={e=>{if(!editing||e.target!==e.currentTarget)return;if(['ArrowLeft','ArrowUp','ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();nudge(widget.id,['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);}}} style={{gridColumn:`${x+1}/span ${width}`,gridRow:`${y+1}/span ${height}`,transform:gesture?.id===widget.id&&gesture.mode==='move'?`translate(${gesture.x-gesture.startX}px,${gesture.y-gesture.startY}px) scale(1.015)`:undefined}}>
    {editing&&<><button className={styles.removeWidget} aria-label={`Remove ${widgetCatalog[widget.id].title}`} onClick={()=>onChange(widgets.filter(w=>w.id!==widget.id))}><X size={12}/></button><button className={styles.widgetMenuToggle} aria-label={`Options for ${widgetCatalog[widget.id].title}`} aria-expanded={menu===widget.id} onClick={()=>setMenu(menu===widget.id?null:widget.id)}><MoreHorizontal size={15}/></button>{menu===widget.id&&<div className={styles.widgetMenu} role="group" aria-label={`Edit ${widgetCatalog[widget.id].title}`}><span>Widget size</span>{(['compact','wide','full'] as WidgetSize[]).map((s,i)=><button key={s} onClick={()=>resize(widget.id,s)}>{['Small','Medium','Large'][i]}{widget.size===s&&<Check size={13}/>}</button>)}<button onClick={()=>nudge(widget.id,-1)}>Move earlier</button><button onClick={()=>nudge(widget.id,1)}>Move later</button></div>}</>}
    <div className={styles.widgetContent} inert={editing}>{children(widget.id)}</div>
    {editing&&<button className={styles.resizeHandle} aria-label={`Resize ${widgetCatalog[widget.id].title}`} onPointerDown={e=>start(e,widget,'resize')} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();const w=widgets.find(w=>w.id===widget.id)!;onChange(widgets.map(item=>item.id===w.id?{...item,width:Math.max(3,Math.min(12,width+(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0))),height:Math.max(2,Math.min(12,height+(e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0)))}:item));}}><MoveDiagonal2 size={14}/></button>}
  </article>)}</div>;
}
