"use client";
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, AudioLines, BookOpen, CalendarDays, Check, Coins, LayoutGrid, Map, Plus, RefreshCw, RotateCcw, Settings2, Sparkles, Users, X, Clock3 } from 'lucide-react';
import { useWorkspaceAccess } from '@/components/workspace/WorkspaceAccess';
import { useMemberNavigation } from '@/components/members/MemberNavigation';
import { activityDays, summaryMetrics } from '@/lib/summary-metrics';
import { defaultOverview, parseOverview, widgetCatalog, widgetIds, widgetDimensions, isNumberWidget } from '@/lib/overview-layout';
import type { OverviewPreferences, WidgetId, WidgetSize } from '@/lib/overview-layout';
import { ActivityChart, PipelineChart } from './SummaryCharts';
import { useOverviewData } from './useOverviewData';
import { OverviewCanvas } from './OverviewCanvas';
import { OverviewDialog } from './OverviewDialog';
import { LessonWidget, RoadmapWidget } from './OverviewLearning';
import styles from './PlatformHome.module.css';
const icons = { leads: Users, ready: ArrowUpRight, conversations: AudioLines, practice: Clock3, activity: AudioLines, pipeline: Users, roadmap: Map, lesson: BookOpen, calendar: CalendarDays, recent: Clock3, credits: Coins };
export function PlatformHome() {
  const { token, user } = useWorkspaceAccess();
  // Remount local editor state across identities; fetched data remains scoped to the current token.
  return user ? <Overview key={user.id} token={token} userId={user.id} name={user.name} /> : null;
}
function Overview({ token, userId, name }: { token: string; userId: string; name: string }) {
  const membership = useMemberNavigation(), { data, loading, refresh } = useOverviewData(token);
  const [preferences, setPreferences] = useState<OverviewPreferences>(defaultOverview), [draft, setDraft] = useState<OverviewPreferences | null>(null), [ready, setReady] = useState(false), [gallery, setGallery] = useState(false), [filter, setFilter] = useState('All widgets'), [query, setQuery] = useState(''), [storageError, setStorageError] = useState(''), [saved, setSaved] = useState(false), [days, setDays] = useState<7 | 30>(7), [gallerySize,setGallerySize] = useState<WidgetSize>('compact');
  const key = `nbc-overview:v1:${userId}`;
  useEffect(() => { try { setPreferences(parseOverview(localStorage.getItem(key))); } catch { setStorageError('Browser storage is unavailable. Changes will last until you leave this page.'); } setReady(true); }, [key]);
  const persist = (next: OverviewPreferences) => { setPreferences(next); try { localStorage.setItem(key, JSON.stringify(next)); setStorageError(''); setSaved(true); } catch { setStorageError('Your changes work here, but could not be saved on this browser.'); } };
  const update = (change: (p: OverviewPreferences) => OverviewPreferences) => { if (draft) setDraft(change(draft)); else persist(change(preferences)); };
  const current = draft ?? preferences, metrics = useMemo(() => summaryMetrics(data?.leads ?? [], data?.sessions ?? []), [data]);
  const rows = useMemo(() => data ? activityDays(data.sessions ?? [], days, data.at) : [], [data, days]), count = rows.reduce((n, d) => n + d.total, 0);
  const show = (n: number, available: boolean) => loading || !available ? '—' : n.toLocaleString('en-US');
  const events = data?.calendar?.events.filter(e => Date.parse(e.ends_at) > Date.now()).sort((a,b) => Date.parse(a.starts_at) - Date.parse(b.starts_at)) ?? [], event = events[0];
  function content(id: WidgetId) {
    const Icon = icons[id];
    const heading = <header className={styles.widgetHeading}><span><Icon size={16} />{widgetCatalog[id].title}</span>{id === 'activity' ? <div className={styles.periods} aria-label="Activity period">{([7,30] as const).map(n => <button key={n} aria-pressed={days === n} onClick={() => setDays(n)}>{n}D</button>)}</div> : <span className={styles.widgetDot} />}</header>;
    if (isNumberWidget(id)) {
      const stat = { leads: {value:metrics.leads,available:data?.leads,note:'Latest 1,000 saved leads'}, ready:{value:metrics.ready,available:data?.leads,note:'New & queued · unblocked'}, conversations:{value:metrics.conversations,available:data?.sessions,note:'Completed in latest 30 sessions'}, practice:{value:metrics.practiceMinutes,available:data?.sessions,note:'Recorded browser practice'} }[id as 'leads'|'ready'|'conversations'|'practice'];
      return <div className={styles.numberWidget}><span>{widgetCatalog[id].title}</span><strong>{show(stat.value,Boolean(stat.available))}</strong><small>{!loading&&!stat.available?'Unavailable · refresh to retry':stat.note}</small></div>;
    }
    if (id === 'activity') return <>{heading}<div className={styles.activityTotal}><strong>{show(count,Boolean(data?.sessions))}</strong><span>completed conversations<br />in the last {days} days</span><span className={styles.liveBadge}><i />YOUR RHYTHM</span></div><ActivityChart key={days} rows={rows} loading={loading} unavailable={!loading&&!data?.sessions} /><footer className={styles.widgetFooter}><span>Latest 30 sessions · UTC</span><Link href="/caller">Open Caller<ArrowUpRight size={14} /></Link></footer></>;
    if (id === 'pipeline') return <>{heading}<PipelineChart groups={metrics.pipeline} loading={loading} unavailable={!loading&&!data?.leads} /><footer className={styles.widgetFooter}><span>{!loading&&!data?.leads?'Unavailable · refresh to retry':metrics.leads?'Standard stages · view custom stages in Caller':'Your first opportunity starts the story.'}</span><Link href="/caller" aria-label="Open pipeline in Caller"><ArrowUpRight size={16} /></Link></footer></>;
    if (id === 'roadmap') return <>{heading}<RoadmapWidget preferences={current} update={update} membership={membership} /></>;
    if (id === 'lesson') return <>{heading}<LessonWidget token={token} preferences={current} update={update} /></>;
    if (id === 'calendar') return <>{heading}<div className={styles.calendarBody}><span className={styles.calendarIcon}><CalendarDays size={26} /></span>{event ? <><span className={styles.eyebrow}>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:data?.calendar?.timezone||'UTC'}).format(new Date(event.starts_at))}</span><h3>{event.title}</h3><p>{new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZoneName:'short',timeZone:data?.calendar?.timezone||'UTC'}).format(new Date(event.starts_at))}</p><a href={event.join_url || '/calendar'} target="_blank" rel="noopener noreferrer" className={styles.secondaryButton}>{event.join_url?'Join session':'View session'}<ArrowUpRight size={16} /></a></> : <><h3>{loading?'Checking your calendar…':!data?.calendar?'Calendar unavailable':'Room for the next breakthrough.'}</h3><p>{!loading&&!data?.calendar?'Refresh to try again.':'Your next scheduled coaching call will appear here.'}</p><Link href="/calendar" className={styles.textButton}>Open calendar<ArrowUpRight size={15} /></Link></>}</div></>;
    if (id === 'recent') return <>{heading}<div className={styles.recentBody}>{metrics.recent.length ? <ul className={styles.recentList}>{metrics.recent.map(s=><li key={s.id}><span className={styles.sessionIcon}><AudioLines size={18}/></span><div><strong>{s.channel==='web'?'Voice practice':'Phone conversation'}</strong><small>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(s.created_at))} · {s.duration_seconds===null?'Duration not recorded':`${Math.round(Math.max(0,s.duration_seconds)/60)} min`}</small></div><Check size={15}/></li>)}</ul> : <div className={styles.emptyContent}><AudioLines size={30}/><h3>{loading?'Loading conversations…':!data?.sessions?'Activity unavailable':'Every conversation counts.'}</h3><p>{!loading&&!data?.sessions?'Refresh to try again.':'Your completed conversations will be waiting here.'}</p></div>}<Link href="/caller" className={styles.textButton}>View conversations<ArrowUpRight size={15}/></Link></div></>;
    return <>{heading}<div className={styles.creditsBody}><span className={styles.creditOrb}><Coins size={31}/></span><strong>{membership?membership.available.toLocaleString('en-US'):'—'}</strong><span>credits available</span><Link href="/credits" className={styles.secondaryButton}>View balance<ArrowUpRight size={16}/></Link></div></>;
  }
  const matches = widgetIds.filter(id => (filter==='All widgets'||widgetCatalog[id].category===filter)&&`${widgetCatalog[id].title} ${widgetCatalog[id].description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className={styles.page}><header className={styles.heading}><div><p className={styles.eyebrow}><span/>YOUR SPACE. YOUR PACE.</p><h1>Overview<span>.</span></h1><p>Welcome back, {name.split(' ')[0] || 'there'}. Make today count.</p></div><div className={styles.headingActions}><button className={styles.iconButton} aria-label="Refresh dashboard" disabled={loading} onClick={refresh}><RefreshCw size={18} className={loading?styles.spinning:undefined}/></button>{draft ? <><button className={styles.secondaryButton} onClick={()=>{setDraft(null);setGallery(false);}}>Cancel</button><button className={styles.primaryButton} onClick={()=>{persist(draft);setDraft(null);setGallery(false);}}><Check size={17}/>Done</button></> : <button className={styles.primaryButton} disabled={!ready} onClick={()=>{setDraft(structuredClone(preferences));setSaved(false);}}><Settings2 size={17}/>Edit</button>}</div></header>
    {draft ? <div className={styles.editBar}><div><span className={styles.editPulse}/><strong>Edit your dashboard</strong><span>Drag widgets to move them, or pull a corner to resize.</span></div><div><button className={styles.textButton} onClick={()=>setDraft({...draft,widgets:defaultOverview().widgets})}><RotateCcw size={15}/>Restore</button><button className={styles.secondaryButton} onClick={()=>setGallery(true)}><Plus size={17}/>Add widget</button></div></div> : <div className={styles.canvasLabel}><span><LayoutGrid size={14}/>{current.widgets.length} widgets · Built around you</span><span>{saved?'Changes saved on this browser':'Your personal command center'}</span></div>}
    {storageError&&<p role="alert" className={styles.inlineError}>{storageError}</p>}
    {!loading&&data&&(!data.leads||!data.sessions||!data.calendar)&&<div className={styles.dataWarning} role="alert"><span>Some activity is unavailable. Your other widgets are ready.</span><button className={styles.textButton} onClick={refresh}>Try again</button></div>}
    {ready ? <OverviewCanvas widgets={current.widgets} editing={Boolean(draft)} onEdit={()=>{if(!draft)setDraft(structuredClone(preferences));}} onChange={widgets=>update(p=>({...p,widgets}))}>{content}</OverviewCanvas> : <div className={styles.emptyCanvas} role="status">Preparing your space…</div>}
    {ready&&!current.widgets.length&&<div className={styles.emptyCanvas}><span><LayoutGrid size={32}/></span><h2>A blank canvas. All yours.</h2><p>Add the things that help you move forward.</p><button className={styles.primaryButton} onClick={()=>{if(!draft)setDraft(structuredClone(preferences));setGallery(true);}}><Plus size={17}/>Explore widgets</button></div>}
    <footer className={styles.pageFooter}><span><Sparkles size={13}/>A little more you. A lot more possibility.</span><span>Layout & personal progress saved on this browser.</span></footer>
    {gallery&&<OverviewDialog title="Add widgets" subtitle="Choose a size, then add a widget. This is how it looks with your data." onClose={()=>setGallery(false)}><div className={styles.galleryToolbar}><div className={styles.galleryTop}><input aria-label="Search widgets" placeholder="Find a widget…" value={query} onChange={e=>setQuery(e.target.value)}/><div className={styles.gallerySizes} aria-label="Preview widget size">{(['compact','wide','full'] as WidgetSize[]).map((size,index)=><button key={size} aria-pressed={gallerySize===size} onClick={()=>setGallerySize(size)}>{['Small','Medium','Large'][index]}</button>)}</div></div><div className={styles.galleryTabs}>{['All widgets','Numbers','Performance','Learning','Your space'].map(value=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div></div><div className={styles.galleryGrid}>{matches.map(id=>{const added=current.widgets.some(w=>w.id===id), dimensions=widgetDimensions({id,size:gallerySize});return <article key={id}><div className={`${styles.actualPreview} ${isNumberWidget(id)?styles.numberPreview:''}`} aria-hidden="true" inert data-preview-size={gallerySize}><div className={styles.previewContent}>{content(id)}</div></div><div className={styles.previewCaption}><div><h3>{widgetCatalog[id].title}</h3><small>{dimensions.width} × {dimensions.height}</small></div><button className={added?styles.addedButton:styles.addWidgetButton} disabled={added} aria-label={added?`${widgetCatalog[id].title} already added`:`Add ${widgetCatalog[id].title}`} onClick={()=>update(p=>({...p,widgets:[...p.widgets,{id,size:gallerySize}]}))}>{added?<Check size={17}/>:<Plus size={17}/>}</button></div></article>;})}{!matches.length&&<p className={styles.bodyNote}>No widgets match your search.</p>}</div></OverviewDialog>}

  </div>;
}
