import 'server-only';
import { database,IntegrationError } from './integration.service';
import { MemberError,memberId,memberText,memberTimezone } from '@/lib/member-validation';
import type { Member } from '@/lib/member-types';
import type { ProfileData,UsagePage,MeteredUsage,ProviderUsageSnapshot } from '@/lib/usage';
import { parseProviderUsage, voiceUsage } from '@/lib/usage';
import { elevenQuery, elevenRead } from './elevenlabs.service';
export function ensureAdmin(actor:Member):void {if(actor.role!=='admin')throw new MemberError(403,'Administrator access is required.');}
function checked<T>(r:{data:T;error:unknown}):T{if(r.error)throw new MemberError(503,'Account data could not be loaded or saved. Please try again.');return r.data;}
async function readProviderUsage():Promise<ProviderUsageSnapshot>{
 const measuredAt=Date.now(),day=86400_000,date=new Date(measuredAt),today=Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate());
 try{const[analytics,subscription]=await Promise.all([elevenQuery('/v1/workspace/analytics/query/usage-by-product-over-time',{start_time:today-29*day,end_time:measuredAt,interval_seconds:86400,group_by:['product_type'],time_zone:'UTC'}),elevenRead('/v1/user/subscription')]);return parseProviderUsage(analytics,subscription,measuredAt);}catch{return{status:'unavailable',measuredAt:new Date(measuredAt).toISOString()};}
}
export async function readUsage(actor:Member,request:Request):Promise<UsagePage>{ensureAdmin(actor);const params=new URL(request.url).searchParams,offset=Number(params.get('offset')||0),search=params.get('search')||'';if(!Number.isSafeInteger(offset)||offset<0||offset>1e6||search.length>120)throw new MemberError(400,'Invalid search or page.');const db=database();const [page,rates,provider]=await Promise.all([db.rpc('nbc_admin_usage',{p_actor:actor.id,p_offset:offset,p_search:search}),db.from('nbc_credit_rates').select('id,label,credit_value_microusd,markup_bps,status').order('created_at',{ascending:false}).limit(20),readProviderUsage()]);return {...checked(page) as Omit<UsagePage,'rates'|'paymentsReady'|'meteringMode'|'provider'>,rates:checked(rates)??[],paymentsReady:Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET&&process.env.NBC_BILLING_ORIGIN),meteringMode:'observe',provider};}
export async function readProfile(actor:Member):Promise<ProfileData>{const db=database();const [member,onboarding,auth]=await Promise.all([db.from('nbc_members').select('display_name,avatar_tone').eq('id',actor.id).single(),db.from('nbc_onboarding').select('*').eq('member_id',actor.id).maybeSingle(),db.auth.admin.getUserById(actor.id)]);const m=checked(member),o=checked(onboarding);if(!m||auth.error)throw new MemberError(503,'Your profile could not be loaded.');return{name:m.display_name,avatarTone:m.avatar_tone,email:auth.data.user.email||'',role:actor.role,business:o?.business??'',timezone:o?.timezone??'America/New_York',goal:o?.goal??'',questions:o?.questions??'',completedAt:o?.completed_at??null};}
export async function saveProfile(actor:Member,raw:unknown):Promise<ProfileData>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new MemberError(400,'Use a valid profile.');const p=raw as Record<string,unknown>;if(!['blue','gold','violet','slate'].includes(String(p.avatarTone)))throw new MemberError(400,'Choose an avatar color.');const existing=await readProfile(actor);checked(await database().rpc('nbc_save_profile',{p_actor:actor.id,p_name:memberText(p.name,'name',120),p_avatar:p.avatarTone,p_business:memberText(p.business,'business',200,Boolean(existing.completedAt)),p_timezone:memberTimezone(p.timezone),p_goal:memberText(p.goal,'goal',2000,Boolean(existing.completedAt)),p_questions:memberText(p.questions,'questions',3000,false)}));return readProfile(actor);}
export async function recordUsage(memberId:string,source:string,eventKey:string,feature:string,usage:MeteredUsage,at:string):Promise<void>{checked(await database().rpc('nbc_usage_record',{p_member:memberId,p_source:source,p_key:eventKey,p_feature:feature,p_input:usage.inputTokens,p_output:usage.outputTokens,p_cached:usage.cachedTokens,p_seconds:usage.seconds,p_cost:usage.costMicrousd,p_scope:usage.costScope,p_at:at}));}
export async function recordCallerUsage(member:string,id:string,payload:unknown,at:string):Promise<void>{await recordUsage(memberId(member),'caller',memberId(id),'Caller',voiceUsage(payload),at);}
export function accountError(error:unknown):Response{return Response.json({error:error instanceof MemberError||error instanceof IntegrationError?error.message:'Your request could not be completed. Please try again.'},{status:error instanceof MemberError||error instanceof IntegrationError?error.status:503,headers:{'Cache-Control':'no-store'}});}
