import 'server-only';
import {database,IntegrationError} from './integration.service';
import type {CallerPipeline,ActivityPage} from '@/lib/caller-workbench';
import type {SessionPageOptions} from '@/lib/caller-pagination';
import {encodeSessionCursor,sessionCursorFilter} from '@/lib/caller-pagination';
const activityFields='id,lead_id,author_id,author_name,kind,outcome,body,created_at';
export function workbenchError(message:string):never{const status=message.includes('lead_not_found')?404:/pipeline_conflict|lead_conflict|request_conflict/.test(message)?409:/invalid_|missing_destination|check constraint/.test(message)?400:503;throw new IntegrationError(status,status===404?'This lead is not in your workspace.':status===409?'This record changed or the request was already used. Refresh and review before saving.':status===400?'Check your selection. Removed stages need a destination in your own pipeline.':'Your CRM could not save this change. You can retry the same request.');}
export async function getPipeline(owner:string,demo:boolean):Promise<CallerPipeline>{const db=database();const init=await db.rpc('caller_ensure_pipeline',{p_owner:owner,p_demo:demo});if(init.error)workbenchError(init.error.message);const [config,buckets]=await Promise.all([db.from('caller_pipelines').select('version,default_bucket_id').eq('operator_id',owner).eq('is_demo',demo).single(),db.from('caller_buckets').select('id,name,color,outcome,position,default_key').eq('operator_id',owner).eq('is_demo',demo).order('position')]);if(config.error||buckets.error)workbenchError('unavailable');return{version:config.data.version,defaultId:config.data.default_bucket_id,buckets:buckets.data};}
export async function assertWorkbenchLead(owner:string,demo:boolean,id:string):Promise<void>{const result=await database().from('caller_leads').select('id').eq('id',id).eq('operator_id',owner).eq('is_demo',demo).maybeSingle();if(result.error)workbenchError('unavailable');if(!result.data)workbenchError('lead_not_found');}
export async function listActivity(owner:string,demo:boolean,id:string,options:SessionPageOptions):Promise<ActivityPage>{await assertWorkbenchLead(owner,demo,id);let query=database().from('caller_activity').select(activityFields).eq('operator_id',owner).eq('is_demo',demo).eq('lead_id',id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(options.limit+1);if(options.cursor)query=query.or(sessionCursorFilter(options.cursor));const result=await query;if(result.error)workbenchError('unavailable');const activities=result.data.slice(0,options.limit);return{activities,nextCursor:result.data.length>options.limit?encodeSessionCursor(activities[activities.length-1]):null};}
export async function workbenchRpc(name:string,args:Record<string,unknown>):Promise<void>{const result=await database().rpc(name,args);if(result.error)workbenchError(result.error.message);}
