import 'server-only';
import {createCipheriv,createDecipheriv,randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {database,IntegrationError} from './integration.service';
import type {BookingConfig,BookingRequest,BookingReceipt,BookingStep,StepReceipt} from '@/lib/caller-booking';
import type {RetellConfig} from '@/lib/retell-config';
export interface BookingConnection {owner_id:string;config:BookingConfig;token_ciphertext:string;retell_config:RetellConfig|null;verified_at:string}
export interface BookingCall {owner_id:string;operation_key:string;config:BookingConfig;token_ciphertext:string;phone:string}
export interface BookingRow {id:string;operation_key:string;owner_id:string;request:BookingRequest;state:BookingReceipt['state'];contact_id:string|null;appointment_id:string|null;receipt:Omit<BookingReceipt,'id'|'state'|'steps'>;created_at:string}
function key():Buffer {const k=Buffer.from(process.env.CALLER_BOOKING_ENCRYPTION_KEY??'','base64');if(k.length!==32)throw new IntegrationError(503,'Booking secret storage is not configured.');return k;}
export function encryptBookingToken(owner:string,token:string):string {const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);cipher.setAAD(Buffer.from(owner));const data=Buffer.concat([cipher.update(token,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),data].map(b=>b.toString('base64url')).join('.');}
export function decryptBookingToken(owner:string,value:string):string {try{const [iv,tag,data]=value.split('.').map(s=>Buffer.from(s,'base64url')),cipher=createDecipheriv('aes-256-gcm',key(),iv);cipher.setAAD(Buffer.from(owner));cipher.setAuthTag(tag);return Buffer.concat([cipher.update(data),cipher.final()]).toString('utf8');}catch{throw new IntegrationError(503,'The booking credential could not be opened. Reconnect GHL.');}}
export function inviteSignature(id:string,expires:string):string {return createHmac('sha256',key()).update(`invite:${id}:${expires}`).digest('hex');}
export function validInviteSignature(id:string,expires:string,signature:string):boolean {if(!/^\d+$/.test(expires)||Number(expires)<Date.now()||!/^[0-9a-f]{64}$/.test(signature))return false;return timingSafeEqual(Buffer.from(signature,'hex'),Buffer.from(inviteSignature(id,expires),'hex'));}
export async function getBookingConnection(owner:string):Promise<BookingConnection|null>{const r=await database().from('caller_booking_connections').select('*').eq('owner_id',owner).maybeSingle();if(r.error)throw new IntegrationError(503,'Booking settings could not load.');return r.data;}
export async function getBookingCall(operation:string):Promise<BookingCall|null>{const r=await database().from('caller_booking_calls').select('*').eq('operation_key',operation).maybeSingle();if(r.error)throw new IntegrationError(503,'Booking call could not load.');return r.data;}
export async function getBooking(operation:string):Promise<BookingRow|null>{const r=await database().from('caller_bookings').select('*').eq('operation_key',operation).maybeSingle();if(r.error)throw new IntegrationError(503,'Booking result could not load.');return r.data;}
export async function updateBooking(id:string,value:Partial<BookingRow>):Promise<void>{const r=await database().from('caller_bookings').update({...value,updated_at:new Date().toISOString()}).eq('id',id).select('id').single();if(r.error)throw new IntegrationError(503,'Booking result could not be persisted. Do not create a replacement.');}
export async function receipt(row:BookingRow):Promise<BookingReceipt>{const r=await database().from('caller_booking_steps').select('*').eq('booking_id',row.id);if(r.error)throw new IntegrationError(503,'Confirmation status could not load.');return {id:row.id,state:row.state,...row.receipt,steps:Object.fromEntries((r.data??[]).map(s=>[s.kind,{state:s.state,providerId:s.provider_id??undefined,reason:s.reason??undefined,costMicrousd:s.cost_microusd??null}]))};}
export async function saveStep(id:string,kind:BookingStep,value:StepReceipt){const r=await database().from('caller_booking_steps').update({state:value.state,provider_id:value.providerId??null,reason:value.reason??null,cost_microusd:value.costMicrousd,updated_at:new Date().toISOString()}).eq('booking_id',id).eq('kind',kind).select('kind').single();if(r.error)throw new IntegrationError(503,'Confirmation receipt could not be saved. Reconciliation is required.');}
export async function claimStep(id:string,kind:BookingStep):Promise<boolean>{
 const db=database(),r=await db.from('caller_booking_steps').insert({booking_id:id,kind,state:'pending'});if(r.error&&r.error.code!=='23505')throw new IntegrationError(503,'Confirmation could not be queued.');
 const claim=await db.from('caller_booking_steps').update({state:'running',updated_at:new Date().toISOString()}).eq('booking_id',id).eq('kind',kind).eq('state','pending').select('kind');if(claim.error)throw new IntegrationError(503,'Confirmation could not be claimed.');return Boolean(claim.data?.length);
}
