import 'server-only';
import {database} from './integration.service';
import {MemberError,memberId} from '@/lib/member-validation';
import type {Member} from '@/lib/member-types';
import {validStripeSignature} from '@/lib/payment-signature';
function configuration(){const key=process.env.STRIPE_SECRET_KEY,webhook=process.env.STRIPE_WEBHOOK_SECRET,origin=process.env.NBC_BILLING_ORIGIN;if(!key||!webhook||!origin)throw new MemberError(503,'Credit top-ups are being prepared.');const url=new URL(origin);if(url.protocol!=='https:'||url.username||url.password)throw new MemberError(503,'Credit top-ups are being prepared.');return{key,webhook,origin:url.origin,live:key.startsWith('sk_live_')};}
async function stripe(path:string,body?:URLSearchParams,id?:string):Promise<Record<string,unknown>>{const c=configuration();const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${c.key}`,...(body?{'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`nbc-topup-${id}`}:{})},body,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new MemberError(503,'The payment service could not confirm this request. Please retry the same order.');return r.json();}
export async function creditPackages(){const {data,error}=await database().from('nbc_credit_packages').select('id,credits,amount_cents,currency').eq('active',true).order('credits');if(error)throw new MemberError(503,'Credit packages are unavailable.');let ready=false;try{configuration();ready=true;}catch{/* Setup is intentionally inactive. */}return{packages:ready?data:[],ready:ready&&Boolean(data?.length)};}
export async function startCheckout(actor:Member,raw:unknown){const c=configuration();if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new MemberError(400,'Choose a credit package.');const p=raw as Record<string,unknown>,id=memberId(p.requestId);if(typeof p.packageId!=='string'||p.packageId.length>60)throw new MemberError(400,'Choose a credit package.');const db=database();let {data:order,error}=await db.from('nbc_credit_orders').select('*').eq('id',id).maybeSingle();if(error)throw new MemberError(503,'Your order could not be loaded.');if(order&&(order.member_id!==actor.id||order.package_id!==p.packageId))throw new MemberError(409,'This order does not match the requested package.');if(!order){const pack=await db.from('nbc_credit_packages').select('*').eq('id',p.packageId).eq('active',true).maybeSingle();if(pack.error||!pack.data)throw new MemberError(409,'This credit package is not available.');const inserted=await db.from('nbc_credit_orders').insert({id,member_id:actor.id,package_id:p.packageId,credits:pack.data.credits,amount_cents:pack.data.amount_cents,currency:pack.data.currency}).select('*').single();if(inserted.error)throw new MemberError(409,'The order is being created. Retry the same request.');order=inserted.data;}
 if(!order.checkout_session&&Date.now()-Date.parse(order.created_at)>23*3600000)throw new MemberError(409,'This order expired. Start a new credit top-up.');
 if(order.status==='paid')return{paid:true,url:null};
 const body=new URLSearchParams({mode:'payment',client_reference_id:actor.id,'metadata[nbc_order_id]':id,success_url:c.origin+'/credits?checkout=returned',cancel_url:c.origin+'/credits?checkout=cancelled','line_items[0][price_data][currency]':order.currency,'line_items[0][price_data][unit_amount]':String(order.amount_cents),'line_items[0][price_data][product_data][name]':`${order.credits.toLocaleString('en-US')} NBC Credits`,'line_items[0][quantity]':'1'});
 const session=order.checkout_session?await stripe(`checkout/sessions/${encodeURIComponent(order.checkout_session)}`):await stripe('checkout/sessions',body,id);if(typeof session.id!=='string'||typeof session.url!=='string'||new URL(session.url).hostname!=='checkout.stripe.com')throw new MemberError(409,'This checkout is no longer available. Start a new order.');const saved=await db.from('nbc_credit_orders').update({checkout_session:session.id}).eq('id',id).eq('member_id',actor.id);if(saved.error)throw new MemberError(503,'Checkout could not be saved. Retry the same order.');return{url:session.url,paid:false};}
export async function processPayment(request:Request){const c=configuration();const reader=request.body?.getReader();if(!reader)throw new MemberError(400,'Missing payment event.');const chunks:Uint8Array[]=[];let bytes=0;while(true){const r=await reader.read();if(r.done)break;bytes+=r.value.length;if(bytes>262144){await reader.cancel();throw new MemberError(413,'Payment event too large.');}chunks.push(r.value);}const body=Buffer.concat(chunks).toString('utf8');if(!validStripeSignature(body,request.headers.get('stripe-signature'),c.webhook))throw new MemberError(400,'Invalid payment signature.');let event;try{event=JSON.parse(body);}catch{throw new MemberError(400,'Invalid payment event.');}
 if(!['checkout.session.completed','checkout.session.async_payment_succeeded'].includes(event.type))return{received:true};if(event.livemode!==c.live)throw new MemberError(400,'Payment environment mismatch.');const sessionId=event.data?.object?.id;if(typeof sessionId!=='string'||!/^cs_[a-zA-Z0-9_]+$/.test(sessionId)||typeof event.id!=='string')throw new MemberError(400,'Invalid checkout event.');const session=await stripe(`checkout/sessions/${sessionId}`);if(session.payment_status!=='paid')return{received:true};if(session.mode!=='payment'||session.livemode!==c.live)throw new MemberError(400,'Invalid payment mode.');const metadata=session.metadata as Record<string,unknown>|undefined;if(!metadata?.nbc_order_id)return{received:true};const orderId=memberId(metadata.nbc_order_id);const db=database();const order=await db.from('nbc_credit_orders').select('member_id').eq('id',orderId).maybeSingle();if(order.error||!order.data||order.data.member_id!==session.client_reference_id)throw new MemberError(409,'Payment owner could not be verified.');if(!Number.isSafeInteger(session.amount_total)||typeof session.currency!=='string'||typeof session.payment_intent!=='string')throw new MemberError(400,'Payment details are incomplete.');const posted=await db.rpc('nbc_paid_topup',{p_order:orderId,p_session:sessionId,p_payment:session.payment_intent,p_amount:session.amount_total,p_currency:session.currency,p_event:event.id});if(posted.error)throw new MemberError(503,'Payment could not be posted. Delivery will be retried.');return{received:true};}
