import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
const artifacts = process.env.K01_ARTIFACT_DIR;
async function screenshot(page: Page, name: string): Promise<void> { if (artifacts) { await page.evaluate(() => { (document.activeElement as HTMLElement | null)?.blur(); window.scrollTo(0, 0); }); await page.screenshot({ path: `${artifacts}/${name}.png`, fullPage: true, animations: 'disabled' }); } }
async function downloadContents(page: Page, name: string): Promise<string> {
  const event = page.waitForEvent('download'); await page.getByRole('button', { name, exact: true }).click();
  const stream = await (await event).createReadStream(); if (!stream) throw new Error('Missing download');
  const chunks: Buffer[] = []; for await (const chunk of stream) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks).toString('utf8');
}
test('premium library and reversible student demo with real sample downloads, captions and notes per lesson', async ({ page }) => {
  const remote: string[] = []; const errors: string[] = [];
  page.on('request', request => { if (new URL(request.url()).hostname !== '127.0.0.1') remote.push(request.url()); });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/academy'); await screenshot(page, 'library-empty-desktop');
  await page.getByRole('button', { name: 'Preview student experience' }).click();
  await expect(page.getByText('Student experience · DEMO', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /Explore course/ })).toHaveCount(4);
  await screenshot(page, 'student-library-desktop');
  await page.getByLabel('Search courses').fill('discovery');
  await expect(page.getByRole('button', { name: /Explore course/ })).toHaveCount(1);
  await page.getByRole('button', { name: /Explore course/ }).click();
  await expect(page.getByRole('heading', { name: 'Open the conversation', level: 1 })).toBeVisible();
  await page.getByRole('button', { name: 'Preview subtitles', exact: true }).click();
  await expect(page.getByText('Sample caption: Begin with one question you want to answer.')).toBeVisible();
  await screenshot(page, 'student-lesson-desktop');
  await page.getByRole('tab', { name: 'Transcript', exact: true }).click();
  expect(await downloadContents(page, 'Download sample transcript')).toContain('not a transcript of a real video');
  expect(await downloadContents(page, 'Download sample captions (.vtt)')).toMatch(/^WEBVTT/);
  await page.getByRole('tab', { name: 'Resources', exact: true }).click();
  expect(await downloadContents(page, 'Download sample practice sheet')).toContain('DEMO PRACTICE SHEET');
  await page.getByRole('tab', { name: 'My notes', exact: true }).click();
  await page.getByLabel('Notes for Open the conversation').fill('My demo thought for lesson one.');
  await page.getByRole('button', { name: 'Next lesson', exact: true }).click();
  await expect(page.getByLabel('Notes for Ask a better question')).toHaveValue('');
  await page.getByLabel('Notes for Ask a better question').fill('A different demo thought.');
  await page.getByRole('button', { name: 'Previous lesson', exact: true }).click();
  await expect(page.getByLabel('Notes for Open the conversation')).toHaveValue('My demo thought for lesson one.');
  expect(await downloadContents(page, 'Download my notes')).toContain('My demo thought for lesson one.');
  await screenshot(page, 'student-notes-desktop');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await screenshot(page, 'student-notes-mobile');
  await page.getByRole('tab', { name: 'Overview', exact: true }).click();
  await screenshot(page, 'student-lesson-mobile');
  page.once('dialog', dialog => dialog.dismiss()); await page.getByRole('button', { name: 'Exit preview', exact: true }).click();
  await expect(page.getByText('Student experience · DEMO', { exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', { name: 'Exit preview', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'The Academy.', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Import your program', exact: true })).toBeVisible();
  expect(remote).toEqual([]); expect(errors).toEqual([]);
});
test('bulk spreadsheet preview, visual editing and demo never replace the actual inventory', async ({ page }) => {
  await page.goto('/academy'); await page.getByRole('button', { name: 'Import your program', exact: true }).click();
  await page.getByLabel('Paste curriculum table').fill('Course\tModule\tLesson\tVideo URL\nK01 DEMO import program\tModule one\tLesson one\t\nK01 DEMO import program\tModule one\tLesson two\thttps://vimeo.com/123456\n');
  await page.getByRole('button', { name: 'Review import', exact: true }).click();
  await expect(page.getByText('Ready to review: 1 courses · 1 modules · 2 lessons', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Use this curriculum', exact: true }).click();
  await expect(page.locator('summary').getByText('K01 DEMO import program', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit lesson Lesson one', exact: true }).click();
  await page.getByLabel('Lesson title', { exact: true }).fill('Updated lesson');
  await page.getByLabel('Video URL (optional)', { exact: true }).fill('https://vimeo.com/987654');
  await page.getByRole('button', { name: 'Update lesson', exact: true }).click();
  const before = JSON.parse(await downloadContents(page, 'Export inventory'));
  expect(before.courses[0].modules[0].lessons[0].videoUrl).toBe('https://vimeo.com/987654');
  await page.getByRole('button', { name: 'Preview student experience' }).click();
  await page.getByRole('button', { name: 'Exit preview', exact: true }).click();
  expect(JSON.parse(await downloadContents(page, 'Export inventory'))).toEqual(before);
  await page.getByLabel('Paste curriculum table').fill('Course,Module,Lesson,Video URL\nC,M,L,javascript:alert(1)');
  await page.getByRole('button', { name: 'Review import', exact: true }).click();
  await expect(page.locator('main').getByRole('alert')).toContainText('Row 2');
  expect(JSON.parse(await downloadContents(page, 'Export inventory'))).toEqual(before);
  await page.getByRole('button', { name: 'Add module', exact: true }).click();
  await page.getByLabel('Module title').fill('Module two');
  await page.getByRole('form', { name: 'Edit curriculum item' }).getByRole('button', { name: 'Add module', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Module two/ })).toBeVisible();
  await page.getByLabel('Paste curriculum table').fill('');
  await screenshot(page, 'import-studio-desktop');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await screenshot(page, 'import-studio-mobile');
  await page.getByRole('button', { name: 'Preview this curriculum', exact: true }).click();
  await page.getByRole('button', { name: /Preview course/ }).click();
  await page.getByRole('tab', { name: 'Transcript', exact: true }).click();
  await expect(page.getByText('No transcript is available for this lesson yet.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Download sample transcript' })).toHaveCount(0);
});
test('create curriculum without JSON, then safely review a CSV replacement', async ({ page }) => {
  await page.goto('/academy'); await page.getByRole('button', { name: 'Import your program', exact: true }).click();
  await page.getByRole('button', { name: 'Add course', exact: true }).click();
  const form = page.getByRole('form', { name: 'Edit curriculum item' });
  await page.getByLabel('Course title').fill('K01 DEMO manual course'); await form.getByRole('button', { name: 'Add course', exact: true }).click();
  await page.getByRole('button', { name: 'Add module', exact: true }).click();
  await page.getByLabel('Module title').fill('K01 DEMO manual module'); await form.getByRole('button', { name: 'Add module', exact: true }).click();
  await page.getByRole('button', { name: 'Add lesson', exact: true }).click();
  await page.getByLabel('Lesson title').fill('K01 DEMO manual lesson'); await form.getByRole('button', { name: 'Add lesson', exact: true }).click();
  const before = JSON.parse(await downloadContents(page, 'Export inventory'));
  expect(before.courses[0].modules[0].lessons[0].title).toBe('K01 DEMO manual lesson');
  await page.getByLabel('Course inventory table').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('Course,Module,Lesson\nMissing columns')});
  await expect(page.locator('main').getByRole('alert')).toContainText('Row 2');
  expect(JSON.parse(await downloadContents(page, 'Export inventory'))).toEqual(before);
  await page.getByLabel('Course inventory table').setInputFiles({name:'K01-DEMO-CSV.csv',mimeType:'text/csv',buffer:Buffer.from('Course,Module,Lesson\nK01 DEMO CSV course,Module,Lesson')});
  page.once('dialog', dialog => dialog.dismiss()); await page.getByRole('button', {name:'Use this curriculum',exact:true}).click();
  expect(JSON.parse(await downloadContents(page, 'Export inventory'))).toEqual(before);
  page.once('dialog', dialog => dialog.accept()); await page.getByRole('button', {name:'Use this curriculum',exact:true}).click();
  const after = JSON.parse(await downloadContents(page, 'Export inventory'));
  expect(after.courses[0].title).toBe('K01 DEMO CSV course'); expect(after.version).toBe(1);
});
