import './caller-test-loader.mjs';import assert from 'node:assert/strict';import test from 'node:test';
const pipeline=await import('../src/app/api/caller/pipeline/route.ts'),activity=await import('../src/app/api/caller/leads/[id]/activity/route.ts'),details=await import('../src/app/api/caller/leads/[id]/details/route.ts');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',lead='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',version='55555555-5555-4555-8555-555555555555';const ctx={params:Promise.resolve({id:lead})};
const req=(path:string,method='GET',body?:unknown,token:string|null='member')=>new Request('https://fixture.test'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
const config={requestId:id,version,defaultId:id,buckets:[{id,name:'Follow up',color:'blue',outcome:'active'}],reassign:{}};
test('C04 authorization and validation use real routes, auth, services and Supabase SDK',async t=>{const original=fetch,env={...process.env};Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:'https://crm4-fixture.supabase.co',SUPABASE_SECRET_KEY:'fixture-secret'});let dbReads=0,rpcs=0,exists=true,conflict=false;const at='2026-09-15T12:00:00.123456+00:00';
 globalThis.fetch=async(input,init)=>{const url=new URL(typeof input==='string'||input instanceof URL?input:input.url),headers=new Headers(init?.headers),body=typeof init?.body==='string'?JSON.parse(init.body):null;
  if(url.pathname==='/auth/v1/user'){if(headers.get('authorization')?.includes('bad'))return Response.json({message:'Invalid'},{status:401});return Response.json({id:a,email:'fixture@example.test',email_confirmed_at:at});}
  if(url.pathname==='/rest/v1/nbc_members')return Response.json([{id:a,display_name:'Verified fixture author',role:'student',status:'active'}]);
  dbReads++;if(url.pathname.startsWith('/rest/v1/rpc/')){rpcs++;assert.equal(body.p_owner,a);assert.equal(body.p_demo,false);if(url.pathname.endsWith('caller_add_activity')){assert.equal(body.p_author,'Verified fixture author');assert.equal(body.p_lead,lead);assert(!('created_at' in body));}if(conflict)return Response.json({message:'pipeline_conflict'},{status:400});return Response.json(null);}
  assert.equal(url.searchParams.get('operator_id'),'eq.'+a);assert.equal(url.searchParams.get('is_demo'),'eq.false');
  if(url.pathname.endsWith('caller_pipelines'))return Response.json({version,default_bucket_id:id});
  if(url.pathname.endsWith('caller_buckets'))return Response.json([{...config.buckets[0],position:0,default_key:null}]);
  if(url.pathname.endsWith('caller_leads')){assert.equal(url.searchParams.get('id'),'eq.'+lead);return Response.json(exists?{id:lead}:null);}
  assert(url.pathname.endsWith('caller_activity'));assert.equal(url.searchParams.get('lead_id'),'eq.'+lead);assert(!url.searchParams.get('select')?.includes('request_payload'));assert.equal(url.searchParams.get('order'),'created_at.desc,id.desc');return Response.json([{id,lead_id:lead,author_id:a,author_name:'Verified fixture author',kind:'note',outcome:null,body:'Fixture note',created_at:at}]);
 };
 try{
 await t.test('anonymous/invalid tokens reject before RPC or private reads',async()=>{for(const token of [null,'bad']){const before=dbReads;assert.equal((await pipeline.GET(req('/api/caller/pipeline','GET',undefined,token))).status,401);assert.equal((await activity.POST(req('/activity','POST',{},token),ctx)).status,401);assert.equal((await details.PATCH(req('/details','PATCH',{},token),ctx)).status,401);assert.equal(dbReads,before);}});
 await t.test('student can customize own live pipeline but cannot access demo',async()=>{assert.equal((await pipeline.GET(req('/api/caller/pipeline'))).status,200);const before=rpcs;assert.equal((await pipeline.GET(req('/api/caller/pipeline?demo=true'))).status,403);assert.equal((await pipeline.PUT(req('/api/caller/pipeline','PUT',{...config,demo:true}))).status,403);assert.equal((await activity.GET(req('/activity?demo=true'),ctx)).status,403);assert.equal(rpcs,before);assert.equal((await pipeline.PUT(req('/pipeline','PUT',config))).status,200);});
 await t.test('bucket payload shape, duplicates, missing default and stale revision reject',async()=>{for(const body of [null,{}, {...config,buckets:[]},{...config,buckets:[...config.buckets,...config.buckets]},{...config,defaultId:b}])assert.equal((await pipeline.PUT(req('/pipeline','PUT',body))).status,400);conflict=true;assert.equal((await pipeline.PUT(req('/pipeline','PUT',config))).status,409);conflict=false;});
 await t.test('author/time injected from verified identity; note and call validation',async()=>{const body={requestId:id,kind:'note',body:'A note',author_id:b,author_name:'Spoofed',created_at:'1990-01-01'};assert.equal((await activity.POST(req('/activity','POST',body),ctx)).status,200);assert.equal((await activity.POST(req('/activity','POST',{...body,kind:'manual_call',outcome:'no_answer'}),ctx)).status,200);for(const invalid of [{...body,body:' '},{...body,body:'x'.repeat(4001)},{...body,kind:'manual_call',outcome:'made_up'},{...body,demo:'yes'}])assert.equal((await activity.POST(req('/activity','POST',invalid),ctx)).status,400);});
 await t.test('activity checks owner before reading, filters lead/mode and validates stable cursor',async()=>{let response=await activity.GET(req('/activity'),ctx);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');assert.equal((await response.json()).activities[0].author_name,'Verified fixture author');assert.equal((await activity.GET(req('/activity?cursor=bad'),ctx)).status,400);assert.equal((await activity.GET(req('/activity?limit=31'),ctx)).status,400);exists=false;assert.equal((await activity.GET(req('/activity'),ctx)).status,404);exists=true;});
 await t.test('lead moves validate UUID/version/flag and cannot target demo as student',async()=>{const body={requestId:id,bucketId:id,doNotCall:true,updatedAt:at};assert.equal((await details.PATCH(req('/details','PATCH',body),ctx)).status,200);for(const invalid of [{...body,bucketId:'bad'},{...body,updatedAt:'bad'},{...body,doNotCall:'false'}])assert.equal((await details.PATCH(req('/details','PATCH',invalid),ctx)).status,400);assert.equal((await details.PATCH(req('/details','PATCH',{...body,demo:true}),ctx)).status,403);});
 }finally{globalThis.fetch=original;for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);}});
