import './caller-test-loader.mjs';import test from 'node:test';import assert from 'node:assert/strict';
import {placeItem,edgeAt,edgeVelocity} from '../src/lib/caller-drag.ts';import {widgetCatalog,defaultWidgets,validView} from '../src/lib/caller-dashboard.ts';
const voices=await import('../src/app/api/caller/voices/route.ts');
const caps=await import('../src/app/api/caller/voices/capabilities/route.ts'),clone=await import('../src/app/api/caller/voices/clone/route.ts');
test('C06 insertion follows either edge in both directions; empty canvas and cancellation primitives',()=>{assert.deepEqual(placeItem(['a','b','c'],'a','b','before'),['a','b','c']);assert.deepEqual(placeItem(['a','b','c'],'a','b','after'),['b','a','c']);assert.deepEqual(placeItem(['a','b','c'],'c','a','before'),['c','a','b']);assert.deepEqual(placeItem(['a','b','c'],'c','a','after'),['a','c','b']);assert.deepEqual(placeItem([],'new',null),['new']);assert.deepEqual(placeItem(['a'],'a','a'),['a']);assert.equal(edgeAt(9,0,20),'before');assert.equal(edgeAt(11,0,20),'after');assert(edgeVelocity(99,0,100)>0);assert(edgeVelocity(1,0,100)<0);assert.equal(edgeVelocity(120,0,100),0);});
test('C06 18 unique widgets retain original defaults and accept full gallery',()=>{assert.equal(widgetCatalog.length,18);assert.equal(new Set(widgetCatalog.map(w=>w.id)).size,18);assert.equal(defaultWidgets.length,10);assert(validView('analytics',{widgets:widgetCatalog.map(w=>({id:w.id,cols:6,rows:5}))}));});
test('C06 real admin guard, Free design/capacity and authorized clone consent/idempotency',async t=>{const original=fetch,env={...process.env};Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:'https://fluid-fixture.supabase.co',SUPABASE_SECRET_KEY:'fixture-secret',ELEVENLABS_API_KEY:'fixture-eleven'});const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';let plan={tier:'free',can_use_instant_voice_cloning:false,voice_limit:3,voice_slots_used:0},job:Record<string,unknown>|null=null,writes=0;
 globalThis.fetch=async(input,init)=>{const url=new URL(typeof input==='string'||input instanceof URL?input:input.url),headers=new Headers(init?.headers),method=init?.method||'GET',body=typeof init?.body==='string'?JSON.parse(init.body):null;if(url.pathname==='/auth/v1/user')return headers.get('authorization')?.includes('bad')?Response.json({message:'invalid'},{status:401}):Response.json({id:owner,email:'fixture@example.test',email_confirmed_at:new Date().toISOString()});if(url.pathname==='/rest/v1/nbc_members')return Response.json([{id:owner,display_name:'Fixture',role:headers.get('authorization')?.includes('student')?'student':'admin',status:'active'}]);if(url.pathname==='/v1/user/subscription')return Response.json(plan);if(url.pathname==='/v1/text-to-voice/design'){writes++;return Response.json({previews:[{generated_voice_id:'fixture-generated'}]});}if(url.pathname==='/v1/text-to-voice'){writes++;return Response.json({voice_id:'fixture-designed'});}if(url.pathname==='/v1/voices/add'){writes++;assert(init?.body instanceof FormData);assert.equal(init.body.get('description'),'Voice owner: Authorized Fixture; permission confirmed by NBC administrator.');return Response.json({voice_id:'fixture-copy',requires_verification:false});}assert.equal(url.pathname,'/rest/v1/caller_voice_jobs');if(method==='POST'){job=body;assert.equal(body.operator_id,owner);return new Response(null,{status:201});}assert.equal(url.searchParams.get('operator_id'),'eq.'+owner);if(method==='PATCH'){Object.assign(job!,body);return Response.json([{id}]);}return Response.json(job?[job]:[]);};
 const get=(token:string|null='admin')=>new Request('https://fixture.test/api/caller/voices/capabilities',{headers:token?{Authorization:'Bearer '+token}:{}});
 const audio=(name='Authorized Fixture',consent=true,token:string|null='admin')=>{const form=new FormData(),bytes=new Uint8Array(2048);bytes.set([0x1a,0x45,0xdf,0xa3]);Object.entries({requestId:id,name:'Fixture clone',voicePermission:'authorized',voiceOwnerName:name,voiceOwnerConsent:String(consent),acceptServiceUsage:'true'}).forEach(([k,v])=>form.set(k,v));form.set('sample',new File([bytes],'fixture.webm',{type:'audio/webm'}));return new Request('https://fixture.test/api/caller/voices/clone',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body:form});};
 try{await t.test('anonymous/invalid are rejected before any provider write',async()=>{for(const token of [null,'bad'])assert.equal((await clone.POST(audio('Authorized Fixture',true,token))).status,401);assert.equal(writes,0);});await t.test('Free design available while clone blocked; full slots block both',async()=>{let data=await (await caps.GET(get())).json();assert.equal(data.designAllowed,true);assert.equal(data.cloneAllowed,false);assert.equal(data.slotsRemaining,3);assert.equal((await clone.POST(audio())).status,403);plan={...plan,tier:'creator',can_use_instant_voice_cloning:true,voice_slots_used:3};data=await(await caps.GET(get())).json();assert.equal(data.designAllowed,false);assert.equal(data.cloneAllowed,false);assert.equal(writes,0);});await t.test('authorized voice requires owner and explicit consent; replay cannot change owner',async()=>{plan.voice_slots_used=0;for(const request of [audio('',true),audio('Authorized Fixture',false),audio('bad\nowner',true)])assert.equal((await clone.POST(request)).status,400);assert.equal(writes,0);assert.equal((await clone.POST(audio())).status,200);assert.equal((await(await clone.POST(audio())).json()).replayed,true);assert.equal((await clone.POST(audio('Different Fixture'))).status,409);assert.equal(writes,1);});await t.test('saved design can be replayed after the final slot is filled',async()=>{job=null;plan.voice_slots_used=0;const request=()=>new Request('https://fixture.test/api/caller/voices',{method:'POST',headers:{Authorization:'Bearer admin','Content-Type':'application/json'},body:JSON.stringify({requestId:id,name:'Fixture design',description:'An original clear warm American voice',acceptServiceUsage:true})});assert.equal((await voices.POST(request())).status,200);plan.voice_slots_used=3;assert.equal((await(await voices.POST(request())).json()).replayed,true);assert.equal(writes,3);});}finally{globalThis.fetch=original;for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);}
});
