import './caller-test-loader.mjs';import test from 'node:test';import assert from 'node:assert/strict';import{createHmac}from'node:crypto';
import {verifyRetellWebhook,safeRetellRecordingUrl,callTranscript} from '../src/lib/retell-webhook.ts';
import {phoneScenario} from '../src/lib/phone-scenario.ts';
import {parsePhoneTrial} from '../src/lib/caller-phone-trial.ts';
const {dispatchRetell}=await import('../src/services/retell-phone.service.ts');
test('webhook authenticates exact raw bytes and rejects altered, expired and future events',()=>{const raw='{"event": "call_started"}',now=Date.now(),key='test-secret';const sig=(r:string,t:number)=>`v=${t},d=${createHmac('sha256',key).update(r+t).digest('hex')}`;assert.ok(verifyRetellWebhook(raw,sig(raw,now),key,now));assert.equal(verifyRetellWebhook(raw+' ',sig(raw,now),key,now),false);assert.equal(verifyRetellWebhook(raw,sig(raw,now-300001),key,now),false);assert.equal(verifyRetellWebhook(raw,sig(raw,now+300001),key,now),false);assert.equal(verifyRetellWebhook(raw,'v=1,d=bad',key,now),false);});
test('recording retrieval accepts only verified provider recording hosts and bounded transcript fields',()=>{assert.ok(safeRetellRecordingUrl('https://d1d33audaiiiuu.cloudfront.net/id/recording.wav?Expires=1'));assert.ok(safeRetellRecordingUrl('https://retellai.s3.us-west-2.amazonaws.com/id/recording.wav?signature=abc'));for(const u of ['http://retellai.s3.us-west-2.amazonaws.com/id/recording.wav','https://attacker.test/recording.wav','https://retellai.s3.us-west-2.amazonaws.com.attacker.test/recording.wav','https://user@retellai.s3.us-west-2.amazonaws.com/id/recording.wav','https://retellai.s3.us-west-2.amazonaws.com/id/private.json'])assert.equal(safeRetellRecordingUrl(u),null);assert.deepEqual(callTranscript([{role:'tool',content:'hidden'},{role:'user',content:'Hello'},{role:'agent',content:3}]),[{role:'user',message:'Hello'}]);});
test('phone request accepts saved scenario IDs but never arbitrary prompts/configuration',()=>{const body={requestId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',phone:'+13055550123',confirmed:true,scenarioId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'};assert.equal(parsePhoneTrial(body).scenarioId,body.scenarioId);assert.throws(()=>parsePhoneTrial({...body,scenarioId:'wrong'}));assert.throws(()=>parsePhoneTrial({...body,prompt:'override'}));assert.match(phoneScenario(null).firstMessage,/recorded and transcribed/);});
test('scenario dispatch sends recorded-call disclosure, per-call scenario and live events without altering the agent',async()=>{const old=fetch,key=process.env.RETELL_API_KEY,origin=process.env.CALLER_WEBHOOK_ORIGIN;process.env.RETELL_API_KEY='fixture';process.env.CALLER_WEBHOOK_ORIGIN='https://preview.example.test';let count=0;globalThis.fetch=async(input,init)=>{count++;assert.equal(String(input),'https://api.retellai.com/v2/create-phone-call');const b=JSON.parse(String(init?.body));assert.match(b.retell_llm_dynamic_variables.nbc_scenario,/2500|2,500/);assert.match(b.agent_override.retell_llm.begin_message,/recorded/);assert.equal(b.agent_override.agent.data_storage_setting,'everything');assert.ok(b.agent_override.agent.webhook_events.includes('transcript_updated'));assert.equal(b.agent_override.agent.webhook_url,'https://preview.example.test/api/caller/webhooks/retell');return Response.json({call_id:'call_fixture',agent_id:'agent_fixture',from_number:'+13055550123',to_number:'+13055550124'});};try{await dispatchRetell({agentId:'agent_fixture',version:0,from:'+13055550123'} as never,'+13055550124','fixture',phoneScenario(null));assert.equal(count,1);}finally{globalThis.fetch=old;if(key===undefined)delete process.env.RETELL_API_KEY;else process.env.RETELL_API_KEY=key;if(origin===undefined)delete process.env.CALLER_WEBHOOK_ORIGIN;else process.env.CALLER_WEBHOOK_ORIGIN=origin;}});

test('archive routes reject anonymous access, foreign recordings and foreign note writes before contacting providers',async()=>{
 const routes=await import('../src/app/api/caller/archive/route.ts');const original=fetch,names=['NEXT_PUBLIC_SUPABASE_URL','SUPABASE_SECRET_KEY'],before=names.map(k=>process.env[k]);process.env.NEXT_PUBLIC_SUPABASE_URL='https://archive-fixture.supabase.co';process.env.SUPABASE_SECRET_KEY='fixture';const owner='11111111-1111-4111-8111-111111111111',key='web-22222222-2222-4222-8222-222222222222';let providers=0;
 globalThis.fetch=async(input,init)=>{const u=new URL(String(input));if(u.hostname!=='archive-fixture.supabase.co'){providers++;throw Error('Unexpected provider request');}if(u.pathname==='/auth/v1/user')return Response.json({id:owner,email_confirmed_at:'2026-01-01T00:00:00Z'});if(u.pathname==='/rest/v1/nbc_members')return Response.json([{id:owner,display_name:'Fixture',role:'admin',status:'active'}]);if(u.pathname==='/rest/v1/call_sessions'){assert.equal(u.searchParams.get('operator_id'),'eq.'+owner);return Response.json([]);}throw Error('Unexpected storage write');};
 try{assert.equal((await routes.GET(new Request('https://fixture.test/api/caller/archive'))).status,401);assert.equal((await routes.GET(new Request('https://fixture.test/api/caller/archive?recording='+key,{headers:{Authorization:'Bearer fixture'}}))).status,404);assert.equal((await routes.PATCH(new Request('https://fixture.test/api/caller/archive',{method:'PATCH',headers:{Authorization:'Bearer fixture','Content-Type':'application/json'},body:JSON.stringify({key,note:'Unauthorized',version:0})}))).status,404);assert.equal(providers,0);}finally{globalThis.fetch=original;names.forEach((n,i)=>{if(before[i]===undefined)delete process.env[n];else process.env[n]=before[i];});}
});
