import './caller-test-loader.mjs';import assert from 'node:assert/strict';import test from 'node:test';
const demo=await import('../src/app/api/caller/demo/route.ts'),lists=await import('../src/app/api/caller/lists/route.ts'),clone=await import('../src/app/api/caller/voices/clone/route.ts'),caps=await import('../src/app/api/caller/voices/capabilities/route.ts'),sessions=await import('../src/app/api/caller/sessions/route.ts');
const {canExportSession}=await import('../src/lib/caller-insights.ts');
const admin='11111111-1111-4111-8111-111111111111',student='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
function req(path:string,method='GET',body?:unknown,token:string|null='admin'){return new Request('https://fixture.test'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});}
function audio(token:string|null='admin',consent=true,bytes=2048,valid=true){const form=new FormData();form.set('requestId',id);form.set('name','Own fixture voice');form.set('ownVoiceConsent',String(consent));form.set('acceptServiceUsage','true');const buf=new Uint8Array(bytes);if(valid)buf.set([0x1a,0x45,0xdf,0xa3]);form.set('sample',new File([buf],'fixture.webm',{type:'audio/webm'}));return new Request('https://fixture.test/api/caller/voices/clone',{method:'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Length':String(bytes+1000)},body:form});}
test('C03 real route/auth/service guard, demo scoping and clone idempotency',async t=>{
 const original=fetch,env={...process.env};Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:'https://ops-fixture.supabase.co',SUPABASE_SECRET_KEY:'fixture-secret',ELEVENLABS_API_KEY:'fixture-voice',VERCEL_ENV:'preview'});let paid=false,write=0,db=0,foreign=false,fail=false,job:Record<string,unknown>|null=null;
 globalThis.fetch=async(input,init)=>{const url=new URL(typeof input==='string'||input instanceof URL?input:input.url),method=init?.method||'GET',headers=new Headers(init?.headers),body=typeof init?.body==='string'?JSON.parse(init.body):null;
  if(url.pathname==='/auth/v1/user'){if(headers.get('authorization')?.includes('invalid'))return Response.json({message:'invalid'},{status:401});return Response.json({id:headers.get('authorization')?.includes('student')?student:admin,email:'fixture@example.test',email_confirmed_at:'2026-09-14T00:00:00Z'});}
  if(url.pathname==='/rest/v1/nbc_members')return Response.json([{id:url.searchParams.get('id')?.slice(3),display_name:'Fixture',role:url.searchParams.get('id')?.includes(student)?'student':'admin',status:'active'}]);
  if(url.hostname==='api.elevenlabs.io'){if(url.pathname==='/v1/user/subscription')return Response.json({tier:paid?'creator':'free',can_use_instant_voice_cloning:paid});assert.equal(url.pathname,'/v1/voices/add');assert(init?.body instanceof FormData);write++;if(fail)return Response.json({detail:{status:'quota_exceeded',message:'PRIVATE-provider-error'}},{status:429});return Response.json({voice_id:'fixture-clone',requires_verification:true});}
  db++;
  if(url.pathname==='/rest/v1/caller_voice_jobs'){if(method==='POST'){job=body;return new Response(null,{status:201});}assert.equal(url.searchParams.get('operator_id'),'eq.'+admin);if(method==='PATCH'){Object.assign(job!,body);return Response.json([{id}]);}return Response.json(job?[job]:[]);}
  if(url.pathname==='/rest/v1/rpc/caller_demo_set'){assert.equal(body.p_operator,admin);return Response.json({enabled:body.p_enabled});}
  if(url.pathname==='/rest/v1/rpc/caller_save_list'){assert.equal(body.p_operator,admin);return foreign?Response.json({message:'invalid_selection'},{status:400}):Response.json(id);}
  assert.equal(url.searchParams.get('operator_id'),'eq.'+admin);assert.equal(url.searchParams.get('is_demo'),'eq.true');
  return method==='HEAD'?new Response(null,{headers:{'Content-Range':'0-0/1'}}):Response.json([]);
 };
 try{
 await t.test('anonymous invalid and non-admin cannot seed, clone, read demo or capabilities',async()=>{for(const token of [null,'invalid','student']){const expected=token==='student'?403:401,before=db;for(const response of [await demo.POST(req('/api/caller/demo','POST',{enabled:true},token)),await clone.POST(audio(token)),await caps.GET(req('/api/caller/voices/capabilities','GET',undefined,token)),await lists.GET(req('/api/caller/lists?demo=true','GET',undefined,token)),await sessions.GET(req('/api/caller/sessions?demo=true','GET',undefined,token))])assert.equal(response.status,expected);assert.equal(db,before);}assert.equal(write,0);});
 await t.test('admin demo owner injected, production denied, list validation and cross-owner rejection',async()=>{assert.equal((await demo.GET(req('/api/caller/demo'))).status,200);assert.equal((await demo.POST(req('/api/caller/demo','POST',{enabled:true,operator_id:student}))).status,200);process.env.VERCEL_ENV='production';assert.equal((await demo.POST(req('/api/caller/demo','POST',{enabled:true}))).status,403);process.env.VERCEL_ENV='preview';assert.equal((await lists.POST(req('/api/caller/lists','POST',{id,name:'Fixture',leadIds:[id,id]}))).status,400);foreign=true;assert.equal((await lists.POST(req('/api/caller/lists','POST',{id,name:'Fixture',leadIds:[student]}))).status,400);foreign=false;assert.equal((await lists.POST(req('/api/caller/lists','POST',{id,name:'Fixture',leadIds:[id],demo:true}))).status,200);});
 await t.test('unsupported plan, consent and oversized audio never reach clone API',async()=>{assert.equal((await caps.GET(req('/api/caller/voices/capabilities'))).status,200);assert.equal((await clone.POST(audio())).status,403);assert.equal((await clone.POST(audio('admin',false))).status,400);assert.equal((await clone.POST(audio('admin',true,3*1024*1024+70000))).status,413);assert.equal((await clone.POST(audio('admin',true,2048,false))).status,400);assert.equal(write,0);});
 await t.test('same clone request creates once; verification state returned; failures sanitized and never retried',async()=>{paid=true;let response=await clone.POST(audio());assert.equal(response.status,200);assert.equal((await response.json()).needsVerification,true);response=await clone.POST(audio());assert.equal((await response.json()).replayed,true);assert.equal(write,1);assert.equal((await clone.POST(audio('admin',true,2049))).status,409);assert.equal(write,1);job=null;fail=true;response=await clone.POST(audio());assert.equal(response.status,502);assert(!(await response.text()).includes('PRIVATE-provider-error'));assert.equal((await clone.POST(audio())).status,409);assert.equal(write,2);assert.equal(job!.status,'failed');});
 await t.test('synthetic transcript cannot masquerade as verified export',()=>{assert.equal(canExportSession({is_demo:true,status:'completed',synced_at:new Date().toISOString(),transcript:[{role:'agent',message:'demo',time_in_call_secs:0}]} as never),false);});
 }finally{globalThis.fetch=original;for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);}
});
