import assert from 'node:assert/strict';import test from 'node:test';
import {defaultOverview,parseOverview,placeWidgets,widgetDimensions,widgetIds} from '../src/lib/overview-layout.ts';
import {googleCalendarEntry,safeMeetingUrl} from '../src/lib/calendar-feed.ts';
test('I04 combined metrics migrate to individual widgets without losing personal data',()=>{const p=parseOverview(JSON.stringify({version:1,widgets:[{id:'metrics',size:'full'},{id:'activity',size:'wide',width:8,height:5}],milestones:[{id:'a',title:'Practice',completed:true}],lesson:{inventoryId:'course',lessonId:'lesson'},completedLessons:['course/lesson']}));assert.deepEqual(p.widgets.map(w=>w.id),['leads','ready','conversations','practice','activity']);assert.equal(p.widgets[4].width,8);assert.equal(p.milestones[0].completed,true);assert.equal(p.lesson?.lessonId,'lesson');});
test('all responsive dense placements remain bounded and never overlap across mixed 2D sizes',()=>{for(const columns of [6,8,12])for(let variant=0;variant<40;variant++){const widgets=defaultOverview().widgets.filter((_,i)=>(i+variant)%3!==0).map((w,i)=>({...w,width:3+(i+variant)%10,height:2+(i*3+variant)%7}));const cells=new Set();const placed=placeWidgets(widgets,columns);assert.equal(placed.length,widgets.length);for(const p of placed){assert(p.x>=0&&p.x+p.width<=columns&&p.y>=0);for(let y=p.y;y<p.y+p.height;y++)for(let x=p.x;x<p.x+p.width;x++){assert(!cells.has(`${x}:${y}`));cells.add(`${x}:${y}`);}}}});
test('sizes affect width and height and invalid stored dimensions are ignored',()=>{assert.deepEqual(widgetDimensions({id:'activity',size:'full'}),{width:12,height:6});assert.deepEqual(widgetDimensions({id:'leads',size:'compact'}),{width:3,height:2});const p=parseOverview(JSON.stringify({version:1,widgets:[{id:'activity',size:'wide',width:999,height:-1}]}));assert.equal(p.widgets[0].width,undefined);assert.equal(p.widgets[0].height,undefined);assert.equal(defaultOverview().widgets.length,widgetIds.length);});
test('calendar mapping excludes cancelled/private items and exposes no attendee data',()=>{const source={id:'a',summary:'Coaching',start:{dateTime:'2026-09-16T10:00:00-05:00'},end:{dateTime:'2026-09-16T11:00:00-05:00'},conferenceData:{entryPoints:[{entryPointType:'video',uri:'https://meet.google.com/abc-defg-hij'}]},attendees:[{email:'private@example.com'}]};const event=googleCalendarEntry(source);assert.equal(event?.source,'google');assert.equal(event?.join_url,'https://meet.google.com/abc-defg-hij');assert(!('attendees' in event!));assert.equal(googleCalendarEntry({...source,status:'cancelled'}),null);assert.equal(googleCalendarEntry({...source,visibility:'private'}),null);assert.equal(googleCalendarEntry({...source,end:{dateTime:'bad'}}),null);assert.equal(safeMeetingUrl('javascript:alert(1)'),null);assert.equal(safeMeetingUrl('https://user:password@example.com'),null);assert.equal(googleCalendarEntry({id:'day',start:{date:'2026-09-16'},end:{date:'2026-09-17'}})?.all_day,true);});
test('balanced rows fill every cell and preserve reading order after resize or removal',()=>{for(const columns of [6,8,12])for(let variant=0;variant<40;variant++){const widgets=defaultOverview().widgets.filter((_,i)=>(i+variant)%4!==0).map((w,i)=>({...w,width:3+(i+variant)%10,height:2+(i*3+variant)%7}));const placed=placeWidgets(widgets,columns);assert.deepEqual(placed.map(p=>p.widget.id),widgets.map(w=>w.id));const bottom=Math.max(0,...placed.map(p=>p.y+p.height));assert.equal(placed.reduce((sum,p)=>sum+p.width*p.height,0),columns*bottom);}});
test('old default learning pair migrates without resetting personal content or custom sizes',()=>{const original={...defaultOverview(),widgets:[{id:'roadmap',size:'wide',width:6,height:5},{id:'lesson',size:'compact',width:6,height:7}],milestones:[{id:'a',title:'Keep this goal',completed:true}],lesson:{inventoryId:'a',lessonId:'b'}};const p=parseOverview(JSON.stringify(original));assert.deepEqual(p.widgets.map(w=>w.width),[4,8]);assert.deepEqual(p.milestones,original.milestones);assert.deepEqual(p.lesson,original.lesson);original.widgets[1].width=9;assert.equal(parseOverview(JSON.stringify(original)).widgets[1].width,9);});
