'use client';
import{useEffect,useState}from'react';
import{RefreshCw,ReceiptText,ArrowDownToLine,Plus,X}from'lucide-react';
import{summarizeCosts,type OperationCostReport}from'@/lib/operation-costs';
import{csvCell}from'@/lib/run-review';
import styles from './OperationCosts.module.css';
const money=(n:number|null)=>n===null?'Pending':`$${(n/1e6).toFixed(4)}`;
export function OperationCosts({token,revision=0,initialKind='All'}:{token:string;revision?:number;initialKind?:string}){
 const[data,setData]=useState<OperationCostReport|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false),[kind,setKind]=useState(initialKind),[industry,setIndustry]=useState('All'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[adding,setAdding]=useState(false),[saving,setSaving]=useState(false),[reconciling,setReconciling]=useState(false),[reconciliation,setReconciliation]=useState('');
 useEffect(()=>{const controller=new AbortController();setError('');setLoading(true);void fetch('/api/admin/costs',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(()=>{if(!controller.signal.aborted)setError('Costs could not be refreshed. Any displayed values are the previous snapshot.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,revision,refresh]);
 const rows=(data?.rows??[]).filter(r=>(kind==='All'||r.kind===kind)&&(industry==='All'||r.industry===industry)&&(!from||r.createdAt.slice(0,10)>=from)&&(!to||r.createdAt.slice(0,10)<=to)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 const totals=summarizeCosts(rows),pending=rows.filter(r=>!r.receiptComplete).length,max=Math.max(1,...totals.providers.map(p=>(p.reportedMicrousd??0)+(p.estimatedMicrousd??0)));
 function exportCosts(){const csv=[['Operation','Kind','Industry','Date UTC','Provider','Reported USD','Estimated USD','Receipt complete','Missing components','Current qualified mobiles','Seconds','Note'],...rows.flatMap(r=>r.lines.map(l=>[r.title,r.kind,r.industry,r.createdAt,l.provider,l.reportedMicrousd===null?'':(l.reportedMicrousd/1e6).toFixed(6),l.estimatedMicrousd===null?'':(l.estimatedMicrousd/1e6).toFixed(6),r.receiptComplete?'Yes':'No',l.missing,r.qualified??'',r.seconds??'',r.note]))].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nbc-operation-costs.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function reconcile(){if(reconciling)return;setReconciling(true);setReconciliation('');try{const r=await fetch('/api/admin/costs',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'reconcile'})});const b=await r.json();if(!r.ok)throw Error(b.error);setReconciliation(`${b.updated} receipts updated · ${b.unavailable} unavailable · ${b.skipped} other operations need separate reconciliation.${b.limited?' First 10 records processed; run again for remaining receipts.':''}`);setRefresh(v=>v+1);}catch{setReconciliation('Receipt reconciliation could not finish. Existing amounts remain visible; refresh before retrying.');}finally{setReconciling(false);}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;setSaving(true);setError('');const form=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/api/admin/costs',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)throw Error(body.error??'Could not save.');setAdding(false);setRefresh(r=>r+1);}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 return <section className={styles.workspace} aria-label="Operation cost breakdown">
 <header className={styles.header}><div><span className={styles.eyebrow}>ADMIN · COST CONTROL</span><h2>Know where every dollar goes.</h2><p>Operation usage and account billing, with the gaps visible.</p></div><button disabled={loading} onClick={()=>setRefresh(r=>r+1)}><RefreshCw size={15}/>{loading?'Refreshing…':'Refresh costs'}</button></header>
 {error&&<p role="alert" className={styles.notice}>{error}</p>}
 {!data?<p role="status">Loading saved receipts…</p>:<>
 <div className={styles.filters}><label>Product<select aria-label="Product" value={kind} onChange={e=>{setKind(e.target.value);setIndustry('All');}}>{['All','Scraper','Caller','Browser voice'].map(k=><option key={k}>{k}</option>)}</select></label><label>Industry<select aria-label="Industry" value={industry} onChange={e=>setIndustry(e.target.value)}><option>All</option>{[...new Set(data.rows.filter(r=>kind==='All'||r.kind===kind).map(r=>r.industry))].sort().map(i=><option key={i}>{i}</option>)}</select></label><label>From (UTC)<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through (UTC)<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button onClick={exportCosts} disabled={!rows.length}><ArrowDownToLine size={15}/>Export breakdown</button></div>
 <div className={styles.metrics}><article><span>Provider-reported usage</span><strong>{money(totals.reportedMicrousd)}</strong><small>Known components · not the full account bill</small></article><article><span>Additional rate estimates</span><strong>{money(totals.estimatedMicrousd)}</strong><small>Saved rates · not invoice-confirmed</small></article><article><span>Incomplete operations</span><strong>{pending}<em> / {rows.length}</em></strong><small>{totals.missing} missing components · final unit cost withheld</small></article></div>
 <div><button disabled={reconciling} onClick={()=>void reconcile()}><RefreshCw size={15}/>{reconciling?'Reading provider receipts…':'Reconcile Apify & Retell receipts'}</button><p>Read-only provider billing requests. No searches, phone checks or calls are started.</p>{reconciliation&&<p role="status">{reconciliation}</p>}</div>
 <p className={styles.notice}>Account total is not reconciled. Plans, phone rental, storage, taxes and outside activity can add costs. Reservations are spending limits, not charges. Usage may be included in a subscription or paid from credit: do not add usage and invoices together.</p>
 {data.truncated&&<p role="alert" className={styles.notice}>Partial retrieval: the record limit was reached. Narrowing these filters does not recover missing records.</p>}
 <div className={styles.card}><h3>Where the usage went</h3><div className={styles.providers}>{totals.providers.map(p=><article key={p.provider}><div><strong>{p.provider}</strong><span>{money(p.reportedMicrousd)} reported{p.estimatedMicrousd!==null?` + ${money(p.estimatedMicrousd)} estimated`:''}</span></div><div className={styles.track}><span style={{width:`${100*((p.reportedMicrousd??0)+(p.estimatedMicrousd??0))/max}%`}}/></div><small>{p.missing?`${p.missing} components still unpriced`:'See each operation for receipt completeness'}</small></article>)}</div>{!rows.length&&<p>No operations match these filters.</p>}</div>
 <div className={styles.card}><h3>Each call. Each list.</h3><p>Unit costs cover operation usage only. Mobile counts reflect current verification validity; they are not a historical delivery snapshot.</p><div className={styles.table}><table><thead><tr><th>Operation</th><th>Usage breakdown</th><th>Results / unit cost</th><th>Receipt</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td><strong>{r.title}</strong><small>{r.kind} · {r.industry}</small><small>{r.createdAt.slice(0,10)} · {r.state}</small></td><td>{r.lines.map((l,i)=><div key={i}><span>{l.provider}: {l.reportedMicrousd!==null?money(l.reportedMicrousd)+' reported':l.estimatedMicrousd!==null?money(l.estimatedMicrousd)+' estimated':'Pending'}</span>{l.details?.length?<details><summary>Included components</summary>{l.details.map((d,j)=><small key={j}>{d.product}: {money(d.costMicrousd)}</small>)}<small>Included in the bundle; never added again. Discounts may change the combined amount.</small></details>:null}</div>)}</td><td>{r.kind==='Scraper'?<>{r.businesses} businesses · {r.checked} checked<small>{r.qualified} currently qualified mobiles</small><strong>{money(r.costPerQualifiedMicrousd)} / mobile</strong>{r.estimatedMicrousd>0&&<small>Includes rate estimate</small>}</>:<>{r.seconds??'—'} seconds<small>{money(r.costPerMinuteMicrousd)} / minute</small></>}</td><td><span className={r.receiptComplete?styles.complete:styles.pending}>{r.receiptComplete?'Usage captured':'Needs reconciliation'}</span><details><summary>Details & limits</summary><p>{r.note}</p><small>Approved: {money(r.approvedMicrousd)} · reserved: {money(r.reservedMicrousd)}. Neither is a charge.</small></details></td></tr>)}</tbody></table></div></div>
 <div className={styles.card}><div className={styles.header}><div><h3><ReceiptText size={18}/>Account billing documents</h3><p>All products and dates. Admin-recorded source documents, separate from the filtered usage above. An invoice is not proof of payment.</p></div><button onClick={()=>setAdding(!adding)}>{adding?<X size={15}/>:<Plus size={15}/>} {adding?'Close':'Record document'}</button></div>
 {adding&&<form onSubmit={save} className={styles.form}><label>Provider<input name="provider" list="cost-providers" maxLength={80} required/></label><datalist id="cost-providers">{data.coverage?.map(c=><option key={c.provider}>{c.provider}</option>)}</datalist><label>Invoice / receipt number<input name="reference" maxLength={160} required/></label><label>Issue date<input name="issued_on" type="date" required/></label><label>Type<select name="kind"><option value="invoice">Invoice</option><option value="prepayment">Prepaid credit purchase</option></select></label><label>Currency<input name="currency" defaultValue="USD" pattern="[A-Z]{3}" maxLength={3} required/></label><label>Document total<input name="total" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required/></label><label>Applied balance<input name="applied" inputMode="decimal" defaultValue="0" required/></label><label>Amount due on document<input name="due" inputMode="decimal" required/></label><label>Evidence reference<input name="evidence" placeholder="Invoice filename or billing reference" maxLength={500} required/></label><label>Billing period / notes<textarea name="note" maxLength={2000}/></label><p>Amounts stay in the original currency. Applied balance + amount due must equal the total. Recording a document does not charge or pay anything.</p><button disabled={saving}>{saving?'Saving…':'Save billing document'}</button></form>}
 <div className={styles.table}><table><thead><tr><th>Provider / document</th><th>Document total</th><th>Balance applied</th><th>Due on document</th><th>Evidence / allocation</th></tr></thead><tbody>{data.statements?.map(s=><tr key={s.id}><td><strong>{s.provider}</strong><small>{s.reference} · {s.issued_on}</small><small>{s.kind==='prepayment'?'Prepaid credit · not usage expense':'Invoice'}</small></td><td>{(s.total_microusd/1e6).toFixed(2)} {s.currency}</td><td>{(s.applied_microusd/1e6).toFixed(2)} {s.currency}</td><td>{(s.due_microusd/1e6).toFixed(2)} {s.currency}</td><td>{s.evidence}<small>{s.note}</small><small>Not allocated to individual operations</small></td></tr>)}</tbody></table></div>{!data.statements?.length&&<p>No billing documents recorded. Missing invoices are not zero expense.</p>}</div>
 <details className={styles.card}><summary>Provider coverage & reconciliation checklist</summary><div className={styles.coverage}>{data.coverage?.map(c=><article key={c.provider}><strong>{c.provider}</strong><p>{c.components}</p><small>{c.status}</small></article>)}</div>{data.unallocated?.map(u=><p key={u.source}><strong>{u.source}: {u.records} records</strong>{u.records?` · ${money(u.amountMicrousd)}`:''}. {u.note}</p>)}</details>
 <p className={styles.footnote}>Saved snapshot: {new Date(data.generatedAt).toLocaleString('en-US')}. Refresh reads stored receipts only; it never places calls, verifies phones or starts searches. Late provider charges require reconciliation.</p>
 </>}</section>;
}
