'use client';
import{useEffect,useState}from'react';
import type{OperationCostReport}from'@/lib/operation-costs';
import styles from './Account.module.css';
const money=(n:number|null)=>n===null?'Pending':`$${(n/1e6).toFixed(4)}`;
export function OperationCosts({token,revision}:{token:string;revision:number}){
 const[data,setData]=useState<OperationCostReport|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setError('');void fetch('/api/admin/costs',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)])}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(()=>{if(!controller.signal.aborted)setError('Operation costs could not be loaded. Refresh to retry.');});return()=>controller.abort();},[token,revision]);
 return <section className={styles.card} style={{minWidth:0}} aria-label="Operation cost breakdown"><h2>Calls & lists · cost breakdown</h2><p>Saved receipts, grouped by operation and provider. These overlap with provider-wide and member usage below: do not add those totals together.</p>{error?<p role="alert">{error}</p>:!data?<p>Loading saved costs…</p>:<>
 <p><strong>{money(data.reportedMicrousd)}</strong> reported usage · <strong>{money(data.estimatedMicrousd)}</strong> additional rate-based estimate · <strong>{data.missing}</strong> missing cost components</p>
 <p>Approved maximums and reservations are not charges. Historical phone checks without a saved rate remain pending. Subscriptions, taxes, numbers, top-ups and activity outside these lists/calls are not included.</p>
 {data.truncated&&<p role="alert">Partial report: the retrieval limit was reached. Totals do not cover all operations.</p>}
 <div className={styles.table}><table><thead><tr><th>Provider</th><th>Reported usage</th><th>Rate estimate</th><th>Missing components</th></tr></thead><tbody>{data.providers.map(p=><tr key={p.provider}><td>{p.provider}</td><td>{money(p.reportedMicrousd)}</td><td>{money(p.estimatedMicrousd)}</td><td>{p.missing}</td></tr>)}</tbody></table></div>
 <div className={styles.table}><table><thead><tr><th>Operation / industry</th><th>Approved / reserved</th><th>Usage breakdown</th><th>Unit economics</th><th>Response timing</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.key}><td><strong>{r.title}</strong><small>{r.kind} · {r.industry} · {r.state}</small><small>{new Date(r.createdAt).toLocaleDateString('en-US')}</small></td><td>{money(r.approvedMicrousd)} / {money(r.reservedMicrousd)}</td><td>{r.lines.map(l=><small key={l.provider}>{l.provider}: {l.reportedMicrousd!==null?money(l.reportedMicrousd)+' reported':l.estimatedMicrousd!==null?money(l.estimatedMicrousd)+' estimated':'Pending'}{l.missing?` · ${l.missing} missing`:''}</small>)}</td><td>{r.kind==='Caller'?<>{r.seconds??'—'} seconds<small>{money(r.costPerMinuteMicrousd)} / minute</small></>:<>{r.qualified} phone-qualified mobiles<small>{money(r.costPerQualifiedMicrousd)} / qualified contact{r.estimatedMicrousd?' · includes estimate':''}</small></>}</td><td>{r.latency?<><span>Median {(r.latency.p50Ms/1000).toFixed(2)}s · p95 {(r.latency.p95Ms/1000).toFixed(2)}s</span><small>{r.latency.samples} responses · provider timing</small><small>{r.latency.definition}</small></>:'Not measured'}</td></tr>)}</tbody></table></div>
 <p>Updated from stored results {new Date(data.generatedAt).toLocaleTimeString('en-US')}. Provider receipts can arrive later; refresh the relevant call or list to reconcile. This page does not trigger paid work.</p>
 </>}</section>;
}
