'use client';
import {useEffect,useState} from 'react';
import type {PilotSlotView} from '@/lib/live-pilot';
import type {OperationCostReport,OperationCostRow} from '@/lib/operation-costs';
import {verificationSummary,verificationPercent} from '@/lib/run-review';
import styles from './LeadRunSummary.module.css';
export function LeadRunSummary({slot,token}:{slot:PilotSlotView;token:string}){
 const summary=verificationSummary(slot.result),found=slot.result.rows?.length??0;
 const [cost,setCost]=useState<OperationCostRow|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const c=new AbortController();setCost(null);setFailed(false);void fetch('/api/admin/costs',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.any([c.signal,AbortSignal.timeout(20000)])}).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<OperationCostReport>;}).then(r=>setCost(r.rows.find(row=>row.key.endsWith('/'+slot.key))??null)).catch(()=>{if(!c.signal.aborted)setFailed(true);});return()=>c.abort();},[token,slot.key,slot.updatedAt,summary.checked]);
 if(!found)return null;
 const usd=(v:number)=>'$'+(v/1e6).toFixed(4);
 return <section className={styles.board} aria-label="Selected list performance"><header><div><span>YOUR LIST AT A GLANCE</span><h3>{slot.title}</h3></div><a href="#costs">View costs & yield ↗</a></header><div className={styles.metrics}>{[['Businesses found',found,'Before exclusions'],['Eligible phones',summary.total,'Unique business numbers'],['Phone checks completed',summary.checked,`${summary.pending} pending · ${summary.unresolved} unresolved`],['Qualified mobiles',summary.qualified,'Current checks passed · ready to review']].map(([title,note,detail])=><article key={title}><span>{title}</span><strong>{note}</strong><small>{detail}</small></article>)}</div>
 <div className={styles.bottom}><div><h4>What verification found</h4><div className={styles.bar} aria-label={`${summary.mobile} mobile, ${summary.landline} landline, ${summary.other} other or unknown`}>{[[summary.mobile,'mobile'],[summary.landline,'landline'],[summary.other,'other']].map(([n,key])=><span key={key} data-type={key} style={{width:summary.checked?`${100*Number(n)/summary.checked}%`:'0%'}}/>)}</div><p><i/>Mobile {summary.mobile} <i data-type="landline"/>Landline {summary.landline} <i data-type="other"/>Other / unknown {summary.other}</p><small>{summary.checked?`${verificationPercent(summary.qualified,summary.checked)} of completed checks qualify for the mobile export.`:'Verification has not returned results yet.'} Landlines are not failed numbers.</small></div><div className={styles.cost}><span>Recorded list usage</span><strong>{cost?usd(cost.reportedMicrousd):failed?'Unavailable':'Loading…'}</strong><p>{cost&&cost.estimatedMicrousd>0?`+ ${usd(cost.estimatedMicrousd)} rate estimate`:'Phone verification is not assumed to be free.'}</p><small>{cost?.receiptComplete?`Usage captured${cost.costPerQualifiedMicrousd!==null?' · '+usd(cost.costPerQualifiedMicrousd)+' / qualified mobile':''}. Excludes shared account expenses.`:'Incomplete cost mapping · final cost per mobile pending.'}</small></div></div></section>;
}
