'use client';
import {useEffect,useState} from 'react';
import {Download,Search,CheckCircle2,ArrowRight} from 'lucide-react';
import type {PilotSlotView} from '@/lib/live-pilot';
import {excludeBeforeVerification,qualifiedRows,phoneDecision,verificationSummary} from '@/lib/run-review';
import styles from './LeadListWorkspace.module.css';
export function LeadRunResults({slot,token}:{slot:PilotSlotView;token:string}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setQuery('');setFilter('all');setPage(0);setError('');setNotice('');},[slot.key]);
 const rows=slot.result.rows??[],qualified=qualifiedRows(slot.result),summary=verificationSummary(slot.result),passed=new Set(qualified),checks=new Map(slot.result.phoneChecks?.map(c=>[c.phone10,c]));
 const filtered=rows.filter(r=>(!query||[r.name,r.city,r.state,r.phone10].join(' ').toLowerCase().includes(query.toLowerCase()))&&(filter==='all'||(filter==='mobile'?passed.has(r):filter==='excluded'?!!excludeBeforeVerification(r):!checks.has(r.phone10??''))));
 const pages=Math.max(1,Math.ceil(filtered.length/50)),current=Math.min(page,pages-1);
 async function download(format:'csv'|'xlsx'){
  setBusy(format);setError('');try{const r=await fetch(`/api/lead-engine/runs/${slot.key}/export?format=${format}&qualified=${filter==='mobile'}`,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Export could not be prepared. Please try again.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=(slot.title.replace(/[^a-zA-Z0-9_-]/g,'-')||'lead-list')+(filter==='mobile'?'-verified-mobile':'')+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setBusy('');}
 }
 async function handoff(){setBusy('caller');setError('');try{const r=await fetch('/api/lead-engine/handoff',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({key:slot.key,requestId:crypto.randomUUID()})}),b=await r.json();if(!r.ok)throw Error(b.error??'Transfer failed.');setNotice(`${b.imported} contacts added; ${b.duplicates} already saved. No calls started.`);}catch(e){setError(e instanceof Error?e.message:'Transfer failed.');}finally{setBusy('');}}
 return <section className={styles.card} aria-label="Saved list contacts"><header className={styles.header}><div><span className={styles.eyebrow}>SAVED RESULTS</span><h2>{slot.title}</h2><p>Your results are saved automatically in Lead Lists.</p></div><div className={styles.actions}><button disabled={!!busy||!rows.length} onClick={()=>void download('csv')}><Download size={15}/>CSV</button><button disabled={!!busy||!rows.length} onClick={()=>void download('xlsx')}><Download size={15}/>Excel</button></div></header>
 <div className={styles.metrics}><div><strong>{rows.length}</strong><span>Businesses found</span></div><div><strong>{summary.checked}</strong><span>Phones checked</span></div><div><strong>{summary.qualified}</strong><span>Verified mobiles</span></div><div><strong>{slot.reportedMicrousd===null?'Pending':'$'+(slot.reportedMicrousd/1e6).toFixed(4)}</strong><span>Discovery receipt · checks billed separately</span></div></div>
 <div className={styles.filters}><label><Search size={16}/><input aria-label="Search contacts" placeholder="Search business, phone or city" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label="Filter contacts" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All businesses</option><option value="mobile">Verified mobiles</option><option value="pending">Not checked yet</option><option value="excluded">Excluded</option></select><button disabled={!qualified.length||!!busy||slot.state!=='completed'} onClick={()=>void handoff()}>Send verified to Caller<ArrowRight size={15}/></button></div>
 <p className={styles.note}>Exports contain {filter==='mobile'?'verified mobiles only':'all saved businesses'}, with their verification status. The text search filters this view only. Mobile verification does not confirm owner identity.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice} <a href="/caller#crm">Open Caller</a></p>}
 <div className={styles.tableWrap}><table><thead><tr><th>Business</th><th>Phone</th><th>Location</th><th>Line type</th><th>Result</th></tr></thead><tbody>{filtered.slice(current*50,current*50+50).map((row,i)=>{const check=checks.get(row.phone10??''),excluded=excludeBeforeVerification(row),ok=passed.has(row);return <tr key={i}><td><strong>{row.name}</strong>{row.website&&<a href={row.website} target="_blank" rel="noreferrer">Website ↗</a>}</td><td>{row.phone10?'+1 '+row.phone10:'No published phone'}</td><td>{row.city}, {row.state}</td><td>{check?.verification?.lineType??'Not checked'}</td><td><span className={ok?styles.passed:styles.status}>{ok&&<CheckCircle2 size={13}/>} {excluded?excluded.replaceAll('_',' '):check?.state==='completed'?phoneDecision(check.verification).label:check?.state??'Awaiting checks'}</span></td></tr>;})}</tbody></table>{!filtered.length&&<p className={styles.empty}>{rows.length?'No contacts match this view.':slot.state==='completed'?'No businesses were returned for this search. Try a broader market.':'Results will appear here as they are saved.'}</p>}</div>
 <footer className={styles.pagination}><span>{filtered.length} contacts · Page {current+1} of {pages}</span><button disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></footer></section>;
}
