'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, ChevronDown, MapPin, Search, ShieldCheck } from 'lucide-react';
import { useWorkspaceAccess } from '@/components/workspace/WorkspaceAccess';
import { benchmarkLabel, type IndustryWorkflow } from '@/lib/lead-engine-workflows';
import { WORKFLOW_NICHES, CROSS_NICHE_REVIEWS, METHOD_NAMES, STATE_CODES, stateName, nicheReview, nicheReviewIds, methodComparison, matchingStates, stateRouteStatus, type EffectiveWorkflowRoute, type WorkflowNiche } from '@/lib/lead-engine-niches';
import styles from './LeadBrain.module.css';
import { sourceName, toolFlow } from '@/lib/lead-engine-tool-flow';
import { LeadToolDiagram } from './LeadToolDiagram';

interface Industry { key:string; aliases:string[]; recipe:string; registerSource:Record<string,string>; expectedClean:number; n:number; measuredBy:string; effectiveRoutes?:Record<string,EffectiveWorkflowRoute> }
interface BrainView { industries:Industry[]; workflowReviews:Record<string,IndustryWorkflow> }
const method = (route?:EffectiveWorkflowRoute) => route?.recipe ? METHOD_NAMES[route.recipe] : 'Route unavailable';
export function LeadBrain() { const {token,user}=useWorkspaceAccess(); return token&&user?.role==='admin' ? <Brain key={user.id} token={token}/> : null; }
function Brain({token}:{token:string}) {
  const [view,setView]=useState<BrainView|null>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0);
  const [search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null),[state,setState]=useState('FL');
  useEffect(()=>{const controller=new AbortController();setError(false);void fetch('/api/lead-engine/brain',{signal:controller.signal,headers:{Authorization:`Bearer ${token}`},cache:'no-store'}).then(async response=>{if(!response.ok)throw Error('unavailable');return response.json() as Promise<BrainView>;}).then(setView).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[token,attempt]);
  if(error)return <div className={styles.notice} role="alert">We could not load the workflows. <button onClick={()=>setAttempt(value=>value+1)}>Try again</button></div>;
  if(!view)return <p role="status">Loading industry workflows…</p>;
  const current=WORKFLOW_NICHES.find(item=>item.id===selected);
  const filtered=WORKFLOW_NICHES.filter(item=>`${item.title} ${item.id} ${nicheReviewIds(item).flatMap(id=>view.industries.find(industry=>industry.key===id)?.aliases??[]).join(' ')}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <section className={styles.workspace} aria-label="Industry workflows">
    <header className={styles.header}><div><span className={styles.kicker}>OWNER CELL / SOURCING GUIDE</span><h2>How we find the right contacts.</h2><p>Choose the business. Pick the state. See where the search starts and why.</p></div><span className={styles.admin}><ShieldCheck size={15}/> Admin only</span></header>
    {current ? <><button className={styles.back} onClick={()=>setSelected(null)}><ArrowLeft size={16}/> All niches</button><NicheDetail niche={current} state={state} setState={setState} view={view}/></> : <>
      <div className={styles.listHeading}><div><h3>Choose a niche</h3><p>{WORKFLOW_NICHES.length} business niches · State-specific sources live inside each niche</p></div><label><Search size={18}/><input aria-label="Search niches" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search a business type…"/></label></div>
      <div className={styles.catalog}>{filtered.map(item=><button key={item.id} className={styles.nicheCard} onClick={()=>setSelected(item.id)} aria-label={`Open ${item.title}`}><strong>{item.title}</strong><p>{item.rationale}</p><span>See the approach <ArrowRight size={16}/></span></button>)}</div>
      {!filtered.length&&<p role="status">No niches match your search.</p>}
      <details className={styles.audit}><summary>Cross-niche source research <ChevronDown size={17}/></summary><p>These studies support multiple niches. They are not separate business types.</p>{CROSS_NICHE_REVIEWS.map(id=>view.workflowReviews[id]&&<ReviewAudit key={id} review={view.workflowReviews[id]}/>)}</details>
    </>}
  </section>;
}
function NicheDetail({niche,state,setState,view}:{niche:WorkflowNiche;state:string;setState:(value:string)=>void;view:BrainView}) {
  const key=nicheReview(niche,state),industry=view.industries.find(item=>item.key===key),route=industry?.effectiveRoutes?.[state];
  const review=view.workflowReviews[key];
  const flow=toolFlow(route, niche.id);
  const variants=nicheReviewIds(niche);
  const [stateSearch,setStateSearch]=useState('');
  const visibleStates=matchingStates(stateSearch);
  return <article className={styles.detail}>
    <header className={styles.detailHeader}><div><span className={styles.kicker}>THE NICHE</span><h3>{niche.title}</h3></div><label className={styles.statePicker}><MapPin size={18}/><span>Where are we looking?<select aria-label="Workflow state" value={state} onChange={event=>setState(event.target.value)}>{STATE_CODES.map(code=><option key={code} value={code}>{stateName(code)}</option>)}</select></span></label></header>
    <section className={styles.answer} aria-label="Selected approach"><div className={styles.answerTop}><span className={styles.kicker}>CURRENT APPROACH IN {stateName(state).toUpperCase()}</span><span className={styles.status}>{route?.blocked?'Cannot run here':route?.legacy?'Existing code · unvalidated branch':route?.fallback?'Fallback route':'Configured route'}</span></div><h4>{method(route)}</h4><p className={styles.rationale}>{niche.rationale}</p><div className={styles.reason}><strong>Why this method here?</strong><p>{flow.reason}</p></div><div className={styles.sourceLine}><span>Starting source</span><strong>{route?.recipe==='A'?'Published business listings (Google Maps)':sourceName(route?.source)}</strong></div>{niche.scope?.[state]&&<p className={styles.scope}><strong>Coverage limit:</strong> {niche.scope[state]}</p>}{route?.blocked&&<details className={styles.blockers}><summary>See what blocks the current quote</summary><ul>{route.blockers?.map((text,i)=><li key={i}>{text}</li>)}</ul></details>}</section>
    <div className={styles.explanationGrid}>
      <LeadToolDiagram flow={flow} title={niche.title}/>
      <aside className={styles.stateAside} aria-label="All US states"><h4>All 50 states + D.C.</h4><p>Every niche is listed nationwide. Select a state to see its method, tools and any missing connection.</p>
        <label className={styles.stateSearch}><Search size={15}/><input aria-label="Search states" placeholder="State name or code…" value={stateSearch} onChange={event=>setStateSearch(event.target.value)}/></label>
        <div className={styles.stateCount}><span role="status">{visibleStates.length} of 51 jurisdictions</span>{stateSearch&&<button type="button" onClick={()=>setStateSearch('')}>Show all</button>}</div>
        <div className={styles.stateOptions} role="group" aria-label="State routes">{visibleStates.map(code=>{const variant=view.industries.find(item=>item.key===nicheReview(niche,code));const candidate=variant?.effectiveRoutes?.[code];return <button key={code} type="button" aria-label={`Inspect ${stateName(code)}`} aria-pressed={code===state} onClick={()=>setState(code)}><span>{stateName(code)}</span><small>{method(candidate)}</small><em data-blocked={candidate?.blocked??false}>{stateRouteStatus(candidate)}</em><ArrowRight size={14}/></button>;})}</div>
        {!visibleStates.length&&<p className={styles.note}>No states match. Clear the search to see the whole country.</p>}
        <p className={styles.note}>All states stay visible, including blocked routes. City-only sources keep their coverage limits.</p><div className={styles.pending}><strong>Selected: {stateName(state)}</strong><p>{stateRouteStatus(route)}. A configured route is not proof of a successful phone result.</p></div>
      </aside>
    </div>
    <details className={styles.audit}><summary>Compare the four methods <ChevronDown size={17}/></summary><p>These are internal route types, not four independently measured promises of quality.</p><div className={styles.methods}>{Object.entries(METHOD_NAMES).map(([code,name])=><div key={code} data-selected={route?.recipe===code}><strong>{name} <small>({code})</small></strong><p>{code==='A'?'Starts with businesses that publish listings. Used where this is the connected route or a permitted fallback.':code==='B'?'An older identity-enrichment path. It needs replacement and validation for published business contacts.':code==='C'?'Starts with a mapped register that supplies phone numbers. Does not add a Maps comparison.':'Starts with a mapped register and compares its numbers with business listings. A difference is not ownership proof.'}</p><span>{methodComparison(code,route)}</span></div>)}</div></details>
    <details className={styles.audit}><summary>Evidence & technical details <ChevronDown size={17}/></summary><p>This is the underlying audit, including old source identifiers and proposed steps. Opening a guide does not start a job or change the runner.</p><dl className={styles.facts}><div><dt>Inspected job identifier</dt><dd>{key}</dd></div><div><dt>Current internal method</dt><dd>{route?.recipe??'Unavailable'}</dd></div><div><dt>Mapped source</dt><dd>{route?.source??'None'}</dd></div></dl>{industry&&<details className={styles.nested}><summary>Historical benchmark, not a new result</summary><p>{Math.round(industry.expectedClean*100)}% configured expectation. {benchmarkLabel(industry.measuredBy,industry.n)}. No new owner-contact yield or cost per confirmed owner was measured.</p></details>}{review&&<ReviewAudit key={key} review={review}/>}<details className={styles.nested}><summary>Other source reviews in this niche</summary>{variants.filter(id=>id!==key).map(id=>view.workflowReviews[id]&&<ReviewAudit key={id} review={view.workflowReviews[id]}/>) }{variants.length===1&&<p>No additional state-specific review is recorded.</p>}</details></details>
  </article>;
}
function ReviewAudit({review}:{review:IndustryWorkflow}) {return <details className={styles.nested}><summary>{review.title}</summary><p>{review.implementation.summary}</p><h5>What was tested</h5><p>{review.measurement.kind.replaceAll('_',' ')} · n = {review.measurement.sampleSize} · {review.measurement.observedAt} · {review.measurement.verifiedPhones} verified phones</p><p>{review.measurement.result}</p><p>Measured cost per confirmed owner: not measured. {review.cost.note}</p><h5>Original decision steps</h5>{review.workflow.map(node=><details className={styles.nodeAudit} key={node.id}><summary>{node.label}</summary><p>{node.detail}</p><ul>{review.edges.filter(edge=>edge.from===node.id).map((edge,index)=><li key={index}><strong>{edge.label||'Next'}:</strong> {review.workflow.find(item=>item.id===edge.to)?.label}</li>)}</ul></details>)}<h5>Source evidence</h5>{review.sources.map((source,index)=><div className={styles.sourceAudit} key={index}><strong>{source.label}</strong><p>{source.scope}</p><small>{source.evidence} · {source.status}</small><code>{source.reference}</code></div>)}<h5>Known failures</h5>{review.failures.map((failure,index)=><p key={index}><strong>{failure.risk}:</strong> {failure.mitigation} ({failure.status})</p>)}<h5>Experiment history</h5>{review.iterations.map((iteration,index)=><div key={index}><p><strong>{iteration.hypothesis}</strong></p><p>Test: {iteration.test}</p><p>Observed: {iteration.observed}</p><p>Adjustment: {iteration.change}</p></div>)}<h5>Next measurement</h5><p>{review.nextMeasurement}</p></details>;}
