'use client';
import {useState} from 'react';
import type {PilotView} from '@/lib/live-pilot';
import {parseVerificationRate} from '@/lib/run-verification-rate';
import styles from '../pilot/NativeRunPanel.module.css';
export function VerificationRateSetup({token,onSaved,disabled}:{token:string;onSaved:(view:PilotView)=>void;disabled:boolean}){
 const [rate,setRate]=useState(''),[source,setSource]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){if(busy||disabled)return;setError('');try{parseVerificationRate({rateUsd:rate,source,confirmed});}catch(e){setError(e instanceof Error?e.message:'Check the rate.');return;}setBusy(true);try{const r=await fetch('/api/lead-engine/verification-rate',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({rateUsd:rate,source,confirmed})});const b=await r.json();if(!r.ok)throw Error(b.error??'The rate could not be saved.');onSaved(b);}catch(e){setError(e instanceof Error?e.message:'Could not save the rate.');}finally{setBusy(false);}}
 return <details className={styles.details}><summary>Set the verification account rate</summary><p>Copy the current Phone Verification price from your BatchData account or invoice. Saving the rate does not run a check or add funds.</p><div className={styles.controls}><label>USD per phone<input aria-label="Verification price per phone" inputMode="decimal" placeholder="Price from your account" value={rate} onChange={e=>{setRate(e.target.value);setConfirmed(false);}}/></label><label>Price source<input aria-label="Verification price source" placeholder="Account pricing page or invoice reference" maxLength={300} value={source} onChange={e=>{setSource(e.target.value);setConfirmed(false);}}/></label></div><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked this rate in the account. Keep the existing $25 total limit.</label><p><button disabled={busy||disabled||!confirmed} onClick={()=>void save()}>{busy?'Saving…':'Save verified rate'}</button></p>{error&&<p role="alert" className={styles.error}>{error}</p>}</details>;
}
