"use client";
import {useEffect,useRef,useState} from 'react';import {Mic,RotateCcw,Square,Trash2,Upload} from 'lucide-react';import {MAX_SAMPLE_BYTES,audioTypes,audioFileType} from '@/lib/caller-audio';import {sampleClock,waveformPeaks} from '@/lib/caller-voice-capture';import {CallerAudioPlayer} from './CallerAudioPlayer';import styles from './CallerVoiceCapture.module.css';
export function CallerAudioRecorder({onSample,onRecordingChange,enabled=true,allowUpload=false}:{onSample?(sample:File|null,duration?:number):void;onRecordingChange?(active:boolean):void;enabled?:boolean;allowUpload?:boolean}){
 const [state,setState]=useState<'idle'|'requesting'|'recording'>('idle'),[seconds,setSeconds]=useState(0),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[error,setError]=useState(''),[duration,setDuration]=useState(0),[peaks,setPeaks]=useState<number[]>([]),[reading,setReading]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),epoch=useRef(0),sampleEpoch=useRef(0),locked=useRef(false),alive=useRef(true),input=useRef<HTMLInputElement|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),urlRef=useRef(''),callback=useRef(onSample),recordCallback=useRef(onRecordingChange);callback.current=onSample;recordCallback.current=onRecordingChange;
 function release(){stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;}
 function cancel(){epoch.current++;if(recorder.current?.state==='recording')recorder.current.stop();recorder.current=null;release();locked.current=false;setState('idle');recordCallback.current?.(false);}
 function discard(){cancel();sampleEpoch.current++;if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current='';setUrl('');setFile(null);setDuration(0);setPeaks([]);setSeconds(0);setError('');callback.current?.(null,0);}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;sampleEpoch.current++;if(recorder.current?.state==='recording')recorder.current.stop();release();if(urlRef.current)URL.revokeObjectURL(urlRef.current);};},[]);
 useEffect(()=>{if(!enabled&&(recorder.current||locked.current))cancel();},[enabled]);
 async function accept(sample:File,measured=0){const turn=++sampleEpoch.current;if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(sample);setFile(sample);setUrl(urlRef.current);setDuration(measured);setPeaks([]);callback.current?.(sample,measured);let context:AudioContext|null=null;
  try{context=new AudioContext();const audio=await context.decodeAudioData(await sample.arrayBuffer());if(!alive.current||sampleEpoch.current!==turn)return;setDuration(audio.duration);setPeaks(waveformPeaks(audio.getChannelData(0)));callback.current?.(sample,audio.duration);}catch{/* Some valid browser recordings cannot be decoded here; playback and measured duration remain available. */}finally{if(context)void context.close().catch(()=>{});}
 }
 async function upload(sample:File){const turn=epoch.current;setReading(true);setError('');try{if(sample.size>MAX_SAMPLE_BYTES||sample.size<1024||!audioTypes.includes(sample.type.split(';')[0])||!audioFileType(new Uint8Array(await sample.slice(0,16).arrayBuffer())))throw new Error('Choose a supported MP3, WAV, WebM, OGG or M4A file between 1 KB and 3 MB. Your previous recording is kept.');if(!alive.current||turn!==epoch.current)return;await accept(sample);}catch(e){if(alive.current&&turn===epoch.current)setError(e instanceof Error?e.message:'This file could not be opened. Your previous recording is kept.');}finally{if(alive.current)setReading(false);}}
 async function start(){if(locked.current||!enabled||reading)return;cancel();locked.current=true;const turn=epoch.current;setState('requesting');recordCallback.current?.(true);setSeconds(0);setError('');
  try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error('Microphone recording needs a supported browser on HTTPS.');const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!alive.current||turn!==epoch.current){media.getTracks().forEach(track=>track.stop());return;}stream.current=media;
   const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(value=>MediaRecorder.isTypeSupported(value));const device=new MediaRecorder(media,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:128000});recorder.current=device;const chunks:BlobPart[]=[];let bytes=0;const began=Date.now();
   device.ondataavailable=event=>{if(event.data.size){bytes+=event.data.size;chunks.push(event.data);if(bytes>MAX_SAMPLE_BYTES&&device.state==='recording')device.stop();}};
   device.onstop=()=>{if(!alive.current||turn!==epoch.current)return;release();recorder.current=null;locked.current=false;setState('idle');recordCallback.current?.(false);if(bytes>MAX_SAMPLE_BYTES){setError('This sample exceeded 3 MB. Record a shorter sample. Your previous recording is kept.');return;}const blob=new Blob(chunks,{type:device.mimeType||'audio/webm'});if(blob.size<1024){setError('No usable audio was captured. Record a longer sample.');return;}const extension=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';void accept(new File([blob],`nbc-voice-sample.${extension}`,{type:blob.type}),(Date.now()-began)/1000);};
   device.onerror=()=>{if(turn===epoch.current&&alive.current){cancel();setError('Recording stopped unexpectedly. Please try again.');}};device.start(1000);setState('recording');timer.current=setInterval(()=>{const elapsed=Math.floor((Date.now()-began)/1000);if(alive.current)setSeconds(elapsed);if(elapsed>=120&&device.state==='recording')device.stop();},250);
  }catch(failure){if(alive.current&&turn===epoch.current){release();locked.current=false;setState('idle');recordCallback.current?.(false);setError(failure instanceof DOMException&&failure.name==='NotAllowedError'?'Microphone permission was denied. Allow it in your browser and try again.':failure instanceof Error?failure.message:'The microphone could not start.');}}
 }
 return <div className={styles.recorder}><div className={styles.recordTop}><span className={styles.micMark} data-recording={state==='recording'}><Mic size={23}/></span><div><strong>{state==='recording'?'Keep it natural. We’re listening.':state==='requesting'?'Allow microphone access…':file?'Your sample is ready to review.':'Let’s capture your voice.'}</strong><p>Local recording · up to 2 minutes</p></div><span className={styles.recordTime}>{state==='recording'?sampleClock(seconds):file?sampleClock(duration):'0:00'}</span></div>{state==='recording'&&<div className={styles.progress}><span style={{width:`${Math.min(100,seconds/120*100)}%`}}/></div>}<div className={styles.actions}>{state==='idle'?<button className={styles.recordButton} onClick={()=>void start()} disabled={!enabled||reading}>{file?<RotateCcw size={16}/>:<Mic size={16}/>} {file?'Record again':'Record audio'}</button>:<><button className={styles.recordButton} disabled={state!=='recording'} onClick={()=>{if(recorder.current?.state==='recording')recorder.current.stop();}}><Square size={15}/>Stop recording</button><button className={styles.secondary} onClick={cancel}>Cancel recording</button></>}{allowUpload&&state==='idle'&&<><input ref={input} className={styles.hiddenInput} type="file" aria-label="Upload voice recording" accept="audio/mpeg,audio/wav,audio/webm,audio/ogg,audio/mp4,.m4a" disabled={!enabled||reading} onChange={e=>{const sample=e.target.files?.[0];e.target.value='';if(sample)void upload(sample);}}/><button className={styles.secondary} disabled={!enabled||reading} onClick={()=>input.current?.click()}><Upload size={16}/>{reading?'Reading audio…':'Upload audio'}</button></>}</div>{url&&file&&state==='idle'&&<><CallerAudioPlayer url={url} file={file} duration={duration} peaks={peaks} enabled={enabled&&!reading}/><button className={styles.discard} disabled={!enabled||reading} onClick={discard}><Trash2 size={14}/>Discard audio</button></>}<p className={styles.privacy}>{file?'Your sample stays in this tab until you submit. Save a copy before leaving.':allowUpload?'MP3, WAV, WebM, OGG or M4A · up to 3 MB. Nothing uploads until you create the voice.':'Only your microphone is captured. This does not record the other end of a phone call.'}</p>{error&&<p className={styles.error} role="alert">{error}</p>}</div>;
}
