"use client";
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import type {CSSProperties,PointerEvent as ReactPointerEvent} from 'react';
import {GripVertical,Plus,SlidersHorizontal,X,Check,ArrowUp,ArrowDown,MoveDiagonal2} from 'lucide-react';
import type {CallerLead} from '@/lib/caller-crm';
import type {CallSession} from '@/lib/caller-types';
import type {CallerPipeline} from '@/lib/caller-workbench';
import {widgetCatalog,defaultWidgets,reorder} from '@/lib/caller-dashboard';
import type {DashboardWidget,AnalyticsConfig} from '@/lib/caller-dashboard';
import {useWorkspaceAccess} from '@/components/workspace/WorkspaceAccess';
import {useCallerView} from './CallerDashboardLayout';
import {useCallerDrag} from './CallerDrag';
import {CallerChart} from './CallerCharts';
import {placeItem} from '@/lib/caller-drag';
import styles from './CallerCanvas.module.css';
export function CallerAnalytics({leads,sessions,demo,pipeline}:{leads:CallerLead[];sessions:CallSession[];demo:boolean;pipeline:CallerPipeline|null}){
 const {token}=useWorkspaceAccess(),store=useCallerView(token,demo,'analytics');const [days,setDays]=useState(14),[channel,setChannel]=useState('all'),[editing,setEditing]=useState(false),[widgets,setWidgets]=useState<DashboardWidget[]>(defaultWidgets),[error,setError]=useState(''),[message,setMessage]=useState('');
 const root=useRef<HTMLElement|null>(null),grid=useRef<HTMLDivElement|null>(null),resizeCleanup=useRef<()=>void>(()=>{}),current=useRef({token,demo}),mounted=useRef(true);current.current={token,demo};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;resizeCleanup.current();};},[]);
 useEffect(()=>{setEditing(false);setError('');setMessage('');resizeCleanup.current();},[token,demo]);
 useEffect(()=>{if(!editing)setWidgets((store.view.config as AnalyticsConfig).widgets);},[store.view,editing]);
 const [preset,setPreset]=useState(6),[resizing,setResizing]=useState<{id:string;width:number;height:number}|null>(null);
 const makeWidget=(id:DashboardWidget['id']):DashboardWidget=>({id,cols:widgetCatalog.find(w=>w.id===id)?.kind==='number'?3:preset,rows:widgetCatalog.find(w=>w.id===id)?.kind==='number'?2:5});
 function placed(previous:DashboardWidget[],source:string,target:string,edge:'before'|'after'){
  const id=source.replace('add:','') as DashboardWidget['id'];const item=previous.find(w=>w.id===id)||makeWidget(id);return placeItem(previous,item,previous.find(w=>w.id===target)||null,edge);
 }
 const drag=useCallerDrag(root,(source,target,edge)=>{if(editing&&!store.busy)setWidgets(previous=>placed(previous,source,target,edge));},true);
 useEffect(()=>{drag.cancel();},[editing,demo,token]);
 const visible=drag.drag?.target?placed(widgets,drag.drag.source,drag.drag.target,drag.drag.edge):widgets;
 const positions=useRef(new Map<string,DOMRect>());
 useLayoutEffect(()=>{const next=new Map<string,DOMRect>();grid.current?.querySelectorAll<HTMLElement>('[data-widget]').forEach(node=>{node.getAnimations().forEach(a=>a.cancel());const id=node.dataset.widget!,rect=node.getBoundingClientRect();next.set(id,rect);const old=positions.current.get(id);if(old&&drag.drag&&!resizing&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const x=old.left-rect.left,y=old.top-rect.top;if(x||y)node.animate([{transform:`translate(${x}px,${y}px)`},{transform:'translate(0,0)'}],{duration:180,easing:'cubic-bezier(.2,.8,.2,1)'});}});positions.current=next;},[visible.map(w=>w.id).join(','),resizing]);
 const dayKey=new Date().toDateString();const dates=useMemo(()=>{const today=new Date();today.setHours(0,0,0,0);return Array.from({length:days},(_,i)=>{const day=new Date(today);day.setDate(day.getDate()-days+1+i);return day;});},[days,dayKey]);
 const filtered=useMemo(()=>{const end=new Date(dates.at(-1)!);end.setDate(end.getDate()+1);return sessions.filter(s=>Date.parse(s.created_at)>=dates[0].getTime()&&Date.parse(s.created_at)<end.getTime()&&(channel==='all'||s.channel===channel));},[sessions,dates,channel]);
 const chartData=useMemo(()=>({leads,sessions:filtered,dates,pipeline}),[leads,filtered,dates,pipeline]);
 function size(id:string,cols:number,rows:number){setWidgets(previous=>previous.map(w=>w.id===id?{...w,cols:Math.max(3,Math.min(12,cols)),rows:Math.max(2,Math.min(6,rows))}:w));}
 function resize(e:ReactPointerEvent<HTMLButtonElement>,widget:DashboardWidget){e.preventDefault();if(e.button!==0||!editing||store.busy)return;resizeCleanup.current();const handle=e.currentTarget,card=handle.closest('article')!,rect=card.getBoundingClientRect(),x=e.clientX,y=e.clientY,step=((grid.current?.clientWidth||1000)+16)/12,pointerId=e.pointerId;let width=rect.width,height=rect.height;
  try{handle.setPointerCapture(pointerId);}catch{}setResizing({id:widget.id,width,height});
  const move=(event:PointerEvent)=>{if(event.pointerId!==pointerId)return;width=Math.max(step*3-16,Math.min(step*12-16,rect.width+event.clientX-x));height=Math.max(136,Math.min(440,rect.height+event.clientY-y));setResizing({id:widget.id,width,height});};
  const stop=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',cancel);document.removeEventListener('keydown',key);window.removeEventListener('blur',cancel);try{handle.releasePointerCapture(pointerId);}catch{}setResizing(null);resizeCleanup.current=()=>{};};
  const finish=(event:PointerEvent)=>{if(event.pointerId!==pointerId)return;size(widget.id,Math.round((width+16)/step),Math.round((height+16)/76));stop();};const cancel=()=>stop();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')cancel();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',cancel);document.addEventListener('keydown',key);window.addEventListener('blur',cancel);resizeCleanup.current=cancel;
 }
 async function save(){setError('');try{await store.save({widgets});if(mounted.current&&current.current.token===token&&current.current.demo===demo){setEditing(false);setMessage('Your dashboard layout is saved.');}}catch(e){if(mounted.current&&current.current.token===token&&current.current.demo===demo)setError(e instanceof Error?e.message:'Layout could not save.');}}
 return <section ref={root} className={styles.dashboard} aria-label="Caller analytics"><header className={styles.header}><div><span className={styles.eyebrow}>NBC / INTELLIGENCE</span><h2>Your numbers.<br/><em>Your perspective.</em></h2><p>{demo?'DEMO · Illustrative activity':'Your saved activity'} <span> / </span> {days}-day view</p></div><div className={styles.controls}><label>Period<select aria-label="Analytics period" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={14}>Last 14 days</option><option value={30}>Last 30 days</option></select></label><label>Source<select aria-label="Analytics source" value={channel} onChange={e=>setChannel(e.target.value)}><option value="all">All conversations</option><option value="phone">Phone calls</option><option value="web">Browser tests</option></select></label><button className={styles.customize} disabled={store.loading||Boolean(store.error)||store.busy} onClick={()=>{setEditing(value=>!value);setMessage('');setError('');}}><SlidersHorizontal size={16}/>{editing?'Close customization':'Customize'}</button></div></header>
 {(error||store.error)&&<div className={styles.error} role="alert">{error||store.error}<button disabled={store.busy} onClick={()=>void store.refresh().then(()=>{setEditing(false);setError('');}).catch(e=>setError(e.message))}>Reload saved layout</button></div>}{message&&<p className={styles.notice} role="status">{message}</p>}
 {editing&&<section className={styles.gallery} aria-label="Widget gallery"><header><div><h3>Make room for what matters.</h3><p>Drag a preview onto your canvas, or add it and move it into place.</p></div><div className={styles.editActions}><button disabled={store.busy} onClick={()=>setWidgets(defaultWidgets.map(w=>({...w})))}>Reset to default</button><button disabled={store.busy} onClick={()=>setEditing(false)}>Cancel</button><button className={styles.save} disabled={store.busy||Boolean(drag.drag)||Boolean(resizing)} onClick={()=>void save()}><Check size={15}/>{store.busy?'Saving…':'Save layout'}</button></div></header><div className={styles.sizePicker} aria-label="Chart preview size">{[[3,'Small'],[6,'Medium'],[12,'Wide']].map(([cols,label])=><button key={cols} aria-pressed={preset===cols} onClick={()=>setPreset(Number(cols))}>{label}<small>{cols}/12 columns</small></button>)}</div>{['number','chart'].map(group=><div key={group}><h4>{group==='number'?'At a glance · Numbers':'Explore the story · Charts'}</h4><div className={styles.previewGallery}>{widgetCatalog.filter(w=>(w.kind==='number')===(group==='number')).map(w=>{const included=widgets.some(x=>x.id===w.id);return <article key={w.id} data-drag-card className={styles.previewCard} data-size={group==='number'?3:preset}><div className={styles.actualPreview} aria-hidden="true" inert><CallerChart id={w.id} data={chartData}/></div><strong>{w.name}</strong><small>{w.description}</small><div><button disabled={included||store.busy} onClick={()=>{setWidgets(previous=>previous.some(item=>item.id===w.id)?previous:[makeWidget(w.id),...previous]);requestAnimationFrame(()=>grid.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}));}} aria-label={`Add ${w.name}`}>{included?<Check size={14}/>:<Plus size={14}/>} {included?'Added':'Add widget'}</button><button disabled={included||store.busy} className={styles.galleryGrip} aria-label={`Drag ${w.name} onto dashboard`} onPointerDown={e=>drag.start(e,`add:${w.id}`)}><GripVertical size={16}/></button></div></article>;})}</div></div>)}<p className={styles.galleryHint}>Previews use the same {demo?'DEMO':'loaded'} data as your dashboard. Drag near the screen edge to scroll. Arrow keys also move or resize widgets. Changes remain a preview until you save. Live and Demo layouts are separate.</p></section>}
 {store.loading?<div className={styles.loading} role="status">Loading your dashboard…</div>:<div ref={grid} className={styles.grid} data-editing={editing}>{visible.map((w,index)=>{const definition=widgetCatalog.find(c=>c.id===w.id)!;return <article key={w.id} className={styles.widget} data-drag-card data-widget={w.id} data-drop-id={w.id} data-kind={definition.kind} data-resizing={resizing?.id===w.id} data-dragging={drag.drag?.source.replace('add:','')===w.id} data-target={drag.drag?.target===w.id} style={{...(resizing?.id===w.id?{width:resizing.width,height:resizing.height,zIndex:20}:{}),'--cols':w.cols,'--rows':w.rows,'--delay':`${Math.min(index,7)*55}ms`} as CSSProperties}><header><h3>{definition.name}</h3>{editing?<div className={styles.widgetTools}><button aria-label={`Move ${definition.name}`} title="Drag, or use arrow keys to reorder" disabled={store.busy} onPointerDown={e=>drag.start(e,w.id)} onKeyDown={e=>{const delta=['ArrowLeft','ArrowUp'].includes(e.key)?-1:['ArrowRight','ArrowDown'].includes(e.key)?1:0;if(delta){e.preventDefault();setWidgets(previous=>reorder(previous,index,index+delta));}}}><GripVertical size={17}/></button><button aria-label={`Remove ${definition.name}`} disabled={store.busy} onClick={()=>setWidgets(previous=>previous.filter(x=>x.id!==w.id))}><X size={15}/></button></div>:<span className={styles.widgetIndex}>{String(index+1).padStart(2,'0')}</span>}</header><div className={styles.widgetBody}><CallerChart id={w.id} data={chartData}/></div>{editing&&<footer className={styles.resizeTools}><span>{w.cols}/12 wide · {w.rows} high</span><button aria-label={`Narrow ${definition.name}`} disabled={store.busy||w.cols===3} onClick={()=>size(w.id,w.cols-1,w.rows)}>−</button><button aria-label={`Widen ${definition.name}`} disabled={store.busy||w.cols===12} onClick={()=>size(w.id,w.cols+1,w.rows)}>+</button><button className={styles.resizeHandle} aria-label={`Resize ${definition.name}`} title="Drag or use arrow keys. Escape cancels." disabled={store.busy} onPointerDown={e=>resize(e,w)} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();size(w.id,w.cols+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),w.rows+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0));}}}><MoveDiagonal2 size={18}/></button></footer>}</article>;})}{editing&&<div className={styles.dropEnd} data-drop-id="canvas-end">Drop here to add at the end</div>}</div>}
 {!widgets.length&&!store.loading&&<div className={styles.loading}>Your canvas is clear. Open Customize to add your first widget.</div>}<p className={styles.scope}>{demo?'DEMO — illustrative data, not NBC activity. ':''}Activity covers {sessions.length} loaded sessions, filtered by local calendar day and source. Load more in AI Caller → Conversation history for older sessions. CRM widgets cover {leads.length} loaded leads, independently of these filters. Unknown durations excluded. No revenue or sales conversion inferred.</p>{drag.drag&&<div className={styles.dragPreview} style={{left:Math.min(drag.drag.x+14,window.innerWidth-260),top:Math.min(drag.drag.y+14,window.innerHeight-180)}}><strong>{widgetCatalog.find(w=>w.id===drag.drag?.source.replace('add:',''))?.name}</strong><div aria-hidden="true" inert><CallerChart id={drag.drag.source.replace('add:','') as DashboardWidget['id']} data={chartData}/></div><small>Release to place · Esc to cancel</small></div>}<span className={styles.srOnly} role="status">{drag.drag?`Moving ${drag.drag.source}. Release over another widget to reorder. Escape cancels.`:''}</span></section>;
}
