"use client";
import {useEffect,useRef,useState} from 'react';import {ArrowUpRight,Clock3,Mail,MessageSquare,Phone,ShieldOff,X} from 'lucide-react';
import type {CallerLead} from '@/lib/caller-crm';import {bucketFor,isBlocked,callOutcomes} from '@/lib/caller-workbench';import type {LeadActivity,ActivityPage} from '@/lib/caller-workbench';import {salesRequest} from '@/lib/caller-request';import type {LeadStore} from './CallerSalesPanels';import type {PipelineStore} from './CallerPipeline';import {useWorkspaceAccess} from '@/components/workspace/WorkspaceAccess';import styles from './CallerWorkbench.module.css';
export interface NoteDraft{body:string;kind:'note'|'manual_call';outcome:keyof typeof callOutcomes;requestId:string;key:string}
export function CallerLeadDetail({lead,store,pipeline,close,dial,drafts}:{lead:CallerLead;store:LeadStore;pipeline:PipelineStore;close?():void;dial?():void;drafts:Map<string,NoteDraft>}){
 const {user}=useWorkspaceAccess();const [activities,setActivities]=useState<LeadActivity[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[draft,setDraft]=useState<NoteDraft>(drafts.get(lead.id)||{body:'',kind:'note',outcome:'no_answer',requestId:'',key:''}),[bucket,setBucket]=useState(bucketFor(lead,pipeline.pipeline)?.id||''),[blocked,setBlocked]=useState(isBlocked(lead));
 const epoch=useRef(0),alive=useRef(true),lock=useRef(false),selected=useRef(lead.id),heading=useRef<HTMLHeadingElement|null>(null),detailsRequest=useRef<{key:string;id:string}|null>(null);selected.current=lead.id;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;};},[]);
 async function load(next?:string){const id=lead.id,turn=++epoch.current;const params=new URLSearchParams();if(store.demo)params.set('demo','true');if(next)params.set('cursor',next);setLoading(true);try{const result=await salesRequest<ActivityPage>(store.token,`/api/caller/leads/${id}/activity?${params}`);if(!Array.isArray(result.activities))throw new Error('Activity could not load. Retry below.');if(alive.current&&selected.current===id&&turn===epoch.current){setActivities(previous=>next?[...new Map([...previous,...result.activities].map(a=>[a.id,a])).values()]:result.activities);setCursor(result.nextCursor);}}catch(e){if(alive.current&&selected.current===id&&turn===epoch.current)setError(e instanceof Error?e.message:'Activity could not load.');}finally{if(alive.current&&selected.current===id&&turn===epoch.current)setLoading(false);}}
 useEffect(()=>{setActivities([]);setCursor(null);setError('');setMessage('');setDraft(drafts.get(lead.id)||{body:'',kind:'note',outcome:'no_answer',requestId:'',key:''});void load();heading.current?.focus({preventScroll:true});return()=>{epoch.current++;};},[lead.id,store.token,store.demo]);
 useEffect(()=>{setBucket(bucketFor(lead,pipeline.pipeline)?.id||'');setBlocked(isBlocked(lead));},[lead.id,lead.bucket_id,lead.updated_at,pipeline.pipeline?.version]);
 function updateDraft(patch:Partial<NoteDraft>){setDraft(previous=>{const next={...previous,...patch};drafts.set(lead.id,next);return next;});}
 async function saveNote(){if(lock.current)return;lock.current=true;setBusy(true);setError('');const id=lead.id,payload={kind:draft.kind,body:draft.body.trim(),outcome:draft.kind==='manual_call'?draft.outcome:null,demo:store.demo};const key=JSON.stringify(payload),reference=draft.key===key&&draft.requestId?draft.requestId:crypto.randomUUID();const pending={...draft,requestId:reference,key};drafts.set(id,pending);setDraft(pending);try{await salesRequest(store.token,`/api/caller/leads/${id}/activity`,'POST',{...payload,requestId:reference});if(drafts.get(id)?.requestId===reference)drafts.delete(id);if(alive.current&&selected.current===id){setDraft({body:'',kind:draft.kind,outcome:draft.outcome,requestId:'',key:''});setMessage('Activity saved.');await load();}await store.refresh();}catch(e){if(alive.current&&selected.current===id)setError(e instanceof Error?e.message:'Your note could not save. Retry the same note.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function saveDetails(){if(lock.current)return;lock.current=true;setBusy(true);setError('');const id=lead.id,payload={bucketId:bucket,doNotCall:blocked,updatedAt:lead.updated_at,demo:store.demo},key=JSON.stringify([id,payload]);if(detailsRequest.current?.key!==key)detailsRequest.current={key,id:crypto.randomUUID()};try{await salesRequest(store.token,`/api/caller/leads/${id}/details`,'PATCH',{...payload,requestId:detailsRequest.current.id});await store.refresh();if(alive.current&&selected.current===id){setMessage('Lead updated.');await load();}}catch(e){if(alive.current&&selected.current===id)setError(e instanceof Error?e.message:'The lead could not be updated.');}finally{lock.current=false;if(alive.current)setBusy(false);}}
 return <aside className={styles.leadDetail} aria-label="Lead details" onKeyDown={e=>{if(e.key==='Escape'&&close){e.preventDefault();close();}}}><header className={styles.detailHead}><div><span className={styles.eyebrow}>{store.demo?'DEMO LEAD':'LEAD DETAILS'}</span><h3 ref={heading} tabIndex={-1}>{lead.name}</h3><p>{lead.company||'Individual contact'}</p></div>{close&&<button className={styles.iconButton} onClick={close} aria-label="Close lead details"><X size={19}/></button>}</header>
 <div className={styles.contactBlock}><span><Phone size={14}/>{lead.phone}</span>{lead.email&&<span><Mail size={14}/>{lead.email}</span>}<div className={styles.contactMeta}><span>Source<strong>{lead.source}</strong></span><span>Added<strong>{new Date(lead.created_at).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</strong></span></div>{dial&&<button className={styles.secondary} disabled={blocked||busy} onClick={dial}>Open in dialer<ArrowUpRight size={14}/></button>}</div>
 <div className={styles.detailSection}><label>Pipeline stage<select aria-label="Lead pipeline stage" value={bucket} disabled={busy||!pipeline.pipeline} onChange={e=>setBucket(e.target.value)}>{pipeline.pipeline?.buckets.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className={styles.checkLabel}><input type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)} disabled={busy}/><ShieldOff size={14}/>Do not call</label><button className={styles.secondary} disabled={busy||!bucket||(bucket===bucketFor(lead,pipeline.pipeline)?.id&&blocked===isBlocked(lead))} onClick={()=>void saveDetails()}>Save lead changes</button></div>
 <div className={styles.detailSection}><div className={styles.composerTabs}><button aria-pressed={draft.kind==='note'} disabled={busy} onClick={()=>updateDraft({kind:'note'})}><MessageSquare size={14}/>Add note</button><button aria-pressed={draft.kind==='manual_call'} disabled={busy} onClick={()=>updateDraft({kind:'manual_call'})}><Phone size={14}/>Log call</button></div>{draft.kind==='manual_call'&&<><label>Call outcome<select aria-label="Call outcome" disabled={busy} value={draft.outcome} onChange={e=>updateDraft({outcome:e.target.value as NoteDraft['outcome']})}>{Object.entries(callOutcomes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p className={styles.caption}>Record an outcome manually. This does not place a call.</p></>}<label className={styles.noteLabel}>{draft.kind==='note'?'Your note':'Call notes (optional)'}<textarea aria-label="Activity note" maxLength={4000} rows={4} value={draft.body} disabled={busy} onChange={e=>updateDraft({body:e.target.value})} placeholder={draft.kind==='note'?'Add context for your next conversation…':'Called today. No answer — try tomorrow afternoon.'}/></label><div className={styles.composerFooter}><span>Posting as <strong>{user?.name}</strong></span><button className={styles.primary} disabled={busy||draft.kind==='note'&&!draft.body.trim()} onClick={()=>void saveNote()}>{busy?'Saving…':draft.kind==='note'?'Save note':'Save call log'}</button></div></div>
 {error&&<div className={styles.error} role="alert">{error}<button className={styles.textButton} disabled={busy||loading} onClick={()=>{setError('');void load();void store.refresh().catch(()=>setError('Your lead could not refresh. Retry.'));}}>Refresh lead & activity</button></div>}{message&&<p className={styles.success} role="status">{message}</p>}
 <div className={styles.detailSection}><header className={styles.timelineHead}><h4>Activity</h4><button className={styles.textButton} disabled={loading||busy} onClick={()=>void load()}>Refresh</button></header>{loading&&!activities.length?<p role="status" className={styles.caption}>Loading activity…</p>:!activities.length?<p className={styles.emptyActivity}>No activity yet. Add a note or log your latest call.</p>:<div className={styles.timeline}>{activities.map(entry=><article key={entry.id}><span className={styles.timelineIcon}>{entry.kind==='note'?<MessageSquare size={13}/>:entry.kind==='manual_call'?<Phone size={13}/>:<ArrowUpRight size={13}/>}</span><div><div className={styles.activityTitle}><strong>{entry.kind==='note'?'Note':entry.kind==='manual_call'?callOutcomes[entry.outcome!]||'Call logged':'Lead updated'}</strong><time dateTime={entry.created_at} title={new Date(entry.created_at).toLocaleString('en-US')}>{new Date(entry.created_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></div><span className={styles.author}>{entry.author_name}{entry.kind==='manual_call'?' · Manually logged':''}</span>{entry.body&&<p>{entry.body}</p>}</div></article>)}</div>}{cursor&&<button className={styles.secondary} disabled={loading} onClick={()=>void load(cursor)}>Load older activity</button>}{lead.notes&&<details className={styles.legacyNotes}><summary>Earlier lead context</summary><p>{lead.notes}</p><small>Saved before the activity timeline. Original author and entry dates are unavailable.</small></details>}<span className={styles.timeHint}><Clock3 size={12}/>Times shown in your local timezone</span></div></aside>;
}
