"use client";
import {memo,useEffect,useId,useState} from 'react';
import type {CSSProperties,PointerEvent as ReactPointerEvent,MouseEvent as ReactMouseEvent} from 'react';
import {useCallerChartTooltip} from './CallerChartTooltip';
import type {CallSession} from '@/lib/caller-types';
import type {CallerLead} from '@/lib/caller-crm';
import type {CallerPipeline} from '@/lib/caller-workbench';
import {bucketFor,bucketHex} from '@/lib/caller-workbench';
import {leadStages,stageLabel} from '@/lib/caller-crm';
import {smoothPath} from '@/lib/caller-dashboard';
import type {WidgetId} from '@/lib/caller-dashboard';
import styles from './CallerCanvas.module.css';
export interface ChartData{leads:CallerLead[];sessions:CallSession[];dates:Date[];pipeline:CallerPipeline|null}
export function AnimatedNumber({value,digits=0,suffix=''}:{value:number;digits?:number;suffix?:string}){const [shown,setShown]=useState(value);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(value);return;}let frame=0;const start=performance.now();const tick=(time:number)=>{const progress=Math.min(1,(time-start)/650);setShown(value*(1-Math.pow(1-progress,3)));if(progress<1)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);return <strong aria-label={value.toFixed(digits)+suffix}>{shown.toFixed(digits)}{suffix}</strong>;}
function Curve({values,labels,unit,summary='sum',gold=false}:{values:number[];labels:string[];unit:string;summary?:'sum'|'last'|'none';gold?:boolean}){const uid=useId().replaceAll(':',''),[point,setPoint]=useState<number|null>(null),max=Math.max(1,...values),path=smoothPath(values);const selected=point!==null&&point<values.length?point:null,tooltip=useCallerChartTooltip();const detail=(i:number)=>({label:labels[i],value:`${values[i].toFixed(unit==='min'?1:0)} ${unit}`,note:summary==='last'?'Cumulative within the selected period':'Selected period · selected source'});function hover(event:ReactPointerEvent<SVGSVGElement>|ReactMouseEvent<SVGSVGElement>){const svg=event.currentTarget,matrix=svg.getScreenCTM();if(!matrix||!values.length)return;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const local=point.matrixTransform(matrix.inverse()),i=Math.max(0,Math.min(values.length-1,Math.round((local.x-38)/680*(values.length-1))));setPoint(i);tooltip.show(detail(i),event.clientX,event.clientY,svg);}
 return <div className={styles.interactiveCurve} style={gold?{'--neon':'var(--brand-gold,#ffbb24)'} as CSSProperties:undefined}><div className={styles.chartReadout}>{selected===null?<><b>{summary==='none'?'Daily':(summary==='last'?(values.at(-1)||0):values.reduce((a,b)=>a+b,0)).toFixed(unit==='min'?1:0)}</b><span>{unit} in this period</span></>:<><b>{values[selected].toFixed(unit==='min'?1:0)}</b><span>{unit} · {labels[selected]}</span></>}</div><svg className={styles.curve} onPointerMove={hover} onPointerLeave={()=>{setPoint(null);tooltip.hide();}} onClick={hover} viewBox="0 0 740 215" role="img" aria-label={`Daily ${unit}: ${values.map(v=>Number(v.toFixed(1))).join(', ')}`}><defs><linearGradient id={uid} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--neon)" stopOpacity=".3"/><stop offset="1" stopColor="var(--neon)" stopOpacity="0"/></linearGradient></defs>{[0,.5,1].map(n=><g key={n}><line x1="38" x2="718" y1={180-n*170} y2={180-n*170}/><text x="4" y={184-n*170}>{Number((max*n).toFixed(unit==='min'?1:0))}</text></g>)}<g transform="translate(38 10)">{selected!==null&&<line className={styles.hoverGuide} x1={selected*680/Math.max(1,values.length-1)} x2={selected*680/Math.max(1,values.length-1)} y1={0} y2={170}/>}<path d={`${path} L 680 170 L 0 170 Z`} fill={`url(#${uid})`}/><path d={path} className={styles.curveGlow}/><path d={path} pathLength="1" className={styles.curveLine}/>{values.map((v,i)=><circle key={i} cx={i*680/Math.max(1,values.length-1)} cy={170-v/max*170} r={selected===i?5:2.5} data-active={selected===i} className={styles.curvePoint}><title>{labels[i]}: {v.toFixed(unit==='min'?1:0)} {unit}</title></circle>)}</g><text x="38" y="210">{labels[0]}</text><text x="718" y="210" textAnchor="end">Today</text></svg><div className={styles.days} aria-label="Explore activity by day">{values.map((v,i)=><button key={i} aria-pressed={selected===i} aria-label={`${labels[i]}: ${v.toFixed(unit==='min'?1:0)} ${unit}`} {...tooltip.bind(detail(i))} onPointerEnter={()=>setPoint(i)} onFocus={e=>{setPoint(i);tooltip.focus(detail(i),e);}} onBlur={()=>{setPoint(null);tooltip.hide();}}>{labels[i].split(' ').at(-1)}</button>)}</div>{tooltip.tip}</div>;
}
export const CallerChart=memo(function CallerChart({id,data}:{id:WidgetId;data:ChartData}){
 const tooltip=useCallerChartTooltip();const {leads,sessions,dates,pipeline}=data,completed=sessions.filter(s=>s.status==='completed').length,pending=sessions.filter(s=>['preparing','ready','active','processing'].includes(s.status)).length,known=sessions.filter(s=>s.duration_seconds!==null),minutes=known.reduce((n,s)=>n+s.duration_seconds!,0)/60;
 const numbers={leads:leads.length,conversations:sessions.length,completed,minutes,pending,average:known.length?minutes/known.length:0};
 if(id in numbers)return <div className={styles.number} {...tooltip.bind({label:({leads:'Pipeline leads',conversations:'Conversations',completed:'Completed',minutes:'Talk time',pending:'Pending results',average:'Average duration'} as Record<string,string>)[id],value:id==='average'&&!known.length?'Not available':`${numbers[id as keyof typeof numbers].toFixed(id==='minutes'||id==='average'?1:0)}${id==='minutes'||id==='average'?' min':''}`,note:id==='leads'?'All loaded leads · independent of date/source':id==='average'?`${known.length} sessions with known duration`:'Selected period and source'})}>{id==='average'&&!known.length?<strong aria-label="Average duration unavailable">—</strong>:<AnimatedNumber value={numbers[id as keyof typeof numbers]} digits={id==='minutes'||id==='average'?1:0} suffix={id==='minutes'||id==='average'?'m':''}/>}{['conversations','completed','minutes'].includes(id)&&<svg viewBox="0 0 120 32" aria-hidden="true"><path d={smoothPath(dates.map(day=>sessions.filter(s=>new Date(s.created_at).toDateString()===day.toDateString()&&(id!=='completed'||s.status==='completed')).reduce((n,s)=>n+(id==='minutes'?(s.duration_seconds??0)/60:1),0)),120,26)}/></svg>}<small>{id==='leads'?'Current loaded CRM':id==='average'?`${known.length} sessions with known duration`:'Selected period & source'}</small>{tooltip.tip}</div>;
 if(id==='averageDaily'){const rows=dates.flatMap(day=>{const values=known.filter(s=>new Date(s.created_at).toDateString()===day.toDateString());return values.length?[{label:day.toLocaleDateString('en-US',{month:'short',day:'numeric'}),value:values.reduce((n,s)=>n+s.duration_seconds!,0)/60/values.length}]:[];});const max=Math.max(1,...rows.map(r=>r.value));return <><div className={styles.bars}>{rows.map(r=><div key={r.label} {...tooltip.bind({label:r.label,value:`${r.value.toFixed(1)} min`,note:'Average of known durations; unknowns excluded'})}><span>{r.label}<b>{r.value.toFixed(1)} min</b></span><div><i style={{width:`${r.value/max*100}%`,background:'var(--brand-gold,#ffbb24)'}}/></div></div>)}</div><p className={styles.chartNote}>{rows.length?'Only days with known duration are shown.':'No known durations in this period.'}</p>{tooltip.tip}</>;}
 if(['activity','duration','cumulative','outcomesDaily'].includes(id)){let cumulative=0;const values=dates.map(day=>{const rows=sessions.filter(s=>new Date(s.created_at).toDateString()===day.toDateString());if(id==='cumulative'){cumulative+=rows.length;return cumulative;}if(id==='outcomesDaily')return rows.filter(s=>s.status==='completed').length;if(id==='activity')return rows.length;const known=rows.filter(s=>s.duration_seconds!==null),sum=known.reduce((n,s)=>n+s.duration_seconds!,0)/60;return sum;});return <><Curve values={values} labels={dates.map(d=>d.toLocaleDateString('en-US',{month:'short',day:'numeric'}))} unit={id==='duration'?'min':'conversations'} summary={id==='cumulative'?'last':'sum'} gold={id==='duration'||id==='cumulative'}/></>; }
 if(id==='outcomes'){const rows=[{label:'Completed',n:completed,color:'#729bff'},{label:'Pending',n:pending,color:'#ffbb24'},{label:'Failed / expired',n:sessions.length-completed-pending,color:'#9eacc6'}];let offset=0;return <div className={styles.ringContent}><svg viewBox="0 0 180 180" role="img" aria-label={rows.map(r=>`${r.label}: ${r.n}`).join(', ')}><circle cx="90" cy="90" r="66" className={styles.ringTrack}/>{rows.map(r=>{const start=offset,length=sessions.length?r.n/sessions.length*100:0;offset+=length;return <circle key={r.label} {...tooltip.bind({label:r.label,value:`${r.n} conversations`,note:`${sessions.length?(r.n/sessions.length*100).toFixed(1):'0'}% of ${sessions.length} loaded in this period`})} cx="90" cy="90" r="66" pathLength="100" className={styles.ringArc} stroke={r.color} strokeDasharray={`${length} ${100-length}`} strokeDashoffset={-start} transform="rotate(-90 90 90)"/>;})}<text x="90" y="89" textAnchor="middle" className={styles.ringNumber}>{sessions.length}</text><text x="90" y="111" textAnchor="middle">conversations</text></svg><div className={styles.legend}>{rows.map(r=><div key={r.label} {...tooltip.bind({label:r.label,value:`${r.n} conversations`,note:`${sessions.length?(r.n/sessions.length*100).toFixed(1):'0'}% of selected conversations`})}><i style={{background:r.color}}/><span>{r.label}</span><b>{r.n}</b></div>)}</div>{tooltip.tip}</div>;}
 if(id==='hours'){const hours=Array.from({length:24},(_,h)=>sessions.filter(s=>new Date(s.created_at).getHours()===h).length),max=Math.max(1,...hours);return <><p className={styles.chartNote}>Start time · your local timezone</p><div className={styles.heatmap}>{hours.map((n,h)=><div key={h} {...tooltip.bind({label:`${h.toString().padStart(2,'0')}:00–${h.toString().padStart(2,'0')}:59 · local time`,value:`${n} conversations`,note:'Conversation starts · selected period/source'})} aria-label={`${h}:00 — ${n} conversations`}><span>{h.toString().padStart(2,'0')}</span><i style={{opacity:.15+.85*n/max,background:n===max&&n>0?'var(--brand-gold,#ffbb24)':undefined}}/><b>{n}</b></div>)}</div><p className={styles.chartNote}>Conversation starts, not connection or answer rates.</p>{tooltip.tip}</>;}
 const rows=id==='leadSources'?Array.from(new Set(leads.map(l=>l.source||'Unspecified'))).map(source=>({id:source,label:source,count:leads.filter(l=>(l.source||'Unspecified')===source).length,color:'#729bff'})):id==='durationMix'?[['Under 1 min',0,60],['1–3 min',60,180],['3–5 min',180,300],['5+ min',300,Infinity]].map(([label,min,max])=>({id:String(label),label:String(label),count:known.filter(s=>s.duration_seconds!>=Number(min)&&s.duration_seconds!<Number(max)).length,color:'#729bff'})):id==='weekdays'?['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i)=>({id:label,label,count:sessions.filter(s=>new Date(s.created_at).getDay()===(i+1)%7).length,color:i<5?'#729bff':'#ffbb24'})):id==='channels'?['phone','web'].map(c=>({id:c,label:c==='phone'?'Phone conversations':'Browser voice tests',count:sessions.filter(s=>s.channel===c).length,color:c==='phone'?'#729bff':'#ffbb24'})):pipeline?.buckets.map(b=>({id:b.id,label:b.name,count:leads.filter(l=>bucketFor(l,pipeline)?.id===b.id).length,color:bucketHex[b.color]}))||leadStages.map(s=>({id:s,label:stageLabel(s),count:leads.filter(l=>l.stage===s).length,color:'#729bff'}));const total=id==='durationMix'?known.length:['channels','weekdays'].includes(id)?sessions.length:leads.length;
 return <><div className={styles.bars}>{rows.map(r=><div key={r.id} {...tooltip.bind({label:r.label,value:`${r.count} ${['stages','leadSources'].includes(id)?'leads':'conversations'}`,note:`${total?(r.count/total*100).toFixed(1):'0'}% of ${total} ${id==='durationMix'?'sessions with known duration':['stages','leadSources'].includes(id)?'loaded leads':'selected sessions'}`})}><span>{r.label}<b>{r.count}</b></span><div><i style={{width:`${total?r.count/total*100:0}%`,background:r.color}}/></div></div>)}</div><p className={styles.chartNote}>{['stages','leadSources'].includes(id)?`Current distribution across ${total} loaded leads. Independent of period/source filters.`:id==='durationMix'?'Known durations only; unknown durations excluded.':id==='weekdays'?'Local start day; selected period and source.':'Saved sessions only. Browser voice tests are practice conversations.'}</p>{tooltip.tip}</>;
});
