"use client";
import {useEffect,useRef,useState} from 'react';import {ListPlus,Play,Square,Upload,Check,Phone,Search,X} from 'lucide-react';
import type {LeadStore} from './CallerSalesPanels';import type {ListStore} from './CallerLists';import {eligibleLeads} from '@/lib/caller-lists';import type {CallSession} from '@/lib/caller-types';import styles from './CallerOperations.module.css';
export function CallerAiQueue({store,lists,transfer,upload,sessions,inspect}:{store:LeadStore;lists:ListStore;transfer:{ids:string[];version:number};upload():void;sessions:CallSession[];inspect(session:CallSession):void}){
 const [ids,setIds]=useState<string[]>([]),[choosing,setChoosing]=useState(false),[search,setSearch]=useState(''),[listId,setListId]=useState(''),[running,setRunning]=useState(false),[current,setCurrent]=useState(''),[done,setDone]=useState<string[]>([]),[detail,setDetail]=useState('');const run=useRef(0),locked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),dialog=useRef<HTMLDialogElement|null>(null);
 const eligible=eligibleLeads(store.leads),queue=ids.map(id=>eligible.find(l=>l.id===id)).filter(l=>Boolean(l)),visible=eligible.filter(l=>`${l.name} ${l.company} ${l.phone}`.toLowerCase().includes(search.toLowerCase()));
 function stop(){run.current++;locked.current=false;if(timer.current)clearTimeout(timer.current);setRunning(false);setCurrent('');}
 useEffect(()=>()=>{run.current++;if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>{stop();setDone([]);setIds(transfer.ids.filter(id=>eligible.some(l=>l.id===id)).slice(0,500));},[transfer.version]);
 useEffect(()=>{if(choosing)dialog.current?.showModal();},[choosing]);
 useEffect(()=>{if(detail)document.getElementById("caller-demo-detail")?.scrollIntoView({behavior:"instant",block:"start"});},[detail]);
 function start(){if(locked.current||!store.demo||!queue.length)return;locked.current=true;const turn=++run.current;setRunning(true);setDone([]);setDetail('');let index=0;const snapshot=queue.map(l=>l!.id);function next(){if(turn!==run.current)return;if(index===snapshot.length){locked.current=false;setRunning(false);setCurrent('');return;}const id=snapshot[index++];setCurrent(id);timer.current=setTimeout(()=>{if(turn!==run.current)return;setDone(previous=>[...previous,id]);next();},1800);}next();}
 function select(id:string){setIds(previous=>previous.includes(id)?previous.filter(value=>value!==id):previous.length<500?[...previous,id]:previous);setDone([]);}
 const detailLead=store.leads.find(l=>l.id===detail);
 return <div className={styles.stack}><section className={styles.queueHero}><div><span className={styles.kicker}>AI CALLER</span><h2>Choose your people.<br/>Set your outreach in motion.</h2><p>Build a calling list from your CRM, review the queue and follow each conversation in one place.</p><div className={styles.actions}><button className={styles.primary} disabled={!store.demo||!queue.length||running} onClick={start}><Play size={17}/>{store.demo?'Turn on AI Caller · Demo':'Turn on AI Caller'}</button>{running&&<button className={styles.secondary} onClick={stop}><Square size={16}/>Stop demo</button>}<span className={styles.heroStatus}>{store.demo?'Simulation mode · no calls placed':'Phone connection pending'}</span></div></div><div className={styles.queueSummary}><Phone size={25}/><strong>{queue.length}</strong><span>leads in your queue</span><small>{done.length} completed{store.demo?' · demo':''}</small></div></section>
 {!store.demo&&<p className={styles.notice}>Prepare your list now. Automated phone calls require a connected phone provider and outbound workflow. Turning on real outreach is unavailable until that connection is configured.</p>}
 <section className={styles.chartCard}><header><div><span className={styles.kicker}>YOUR CALLING LIST</span><h3>{running?'Working through your demo queue.':'Who should we call?'}</h3></div><div className={styles.actions}><button className={styles.secondary} disabled={running||store.busy} onClick={()=>setChoosing(true)}><ListPlus size={16}/>Load from CRM</button><button className={styles.secondary} disabled={running} onClick={upload}><Upload size={16}/>Upload leads</button></div></header><div className={styles.actions}><label>Saved CRM list<select aria-label="Load saved calling list" disabled={running} value={listId} onChange={e=>{setListId(e.target.value);setIds((lists.lists.find(l=>l.id===e.target.value)?.leadIds??[]).filter(id=>eligible.some(l=>l.id===id)));setDone([]);}}><option value="">Choose a saved list</option>{lists.lists.map(l=><option value={l.id} key={l.id}>{l.name} · {l.leadIds.length}</option>)}</select></label><button className={styles.textButton} disabled={running||!ids.length} onClick={()=>{setIds([]);setDone([]);setListId('');}}>Clear queue</button><span className={styles.scope}>Do not call, Won and Lost leads are excluded.</span></div>{lists.error&&<p className={styles.error} role="alert">{lists.error}</p>}
 {queue.length?<div className={styles.tableWrap}><table><thead><tr><th>Lead</th><th>Phone</th><th>Progress</th><th>Conversation</th></tr></thead><tbody>{queue.map(lead=>{const l=lead!,complete=done.includes(l.id),calling=current===l.id,result=sessions.find(s=>s.lead_id===l.id);return <tr key={l.id} data-calling={calling}><td><strong>{l.name}</strong><small>{l.company}</small></td><td>{l.phone}</td><td><span className={complete?styles.done:calling?styles.calling:styles.ready}>{complete?<Check size={14}/>:calling?<Phone size={14}/>:null}{complete?'Completed · Demo':calling?'Calling · Demo':'Ready'}</span></td><td><button className={styles.textButton} disabled={!complete&&!result} onClick={()=>result?inspect(result):setDetail(l.id)}>View call & transcript</button></td></tr>;})}</tbody></table></div>:<div className={styles.empty}><ListPlus size={30}/><h3>Your queue is waiting for its first lead.</h3><p>Load a saved list, select leads from your CRM or upload a CSV to get started.</p></div>}
 <p className={styles.scope} role="status">{store.demo?`DEMO — ${done.length} of ${queue.length} simulated steps completed. Progress resets when you leave Caller or switch data mode. No phone call, voice generation or CRM outcome is created.`:`${queue.length} leads selected. No calls have been started.`}</p></section>
 {detailLead&&<section id="caller-demo-detail" className={styles.chartCard}><header><h3>Demo conversation · {detailLead.name}</h3><button aria-label="Close demo conversation" className={styles.secondary} onClick={()=>setDetail('')}><X size={16}/></button></header><p className={styles.notice}>Illustrative transcript for the demo queue. This conversation did not happen and is not provider-verified.</p><p><strong>AI agent:</strong> This call is going to be recorded for educational purposes. Is now a good time to talk?</p><p><strong>Demo lead:</strong> Can you tell me a little more about how this works?</p><p><strong>AI agent:</strong> Of course. Let’s start with what you want to improve.</p></section>}
 {choosing&&<dialog className={styles.dialog} ref={dialog} onCancel={()=>setChoosing(false)} onClose={()=>setChoosing(false)} aria-label="Choose calling leads"><header><h3>Build your calling list.</h3><button className={styles.secondary} aria-label="Close lead selection" onClick={()=>setChoosing(false)}><X size={18}/></button></header><label className={styles.search}><Search size={16}/><input autoFocus aria-label="Search calling leads" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your CRM…"/></label><div className={styles.actions}><label className={styles.consent}><input type="checkbox" aria-label="Select all eligible leads" checked={Boolean(visible.length)&&visible.slice(0,500).every(l=>ids.includes(l.id))} onChange={e=>{setIds(e.target.checked?visible.slice(0,500).map(l=>l.id):[]);setDone([]);}}/>Select all filtered · max 500</label><span>{ids.length} selected</span></div><div className={styles.pickList}>{visible.map(l=><label key={l.id}><input type="checkbox" checked={ids.includes(l.id)} onChange={()=>select(l.id)}/><span><strong>{l.name}</strong><small>{l.company} · {l.phone}</small></span></label>)}{!visible.length&&<p>No eligible leads in this view.</p>}</div><button className={styles.primary} onClick={()=>setChoosing(false)}>Use {ids.length} leads</button></dialog>}
 </div>;
}
