'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Check,Mail,MessageSquare,RefreshCw} from 'lucide-react';
import {emptyBookingConfig,type BookingConfig} from '@/lib/caller-booking';
import styles from './CallerBooking.module.css';
interface Options {locationName:string;calendars:{id:string;name:string}[];pipelines:{id:string;name:string;stages:{id:string;name:string}[]}[]}
interface Booking {id:string;state:string;created_at:string;receipt:{startTime?:string};caller_booking_steps:{kind:string;state:string;reason?:string;cost_microusd:number|null}[]}
interface Status {config:BookingConfig;connected:boolean;toolsReady:boolean;verifiedAt:string|null;bookings:Booking[]}
export function CallerBooking({token}:{token:string}){
 const [data,setData]=useState<Status|null>(null),[config,setConfig]=useState(emptyBookingConfig),[secret,setSecret]=useState(''),[options,setOptions]=useState<Options|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch('/api/caller/booking/'+path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Booking could not load.');return d;}
 async function load(){const d=await api<Status>('config');setData(d);setConfig(d.config);}
 useEffect(()=>{let cancelled=false;void api<Status>('config').then(d=>{if(!cancelled){setData(d);setConfig(d.config);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[token]);
 function update<K extends keyof BookingConfig>(key:K,value:BookingConfig[K]){setConfig(c=>({...c,[key]:value}));setNotice('');}
 async function action(name:string,work:()=>Promise<void>){if(busy)return;setBusy(name);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Could not complete this action.');}finally{setBusy('');}}
 return <div className={styles.wrap}>
  <header className={styles.header}><div><span className={styles.eyebrow}>CONNECTED ACTIONS</span><h2>Turn a conversation into a meeting.</h2><p>Book into NBC’s calendar, send the invitation and keep the sales pipeline in sync.</p></div><span className={styles.status}>{data?.config.enabled?'Booking enabled':data?.connected?'Connection saved · activation pending':'Connect GoHighLevel'}</span></header>
  <div className={styles.flow}>{[{icon:CalendarDays,title:'Find a time',body:'Live availability in the recipient’s timezone.'},{icon:Check,title:'Confirm the booking',body:'Reserve only after the recipient agrees.'},{icon:Mail,title:'Send the invitation',body:'Email with calendar attachment and optional SMS.'},{icon:MessageSquare,title:'Update your CRM',body:'Apply your tags and move the opportunity.'}].map(({icon:Icon,title,body})=><div key={title}><Icon size={20}/><strong>{title}</strong><p>{body}</p></div>)}</div>
  {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
  <form className={styles.panel} onSubmit={e=>{e.preventDefault();void action('save',async()=>{await api('config','PUT',{config,token:secret});setSecret('');await load();setNotice('Booking settings saved.');});}}>
   <fieldset disabled={Boolean(busy)||!data}><legend>1. Connect NBC’s GoHighLevel account</legend><p>The private token stays on the server. Loading calendars only reads your account.</p><div className={styles.grid}>
    <label>Location ID<input value={config.locationId} onChange={e=>{update('locationId',e.target.value);setOptions(null);update('calendarId','');update('pipelineId','');update('stageId','');}} required autoComplete="off"/></label>
    <label>Private integration token<input type="password" value={secret} onChange={e=>{setSecret(e.target.value);setOptions(null);}} placeholder={data?.connected?'Saved securely · leave blank to keep':'Paste your GHL integration token'} autoComplete="new-password"/></label>
   </div><button type="button" onClick={()=>void action('connect',async()=>{const o=await api<Options>('options','POST',{locationId:config.locationId,token:secret});setOptions(o);setNotice(`Connected to ${o.locationName}. Choose your calendar and pipeline below.`);})}>{busy==='connect'?'Reading your account…':'Load calendars & pipelines'}</button>
   <details><summary>Required GHL access</summary><p>locations.readonly, calendars.readonly, calendars/events.readonly, calendars/events.write, contacts.readonly, contacts.write, opportunities.readonly, opportunities.write, conversations/message.readonly and conversations/message.write. The GHL calendar must have an active meeting location; email and SMS senders must already work in this location.</p></details></fieldset>
   <fieldset disabled={Boolean(busy)||!data}><legend>2. Choose where meetings go</legend><div className={styles.grid}>
    <label>Business name<input value={config.businessName} onChange={e=>update('businessName',e.target.value)} maxLength={100} required/></label>
    <label>Calendar<select aria-label="Calendar" value={config.calendarId} onChange={e=>update('calendarId',e.target.value)} required><option value="">Choose a calendar</option>{!options&&config.calendarId&&<option value={config.calendarId}>Saved calendar · load to change</option>}{options?.calendars.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Calendar timezone<input value={config.timezone} onChange={e=>update('timezone',e.target.value)} placeholder="America/New_York" required/></label>
    <label>Pipeline<select aria-label="Pipeline" value={config.pipelineId} onChange={e=>{update('pipelineId',e.target.value);update('stageId','');}} required><option value="">Choose a pipeline</option>{!options&&config.pipelineId&&<option value={config.pipelineId}>Saved pipeline · load to change</option>}{options?.pipelines.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label>Stage after booking<select aria-label="Stage after booking" value={config.stageId} onChange={e=>update('stageId',e.target.value)} required><option value="">Choose a stage</option>{!options&&config.stageId&&<option value={config.stageId}>Saved stage · load to change</option>}{options?.pipelines.find(p=>p.id===config.pipelineId)?.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <label>Tags to add<input value={config.tags.join(', ')} onChange={e=>update('tags',e.target.value.split(',').map(t=>t.trim()))} placeholder="Choose your tags, separated by commas"/></label>
   </div></fieldset>
   <fieldset disabled={Boolean(busy)||!data}><legend>3. Send the confirmation</legend><p>Direct sends through GHL. Calendar automations are suppressed on the booking request to avoid duplicate notifications.</p><div className={styles.grid}>
    <div><label className={styles.check}><input type="checkbox" checked={config.sendEmail} onChange={e=>update('sendEmail',e.target.checked)}/>Email with calendar invitation</label><label>Connected sender email<input type="email" value={config.emailFrom} onChange={e=>update('emailFrom',e.target.value)} required={config.sendEmail}/></label></div>
    <div><label className={styles.check}><input type="checkbox" checked={config.sendSms} onChange={e=>update('sendSms',e.target.checked)}/>SMS after verbal confirmation</label><label>Connected GHL SMS number<input type="tel" value={config.smsFrom} onChange={e=>update('smsFrom',e.target.value)} placeholder="+1…" required={config.sendSms}/></label></div>
   </div><p>GHL email and SMS charges are additional to voice usage. Billing is shown as pending until a provider receipt is available. Do Not Disturb preferences are respected.</p></fieldset>
   <div className={styles.footer}><label className={styles.check}><input type="checkbox" checked={config.enabled} disabled={!data?.toolsReady||Boolean(busy)} onChange={e=>update('enabled',e.target.checked)}/>Enable booking for new phone calls</label>{!data?.toolsReady&&<p>Save the NBC connection first. Phone booking tools must be registered before activation. Browser practice remains a simulation.</p>}<div className={styles.actions}><button type="submit" disabled={Boolean(busy)||!data}>{busy==='save'?'Saving…':'Save booking settings'}</button>{data?.config.enabled&&<button type="button" disabled={Boolean(busy)} onClick={()=>void action('pause',async()=>{await api('config','PATCH');await load();})}>Pause booking</button>}</div></div>
  </form>
  <section className={styles.panel}><div className={styles.sectionHead}><div><h3>Booking activity</h3><p>Reservation, CRM updates and delivery are tracked separately.</p></div><button type="button" aria-label="Refresh bookings" disabled={Boolean(busy)} onClick={()=>void action('refresh',load)}><RefreshCw size={16}/></button></div>{!data?.bookings.length?<p>No meetings booked yet. Your first confirmed booking will appear here.</p>:data.bookings.map(b=><article key={b.id} className={styles.booking}><div><strong>{b.receipt.startTime?new Date(b.receipt.startTime).toLocaleString('en-US'):new Date(b.created_at).toLocaleString('en-US')}</strong><span>{b.state}</span></div><ul>{b.caller_booking_steps.map(s=><li key={s.kind}>{s.kind}: {s.state}{s.reason?` · ${s.reason}`:''}{['email','sms'].includes(s.kind)?` · ${s.cost_microusd===null?'cost pending':`$${(s.cost_microusd/1e6).toFixed(4)}`}`:''}</li>)}</ul><button type="button" disabled={Boolean(busy)} onClick={()=>void action(b.id,async()=>{await api(`${b.id}/refresh`,'POST');await load();})}>Check saved result</button></article>)}</section>
 </div>;
}
