'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {PilotSlotView} from '@/lib/live-pilot';
import type {CallSession} from '@/lib/caller-types';
import styles from './CallerArchive.module.css';
export interface CallAsset{resource_key:string;recording_status:string;note:string;note_version:number;live_transcript:Array<{role:string;message:string}>;live_status:string;updated_at:string}
export function useCallArchive(token:string){
 const [calls,setCalls]=useState<PilotSlotView[]>([]),[assets,setAssets]=useState<CallAsset[]>([]),[error,setError]=useState('');
 const version=useRef(0),currentToken=useRef(token);currentToken.current=token;
 const refresh=useCallback(async()=>{if(!token)return;const turn=++version.current;try{
  const r=await fetch('/api/caller/archive',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(15000)}),b=await r.json();
  if(!r.ok)throw Error(b.error??'Archive could not load.');if(turn!==version.current||currentToken.current!==token)return;
  setCalls(b.calls);setAssets(b.assets);setError('');
 }catch(e){if(turn===version.current&&currentToken.current===token)setError(e instanceof Error?e.message:'Archive unavailable.');}},[token]);
 useEffect(()=>{setCalls([]);setAssets([]);setError('');void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);return()=>{version.current++;clearInterval(timer);};},[refresh]);
 return{calls,assets,error,refresh};
}
export function CallRecordingAndNotes({token,resourceKey,asset,onSaved}:{token:string;resourceKey:string;asset?:CallAsset;onSaved:()=>void}){
 const [url,setUrl]=useState(''),[note,setNote]=useState(asset?.note??''),[version,setVersion]=useState(asset?.note_version??0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(!dirty&&(asset?.note_version??0)>=version){setNote(asset?.note??'');setVersion(asset?.note_version??0);}},[asset?.note_version,dirty,asset?.note,version]);
 async function run(action:'audio'|'note'){setBusy(action);setError('');try{const r=await fetch(action==='audio'?'/api/caller/archive?recording='+encodeURIComponent(resourceKey):'/api/caller/archive',{method:action==='audio'?'GET':'PATCH',headers:{Authorization:'Bearer '+token,...(action==='note'?{'Content-Type':'application/json'}:{})},...(action==='note'?{body:JSON.stringify({key:resourceKey,note,version})}:{}),cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error??'Please retry.');if(action==='audio')setUrl(b.url);else{setVersion(b.note_version);setDirty(false);setSaved(true);}onSaved();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy('');}}
 return <div className={styles.recording}><h3>Recording & notes</h3><p>Full conversation audio, when retained by the provider. Older calls without a recording cannot be reconstructed.</p><button disabled={Boolean(busy)} onClick={()=>void run('audio')}>{busy==='audio'?'Preparing recording…':url?'Refresh playback link':'Open recording'}</button>{url&&<><audio controls preload="metadata" src={url} aria-label="Full call recording" onError={()=>setError('Playback link may have expired. Refresh it to listen again.')}/><a href={url} target="_blank" rel="noreferrer">Open / download audio</a></>}<label>Private call notes<textarea maxLength={3000} rows={4} value={note} onChange={e=>{setNote(e.target.value);setDirty(true);setSaved(false);}} placeholder="What worked? What should change next time?"/></label><button disabled={Boolean(busy)||!dirty} onClick={()=>void run('note')}>{busy==='note'?'Saving…':'Save notes'}</button>{saved&&<span role="status">Notes saved</span>}{error&&<p role="alert">{error}</p>}</div>;
}
export function CallerPhoneArchive({token,calls,assets,refresh}:{token:string;calls:PilotSlotView[];assets:CallAsset[];refresh:()=>void}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const filtered=calls.filter(c=>`${c.title} ${c.destinationLast4??''} ${c.scenarioTitle??''} ${c.result.summary??''} ${c.result.transcript?.map(t=>t.message).join(' ')??''}`.toLowerCase().includes(query.toLowerCase()));const chosen=calls.find(c=>c.key===selected);
 async function sync(key:string){setBusy(true);setError('');try{const r=await fetch('/api/pilot',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'sync',key})});const b=await r.json();if(!r.ok)throw Error(b.error??'Could not update call.');refresh();}catch(e){setError(e instanceof Error?e.message:'Could not update call.');}finally{setBusy(false);}}
 function download(c:PilotSlotView){const blob=new Blob([`${c.scenarioTitle??c.title}\n${c.createdAt??''}\n\n${c.result.summary??''}\n\n`+(c.result.transcript??[]).map(t=>`${t.role==='agent'?'Agent':'Prospect'}: ${t.message}`).join('\n\n')],{type:'text/plain'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`call-${c.key}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className={styles.archive} aria-label="Phone call archive"><header><div><span>PHONE CALLS</span><h2>Every conversation, in one place.</h2><p>Listen back, read the transcript, and keep your notes with the call.</p></div><button onClick={refresh}>Refresh archive</button></header><input type="search" aria-label="Search phone calls" placeholder="Search scenario, phone ending or transcript…" value={query} onChange={e=>setQuery(e.target.value)}/><div className={styles.list}>{filtered.map(c=><button className={selected===c.key?styles.selected:''} key={c.key} onClick={()=>setSelected(c.key)}><strong>{c.scenarioTitle??c.title}</strong><span>{c.createdAt?new Date(c.createdAt).toLocaleString():''} · ending {c.destinationLast4} · {c.state}</span><small>{c.result.durationSeconds==null?'Duration pending':`${Math.round(c.result.durationSeconds)} seconds`} · {c.reportedMicrousd==null?'Cost pending':`$${(c.reportedMicrousd/1e6).toFixed(4)}`} · {assets.find(a=>a.resource_key===c.key)?.recording_status==='saved'?'Audio saved':assets.find(a=>a.resource_key===c.key)?.recording_status==='unavailable'?'No retained audio':assets.find(a=>a.resource_key===c.key)?.recording_status==='retry'?'Audio save pending retry':'Audio availability pending'}</small></button>)}</div>{!filtered.length&&<p>No phone calls match. Your completed calls will appear here.</p>}{chosen&&<section className={styles.detail} aria-label="Saved phone call"><header><h3>{chosen.scenarioTitle??chosen.title}</h3><button disabled={busy} onClick={()=>void sync(chosen.key)}>Update saved result</button><button disabled={!chosen.result.transcript?.length} onClick={()=>download(chosen)}>Download transcript</button></header><p>{chosen.result.summary??chosen.result.message}</p>{error&&<p role="alert">{error}</p>}<CallRecordingAndNotes key={chosen.key} token={token} resourceKey={chosen.key} asset={assets.find(a=>a.resource_key===chosen.key)} onSaved={refresh}/><h3>Transcript</h3><div className={styles.transcript}>{chosen.result.transcript?.map((t,i)=><p key={i}><strong>{t.role==='agent'?'Agent':'Prospect'}:</strong> {t.message}</p>)}</div></section>}</section>;
}
export function phoneAnalyticsSessions(calls:PilotSlotView[],existing:CallSession[]):CallSession[]{return calls.filter(c=>!existing.some(s=>s.id===c.key)).map(c=>({id:c.key,provider:c.result.phoneEngine==='retell'?'retell':'elevenlabs',provider_call_id:null,channel:'phone',status:c.state==='completed'?'completed':c.state==='failed'||c.state==='stopped'?'failed':'active',scenario_title:c.scenarioTitle??c.title,created_at:c.createdAt??'',started_at:c.createdAt??null,ended_at:c.state==='completed'?c.updatedAt??null:null,duration_seconds:c.result.durationSeconds??null,cost_microusd:c.reportedMicrousd,transcript:[],summary:c.result.summary??null,failure_code:null,synced_at:c.updatedAt??null}));}
