"use client";
import {CallerBoard} from './CallerBoard';
import {useEffect,useRef,useState} from 'react';import type {MouseEvent} from 'react';import {ArrowUpRight,ChevronRight,FileUp,LayoutList,Columns3,Plus,Search,SlidersHorizontal,Phone,ShieldOff,X} from 'lucide-react';
import type {CallerLead} from '@/lib/caller-crm';import {parseLeadCsv} from '@/lib/caller-crm';import {bucketFor,bucketHex,isBlocked} from '@/lib/caller-workbench';import {salesRequest} from '@/lib/caller-request';import {LeadFeedback} from './CallerSalesPanels';import type {LeadStore} from './CallerSalesPanels';import {CallerSelection} from './CallerLists';import type {ListStore} from './CallerLists';import {CallerPipelineEditor} from './CallerPipeline';import type {PipelineStore} from './CallerPipeline';import {CallerLeadDetail} from './CallerLeadDetail';import type {NoteDraft} from './CallerLeadDetail';import styles from './CallerWorkbench.module.css';import sales from './CallerSales.module.css';
export function CallerCrm({store,dial,lists,send,pipeline,importRequest=0}:{store:LeadStore;dial(lead:CallerLead):void;lists:ListStore;send(ids:string[]):void;pipeline:PipelineStore;importRequest?:number}){
 const [importing,setImporting]=useState(false),[preview,setPreview]=useState<ReturnType<typeof parseLeadCsv>|null>(null),[fileName,setFileName]=useState(''),[fileError,setFileError]=useState(''),[query,setQuery]=useState(''),[stage,setStage]=useState('all'),[view,setView]=useState('pipeline'),[selected,setSelected]=useState<string|null>(null),[chosen,setChosen]=useState<string[]>([]),[listFilter,setListFilter]=useState(''),[editing,setEditing]=useState(false);
 const requestId=useRef(''),fileVersion=useRef(0),drafts=useRef(new Map<string,NoteDraft>()),opener=useRef<HTMLElement|null>(null),detailSlot=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(importRequest)setImporting(true);},[importRequest]);useEffect(()=>()=>{fileVersion.current++;},[]);
 const config=pipeline.pipeline,buckets=config?.buckets||[],selection=store.leads.find(l=>l.id===selected),selectedIds=chosen.filter(id=>store.leads.some(l=>l.id===id));
 const visible=store.leads.filter(l=>(!listFilter||lists.lists.find(list=>list.id===listFilter)?.leadIds.includes(l.id))&&(stage==='all'||bucketFor(l,config)?.id===stage)&&`${l.name} ${l.company} ${l.phone} ${l.email}`.toLowerCase().includes(query.toLowerCase()));
 const totals={active:store.leads.filter(l=>bucketFor(l,config)?.outcome==='active'&&!isBlocked(l)).length,won:store.leads.filter(l=>bucketFor(l,config)?.outcome==='won').length};
 function openLead(id:string,event:MouseEvent<HTMLElement>){opener.current=event.currentTarget;setSelected(id);requestAnimationFrame(()=>{if(innerWidth<1050)detailSlot.current?.scrollIntoView({behavior:'instant',block:'start'});});}
 function closeLead(){setSelected(null);opener.current?.focus({preventScroll:true});}
 function toggle(id:string){setChosen(previous=>previous.includes(id)?previous.filter(value=>value!==id):previous.length<500?[...previous,id]:previous);}
  async function readFile(file?: File): Promise<void> {
    const turn = ++fileVersion.current; setFileError(""); setPreview(null); requestId.current = "";
    if (!file) return;
    setFileName(file.name);
    try { if (file.size > 512 * 1024) throw new Error("Choose a CSV smaller than 512 KB."); const data = parseLeadCsv(await file.text()); if (turn !== fileVersion.current) return; setPreview(data); requestId.current = crypto.randomUUID(); }
    catch (failure) { if (turn === fileVersion.current) setFileError(failure instanceof Error ? failure.message : "This file could not be read."); }
  }
  async function importLeads(): Promise<void> {
    if (store.demo || !preview?.leads.length) return;
    const done = await store.run(async () => {
      const result = await salesRequest<{ imported: number; duplicates: number; replayed: boolean }>(store.token, "/api/caller/leads", "POST", { requestId: requestId.current, leads: preview.leads });
      await store.refresh();
      return `${result.imported} leads saved; ${result.duplicates} existing phone numbers skipped. No calls started.`;
    });
    if (done) { setPreview(null); setImporting(false); requestId.current = ""; }
  }
 return <div className={styles.crm}><header className={styles.crmHeader}><div><h2>Pipeline <span>{store.leads.length}</span></h2><p><span>{totals.active} active</span><i/> <span>{totals.won} won</span><i/><span>{store.demo?'Demo workspace':'Your private workspace'}</span></p></div><div className={styles.actions}><button className={styles.secondary} disabled={!config||store.busy} onClick={()=>setEditing(value=>!value)}><SlidersHorizontal size={15}/>Customize pipeline</button><button className={styles.primary} disabled={store.busy} onClick={()=>setImporting(value=>!value)}><Plus size={16}/>Import leads</button></div></header>
 {editing&&config&&<CallerPipelineEditor key={config.version} store={pipeline} close={()=>setEditing(false)} saved={async()=>{await store.refresh();setStage('all');}}/>}
 {pipeline.error&&<div role="alert" className={styles.error}>{pipeline.error}<button className={styles.textButton} onClick={()=>void pipeline.refresh().catch(()=>undefined)}>Retry pipeline</button></div>}
    {importing && <div className={sales.importBox}><div className={sales.row}><h3><FileUp size={19} /> Bring your leads into NBC</h3><button aria-label="Close import" disabled={store.busy} onClick={() => setImporting(false)}><X size={18} /></button></div>{store.demo && <p className={sales.notice}>Switch to Live data to import a real CSV. Demo data stays separate.</p>}<p>CSV · up to 500 rows · US phone numbers. Required columns: <code>name,phone</code>. Optional: <code>email,company,source</code>.</p><label className={sales.file}>Choose CSV<input type="file" accept=".csv,text/csv" disabled={store.busy} onChange={event => void readFile(event.target.files?.[0])} /></label>{fileName && <small>{fileName}</small>}{fileError && <p className={sales.error} role="alert">{fileError}</p>}{preview && <><p>{preview.leads.length} valid leads · {preview.duplicates} duplicate numbers in file · {preview.errors.length} invalid rows</p>{preview.errors.length > 0 && <details><summary>Review skipped rows</summary>{preview.errors.slice(0,30).map(error => <p key={error.row}>Row {error.row}: {error.message}</p>)}{preview.errors.length > 30 && <p>Showing the first 30 errors. Fix the CSV before importing all rows.</p>}</details>}<div className={sales.preview}>{preview.leads.slice(0,5).map(lead => <div key={lead.phone}><strong>{lead.name}</strong><span>{lead.phone}</span></div>)}</div><button className={sales.primary} disabled={store.demo || store.busy || !store.configured || !preview.leads.length} onClick={() => void importLeads()}>{store.busy ? "Saving…" : `Import ${preview.leads.length} valid leads`}</button><small>Duplicates already in your CRM keep their existing stage and notes. Invalid rows are skipped. Retry uses the same import reference.</small></>}</div>} <div className={styles.toolbar}><label className={styles.search}><Search size={15}/><input aria-label="Search leads" placeholder="Search leads…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className={styles.filter}>List<select aria-label="Filter by lead list" value={listFilter} onChange={e=>setListFilter(e.target.value)}><option value="">All leads</option>{lists.lists.map(list=><option value={list.id} key={list.id}>{list.name} ({list.leadIds.length})</option>)}</select></label><label className={styles.filter}>Stage<select aria-label="Filter pipeline stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{buckets.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className={styles.viewToggle}><button aria-pressed={view==='pipeline'} onClick={()=>setView('pipeline')}><Columns3 size={15}/>Board</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}><LayoutList size={15}/>List</button></div></div>
 <div className={styles.selection}><label className={styles.checkLabel}><input type="checkbox" aria-label="Select all filtered leads" checked={Boolean(visible.length)&&visible.slice(0,500).every(l=>selectedIds.includes(l.id))} onChange={e=>setChosen(e.target.checked?visible.slice(0,500).map(l=>l.id):[])}/>Select all</label><CallerSelection ids={selectedIds} lists={lists} send={()=>send(selectedIds)} clear={()=>setChosen([])}/></div>
 <LeadFeedback store={store}/>
 <div className={styles.crmLayout} data-open={Boolean(selection)}><div className={styles.boardArea}>{pipeline.loading||store.busy&&!store.leads.length?<div className={styles.empty} role="status">Loading your workspace…</div>:view==='pipeline'?<CallerBoard store={store} pipeline={pipeline} visible={visible} stage={stage} selected={selected} selectedIds={selectedIds} toggle={toggle} openLead={openLead}/>:<div className={styles.tableWrap}><table><thead><tr><th/><th>Lead</th><th>Contact</th><th>Stage</th><th>Latest activity</th></tr></thead><tbody>{visible.map(l=><tr key={l.id} data-selected={selected===l.id}><td><input type="checkbox" aria-label={`Select ${l.name}`} checked={selectedIds.includes(l.id)} onChange={()=>toggle(l.id)}/></td><td><button onClick={e=>openLead(l.id,e)} aria-label={`Open ${l.name}`}><strong>{l.name}</strong><small>{l.company}</small></button></td><td>{l.phone}{isBlocked(l)&&<small className={styles.blocked}>Do not call</small>}</td><td><span className={styles.stageLabel}><i style={{background:bucketHex[bucketFor(l,config)?.color||'slate']}}/>{bucketFor(l,config)?.name||'Unassigned'}</span></td><td><span className={styles.activityPreview}>{l.latest_activity_preview||'No activity logged'}</span>{l.latest_activity_at&&<small>{new Date(l.latest_activity_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small>}</td></tr>)}</tbody></table>{!visible.length&&<div className={styles.empty}>No leads match this view.</div>}</div>}</div>{selection&&<div ref={detailSlot} className={styles.detailSlot}><CallerLeadDetail key={selection.id} lead={selection} store={store} pipeline={pipeline} drafts={drafts.current} close={closeLead} dial={()=>{dial(selection);setSelected(null);}}/></div>}</div><p className={styles.caption}>{visible.length} of {store.leads.length} loaded leads · up to 1,000 recent records.{store.hasMore?' More leads exist outside this view.':''} Selection supports up to 500. {store.demo?'All data in this view is demo.':''}</p>
 </div>;
}
