'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowRight,Check,ExternalLink,LoaderCircle,Plus,RefreshCw,Users} from 'lucide-react';
import {useWorkspaceAccess} from '@/components/workspace/WorkspaceAccess';
import {emptyIntake,taskLink,type Intake,type IntakeRecord,type IntakeState} from '@/lib/client-onboarding';
import styles from './ClientOnboarding.module.css';
const labels:Record<IntakeState,string>={draft:'Draft',starting:'Starting setup',queued:'Added to onboarding queue',existing:'Already in ClickUp',uncertain:'Confirmation needed',needs_review:'Check saved fields'};
export function ClientOnboarding(){
 const access=useWorkspaceAccess();const [records,setRecords]=useState<IntakeRecord[]>([]),[connected,setConnected]=useState(false),[connectionIssue,setConnectionIssue]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[record,setRecord]=useState<IntakeRecord|null>(null),[intake,setIntake]=useState<Intake>(emptyIntake),[review,setReview]=useState(false),[confirmed,setConfirmed]=useState(false);
 const id=useRef(''),lock=useRef(false);
 async function api(path:string,body?:unknown){const r=await fetch('/api/onboarding'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${access.token}`,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load onboarding.');return d;}
 function remember(row:IntakeRecord){setRecord(row);setIntake(row.intake);id.current=row.id;setRecords(old=>[row,...old.filter(r=>r.id!==row.id)]);try{sessionStorage.setItem(`nbc-onboarding:${access.user?.id}`,row.id);}catch{} }
 async function load(){setLoading(true);setError('');try{const data=await api('');setRecords(data.records);setConnected(data.connected);setConnectionIssue(data.connectionIssue);let saved='';try{saved=sessionStorage.getItem(`nbc-onboarding:${access.user?.id}`)||'';}catch{}const row=data.records.find((r:IntakeRecord)=>r.id===saved);if(row){setRecord(row);setIntake(row.intake);id.current=row.id;}else{id.current=crypto.randomUUID();}}catch(e){setError(e instanceof Error?e.message:'Could not load onboarding.');}finally{setLoading(false);}}
 useEffect(()=>{if(access.token&&access.user?.role==='admin')void load();else setLoading(false);},[access.token]); // eslint-disable-line react-hooks/exhaustive-deps
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Request could not be confirmed. Open the saved result.');}finally{lock.current=false;setBusy(false);}}
 function choose(row:IntakeRecord){remember(row);setReview(false);setConfirmed(false);setError('');}
 function fresh(){id.current=crypto.randomUUID();setRecord(null);setIntake(emptyIntake());setReview(false);setConfirmed(false);setError('');try{sessionStorage.removeItem(`nbc-onboarding:${access.user?.id}`);}catch{}}
 async function save(event:FormEvent){event.preventDefault();await run(async()=>{const data=await api('',{id:id.current||crypto.randomUUID(),intake,revision:record?.revision});remember(data.record);setReview(true);setConfirmed(false);});}
 async function start(){if(!record||!confirmed)return;await run(async()=>{const data=await api('/'+record.id,{action:'start',confirmed:true,revision:record.revision});remember(data.record);setReview(false);setConfirmed(false);});}
 async function refresh(){if(!record)return;await run(async()=>{const data=await api('/'+record.id,record.state==='draft'?undefined:{action:'reconcile'});remember(data.record);});}
 const started=record&&record.state!=='draft';
 const fields=(key:keyof Intake,label:string,placeholder:string,required=false,type='text')=><label className={styles.field}>{label}{required&&<span aria-hidden="true"> *</span>}<input name={key} value={intake[key]} required={required} type={type} maxLength={key==='recording'||key==='transcript'?1500:200} placeholder={placeholder} disabled={busy||loading} onChange={e=>setIntake(v=>({...v,[key]:e.target.value}))}/></label>;
 if(access.user?.role!=='admin')return <section className={styles.page}><h1>Client onboarding</h1><p>This workspace is available to NBC administrators.</p></section>;
 return <section className={styles.page}>
  <header className={styles.header}><div><p className={styles.eyebrow}>NBC INTERNAL OPERATIONS</p><h1>Client onboarding</h1><p>A warm welcome starts with the right details.</p></div><span className={styles.connection}><i data-ready={connected}/>{loading?'Checking connection':connected?'ClickUp connected':'Connection needs attention'}</span></header>
  {error&&<div role="alert" className={styles.error}>{error}{!record&&<button onClick={()=>void load()} disabled={busy}>Reload</button>}</div>}
  {connectionIssue&&<p className={styles.notice}>{connectionIssue} You can save a draft while the connection is restored.</p>}
  <div className={styles.layout}><div className={styles.card}>
   <div className={styles.cardHeading}><span className={styles.icon}><Users size={21}/></span><div><h2>{started?'Your onboarding request':review?'Review & start':'Start a client’s onboarding'}</h2><p>{started?'Follow the saved request without creating it again.':review?'Check the details before the existing workflow starts.':'Save the intake, then review and start when you’re ready.'}</p></div></div>
   {loading?<p role="status">Loading onboarding…</p>:started?<div className={styles.result}>
    <span className={styles.status} data-state={record.state}>{record.state==='queued'||record.state==='existing'?<Check size={17}/>:null}{labels[record.state]}</span><h3>{record.intake.company}</h3><p>{record.intake.name} · {record.intake.email}</p>
    {record.issue&&<p className={styles.notice}>{record.issue}</p>}
    {record.state==='queued'&&<p>The task and its fields are confirmed in ClickUp. The existing Zap handles channel setup and the welcome message; its completion has not been verified here.</p>}
    {record.task_id&&<a className={styles.link} href={taskLink(record.task_id)} target="_blank" rel="noreferrer">Open ClickUp task <ExternalLink size={15}/></a>}
    <div className={styles.actions}>{['starting','uncertain','needs_review'].includes(record.state)&&<button disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>Check saved result</button>}<button disabled={busy} onClick={fresh}><Plus size={16}/>New client</button></div>
    <div className={styles.manual}><strong>Still handled by Elias</strong><p>Add the client to Slack, invite them to Skool, share ELITE, and record/send the personal welcome video. These steps are not marked complete by this request.</p></div>
   </div>:review&&record?<div className={styles.review}>
    <dl><dt>Client / company</dt><dd>{record.intake.company}</dd><dt>Primary contact</dt><dd>{record.intake.name}<br/>{record.intake.email}</dd>{record.intake.partnerName&&<><dt>Second partner</dt><dd>{record.intake.partnerName}<br/>{record.intake.partnerEmail}</dd></>}<dt>Program</dt><dd>ELITE · existing welcome workflow</dd><dt>Sales-call recording</dt><dd>{record.intake.recording?'Included':'Not added yet — does not block setup'}</dd></dl>
    <div className={styles.notice}><strong>Starting has real effects.</strong><p>A new ClickUp task triggers the existing Zap to create a private Slack channel, add Elias and Viktor, and post the welcome message with the onboarding form. Existing Zapier usage applies.</p><p>If this email already has an entry, we’ll show that task without starting it again.</p></div>
    <label className={styles.consent}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>This is a confirmed ELITE client. Start their Slack setup and welcome message.</label>
    <div className={styles.actions}><button disabled={busy} onClick={()=>{setReview(false);setConfirmed(false);}}>Edit draft</button><button className={styles.primary} disabled={busy||!confirmed||!connected} onClick={()=>void start()}>{busy?<LoaderCircle className={styles.spin} size={17}/>:<ArrowRight size={17}/>}Start onboarding</button></div>
   </div>:<form onSubmit={save}>
    <div className={styles.grid}>{fields('company','Client / company name','e.g. Nalify',true)}{fields('name','Primary contact name','Full name',true)}{fields('email','Primary contact email','name@company.com',true,'email')}</div>
    <details className={styles.details}><summary>Second partner (optional)</summary><div className={styles.grid}>{fields('partnerName','Partner name','Full name')}{fields('partnerEmail','Partner email','partner@company.com',false,'email')}</div></details>
    <details className={styles.details}><summary>Sales-call context (optional)</summary><p>Add existing links if available. This step does not generate a briefing yet.</p><div className={styles.grid}>{fields('recording','Fathom recording','https://fathom.video/share/…',false,'url')}{fields('transcript','Google Docs transcript','https://docs.google.com/document/…',false,'url')}</div></details>
    <div className={styles.formFooter}><p>ELITE workflow · Saving a draft sends nothing.</p><button className={styles.primary} disabled={busy||loading} type="submit">{busy?<LoaderCircle className={styles.spin} size={17}/>:<ArrowRight size={17}/>}Save & review</button></div>
   </form>}
  </div><aside className={styles.aside}><p className={styles.eyebrow}>THE CURRENT WORKFLOW</p><h2>One clear handoff.</h2><ol><li><strong>Save the client</strong><p>Keep their contact details together.</p></li><li><strong>Start the existing setup</strong><p>ClickUp hands off to the Slack automation already in place.</p></li><li><strong>Elias welcomes them</strong><p>Client invitations and the personal video stay with Elias.</p></li></ol><p className={styles.footnote}>The client fills out their questionnaire after the welcome video. Their response is not required to start setup.</p></aside></div>
  <section className={styles.history}><div className={styles.historyHeading}><div><h2>Recent onboarding</h2><p>Saved in the portal · up to 100 recent entries</p></div>{record&&<button disabled={busy||loading} onClick={fresh}><Plus size={16}/>New client</button>}</div>{!records.length?<p className={styles.empty}>Your first client starts here. Existing ClickUp entries are checked when you start an onboarding.</p>:<div className={styles.rows}>{records.map(row=><button key={row.id} disabled={busy} onClick={()=>choose(row)} className={styles.row}><span><strong>{row.intake.company}</strong><small>{row.intake.email}</small></span><span className={styles.status} data-state={row.state}>{labels[row.state]}</span><ArrowRight size={16}/></button>)}</div>}</section>
 </section>;
}
